const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),http=require('node:http');
const C=require('../core.js');
let pw;try{pw=require('playwright');}catch{pw=require(path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
const getDoc=page=>page.evaluate(()=>DiagramEditor.getDocument());
async function serve(){
  const root=path.resolve(__dirname,'..'),allowed=new Set(['index.html','editor.css','icon.svg','core.js','render.js','output.js','parts.js','layout.js','transitions.js','editor.js','storage.js','local-autosave.js']);
  const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml'};
  const server=http.createServer(async(req,res)=>{const name=new URL(req.url,'http://localhost').pathname.slice(1)||'index.html';if(!allowed.has(name))return res.writeHead(404).end();try{res.writeHead(200,{'Content-Type':types[path.extname(name)]});res.end(await fs.readFile(path.join(root,name)));}catch{res.writeHead(404).end();}});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));return {url:`http://127.0.0.1:${server.address().port}/`,close:()=>new Promise(resolve=>server.close(resolve))};
}
async function menu(page,id){if(await page.locator('#'+id).getAttribute('open')===null)await page.locator('#'+id+' > summary').click();}
async function fill(page,id,value){await page.locator('#'+id).fill(String(value));await page.locator('#'+id).press('Tab');}
async function settings(page){if(await page.locator('.toolbar').getAttribute('data-compact')==='true'&&await page.locator('#toolbar-toggle').getAttribute('aria-expanded')!=='true')await page.locator('#toolbar-toggle').click();await menu(page,'settings-menu');}
async function load(page,doc){await page.locator('#file-input').setInputFiles({name:'output.diagram.json',mimeType:'application/json',buffer:Buffer.from(C.serializeDocument(doc))});await page.locator('[data-open-source="local-file"]').click();if(await page.locator('#confirm-dialog').isVisible())await page.locator('#confirm-continue').click();await page.waitForFunction(id=>DiagramEditor.getDocument().id===id,doc.id);}
function sample(){const d=C.createDocument();d.title='出力寸法の確認';d.nodes=[C.createNode('process',100,100,{id:'red',w:200,h:100,style:{fill:'#ff0000',stroke:'#000000'}}),C.createNode('process',1000,600,{id:'outside',text:'選択外の部品',style:{fill:'#0000ff'}})];return d;}
async function download(page,id,file){const waiting=page.waitForEvent('download');await page.locator('#'+id).click();const result=await waiting;await result.saveAs(file);return fs.readFile(file);}
async function pixels(page,png){return page.evaluate(async base64=>{const image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=reject;image.src='data:image/png;base64,'+base64;});const canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;const ctx=canvas.getContext('2d');ctx.drawImage(image,0,0);const data=ctx.getImageData(0,0,canvas.width,canvas.height).data;let red=0,blue=0;for(let i=0;i<data.length;i+=4){if(data[i]>240&&data[i+1]<10&&data[i+2]<10&&data[i+3]>240)red++;if(data[i]<10&&data[i+1]<10&&data[i+2]>240&&data[i+3]>240)blue++;}return{w:image.width,h:image.height,corner:[...data.slice(0,4)],red,blue};},png.toString('base64'));}
async function printGeometry(page){return page.evaluate(()=>{const sheet=document.getElementById('print-sheet');sheet.classList.add('is-measuring');try{const host=sheet.querySelector('.print-diagram'),svg=host.querySelector('svg'),a=host.getBoundingClientRect(),b=svg.getBoundingClientRect();return {x:b.x-a.x,y:b.y-a.y,w:b.width,h:b.height,availableW:a.width,availableH:a.height,pages:sheet.children.length,names:sheet.querySelectorAll('.print-name-field').length};}finally{sheet.classList.remove('is-measuring');}});}
async function check(browser,url,artifacts,engine){
  const context=await browser.newContext({viewport:{width:1280,height:800},acceptDownloads:true});
  try{
    const page=await context.newPage(),errors=[];page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.waitForFunction(()=>!!window.DiagramEditor);
    const doc=sample();await load(page,doc);await menu(page,'file-menu');await page.locator('#save-browser').click();
    const savedBefore=await page.evaluate(()=>[localStorage.getItem('kaijo.diagram.recovery.v1'),localStorage.getItem('kaijo.diagram.saved.v1')]);
    await page.evaluate(()=>DiagramEditor.select(['red']));await page.locator('[data-pane-button="export"]').click();await page.locator('#export-scope').selectOption('selection');await page.locator('#export-size-mode').selectOption('width');await fill(page,'export-width',978);
    await page.locator('#export-margins > summary').click();for(const [side,value] of Object.entries({top:20,right:40,bottom:60,left:80}))await fill(page,'export-'+side,value);
    await page.locator('#transparent').check();assert.match(await page.locator('#export-name').textContent(),/978 × 558 px/);
    const png=await download(page,'export-png',path.join(artifacts,engine+'-custom.png')),decoded=await pixels(page,png);assert.equal(png.readUInt32BE(16),978);assert.equal(png.readUInt32BE(20),558);assert.equal(decoded.corner[3],0);assert.ok(decoded.red>100000);assert.equal(decoded.blue,0,'Selection export excludes the other node');
    const svg=(await download(page,'export-svg',path.join(artifacts,engine+'-custom.svg'))).toString();assert.match(svg,/viewBox="17 77 326 186"/);assert.doesNotMatch(svg,/選択外の部品|#0000ff/);
    await page.locator('#transparent').uncheck();const white=await pixels(page,await download(page,'export-png',path.join(artifacts,engine+'-white.png')));assert.deepEqual(white.corner,[255,255,255,255]);
    await page.locator('#export-size-mode').selectOption('height');await fill(page,'export-height',372);assert.match(await page.locator('#export-name').textContent(),/652 × 372 px/);
    await page.locator('#export-size-mode').selectOption('width');await fill(page,'export-width',0);assert.equal(await page.locator('#export-png').isDisabled(),true);assert.equal(await page.locator('#export-error').isVisible(),true);
    await fill(page,'export-width',100000);const cap=(await page.locator('#export-name').textContent()).match(/PNG (\d+) × (\d+) px/);assert.ok(Number(cap[1])<=8192&&Number(cap[2])<=8192&&Number(cap[1])*Number(cap[2])<=32000000);assert.match(await page.locator('#export-name').textContent(),/解像度を調整/);await fill(page,'export-width',978);
    await settings(page);await page.locator('#theme').selectOption('dark');await page.locator('#settings-menu > summary').press('Escape');assert.match(await page.locator('#export-preview').innerHTML(),/#ff0000/);
    assert.deepEqual(await getDoc(page),doc);assert.equal(await page.locator('#undo').isDisabled(),true);assert.deepEqual(await page.evaluate(()=>[localStorage.getItem('kaijo.diagram.recovery.v1'),localStorage.getItem('kaijo.diagram.saved.v1')]),savedBefore,'Output settings do not mark or save the drawing');
    await page.screenshot({path:path.join(artifacts,engine+'-output-wide.png')});
    await page.locator('#side-print').click();await page.locator('#print-size-mode').selectOption('width');await fill(page,'print-width',80);await page.locator('#print-align').selectOption('right');await page.locator('#print-valign').selectOption('bottom');await page.locator('#print-name').check();
    for(const [paper,orientation] of [['A4','landscape'],['B5','portrait']]){
      await page.locator('#print-paper').selectOption(paper);await page.locator('#print-orientation').selectOption(orientation);const g=await printGeometry(page);
      assert.ok(Math.abs(g.w*25.4/96-80)<.05);assert.ok(Math.abs(g.x+g.w-g.availableW)<.2);assert.ok(Math.abs(g.y+g.h-g.availableH)<.2);assert.equal(g.pages,1);assert.equal(g.names,1);
      const previewStyle=await page.locator('#print-preview .print-diagram svg').getAttribute('style'),actualStyle=await page.locator('#print-sheet .print-diagram svg').getAttribute('style');assert.equal(previewStyle,actualStyle);
      if(engine==='chromium')await page.pdf({path:path.join(artifacts,`${paper}-${orientation}.pdf`),preferCSSPageSize:true,printBackground:true});
    }
    await fill(page,'print-width',999);assert.match(await page.locator('#print-summary').textContent(),/用紙に収まる幅へ縮小/);const fitted=await printGeometry(page);assert.ok(fitted.w<=fitted.availableW+.1&&fitted.h<=fitted.availableH+.1);
    await fill(page,'print-width',0);assert.equal(await page.locator('#print-submit').isDisabled(),true);assert.equal(await page.locator('#print-error').isVisible(),true);await fill(page,'print-width',80);
    await page.screenshot({path:path.join(artifacts,engine+'-print-wide.png')});await page.locator('#print-dialog [data-close-dialog]').click();assert.deepEqual(await getDoc(page),doc);
    await page.reload();await page.locator('[data-open-source="browser-manual"]').click();await page.locator('[data-pane-button="export"]').click();assert.equal(await page.locator('#export-size-mode').inputValue(),'width');assert.equal(await page.locator('#export-width').inputValue(),'978');for(const [side,value]of Object.entries({top:'20',right:'40',bottom:'60',left:'80'}))assert.equal(await page.locator('#export-'+side).inputValue(),value);
    await page.locator('#side-print').click();assert.equal(await page.locator('#print-width').inputValue(),'80');assert.equal(await page.locator('#print-align').inputValue(),'right');assert.equal(await page.locator('#print-valign').inputValue(),'bottom');assert.deepEqual(await getDoc(page),doc);
    await fill(page,'print-width',0);await page.locator('#print-dialog [data-close-dialog]').click();const latest=sample();latest.title='印刷前に開いた現在の図';await load(page,latest);
    await page.evaluate(()=>window.dispatchEvent(new Event('beforeprint')));assert.equal(await page.locator('#print-sheet h1').textContent(),latest.title);assert.ok(Math.abs((await printGeometry(page)).w*25.4/96-80)<.05,'Native print rebuilds the current document with the previous valid width');assert.deepEqual(await getDoc(page),latest);assert.deepEqual(errors,[]);
  }finally{await context.close();}
}
async function mobile(browser,url,artifacts,engine){
  const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true});
  try{const page=await context.newPage(),errors=[];page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.waitForFunction(()=>!!window.DiagramEditor);await settings(page);await page.locator('#theme').selectOption('dark');await page.locator('#text-size').selectOption('largest');await page.locator('#settings-menu > summary').press('Escape');await load(page,sample());await page.locator('[data-pane-button="export"]').tap();await page.locator('#export-size-mode').selectOption('width');await fill(page,'export-width',600);await page.locator('#export-margins > summary').tap();await fill(page,'export-left',50);
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=390),true);await page.screenshot({path:path.join(artifacts,engine+'-output-390.png'),fullPage:true});await page.locator('#side-print').tap();await page.locator('#print-size-mode').selectOption('width');await fill(page,'print-width',70);await page.locator('#print-align').selectOption('left');await page.locator('#print-valign').selectOption('top');
    const g=await printGeometry(page);assert.ok(Math.abs(g.w*25.4/96-70)<.05);assert.ok(Math.abs(g.x)<.1&&Math.abs(g.y)<.1);const dialog=await page.locator('#print-dialog').boundingBox();assert.ok(dialog.x>=0&&dialog.x+dialog.width<=391);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=390),true);
    for(const id of ['print-paper','print-size-mode','print-width','print-align','print-submit'])assert.ok((await page.locator('#'+id).boundingBox()).height>=43,id+' tap target');
    await page.screenshot({path:path.join(artifacts,engine+'-print-390.png'),fullPage:true});await page.keyboard.press('Escape');assert.equal(await page.locator('#print-dialog').isHidden(),true);assert.equal(await page.locator('#side-print').evaluate(el=>el===document.activeElement),true);assert.deepEqual(errors,[]);
  }finally{await context.close();}
}
(async()=>{const host=await serve(),artifacts=path.join(os.tmpdir(),'joho-flowchart-output-browser');await fs.mkdir(artifacts,{recursive:true});try{for(const engine of process.argv.includes('--chrome-only')?['chromium']:['chromium','webkit']){const browser=await pw[engine].launch(engine==='chromium'?{channel:'chrome',headless:true}:{headless:true});try{await check(browser,host.url,artifacts,engine);await mobile(browser,host.url,artifacts,engine);console.log(engine+': custom PNG pixels, SVG margins, print width and placement, persistence and narrow touch UI passed');}finally{await browser.close();}}}finally{await host.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
