/* Reviewed branch/loop layout, transition editing, activity sets and templates. */
const assert=require('node:assert/strict');
const fs=require('node:fs/promises'),http=require('node:http'),os=require('node:os'),path=require('node:path');
const C=require('../core.js'),Q=require('../layout.js'),T=require('../transitions.js');
let pw;try{pw=require('playwright');}catch{pw=require(path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
async function serve(){
  const allowed=new Set(['index.html','core.js','render.js','layout.js','transitions.js','parts.js','output.js','storage.js','local-autosave.js','editor.js','editor.css','icon.svg']);
  const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml'};
  const server=http.createServer(async(req,res)=>{const file=new URL(req.url,'http://localhost').pathname.slice(1)||'index.html';if(!allowed.has(file))return res.writeHead(404).end();try{res.writeHead(200,{'Content-Type':`${types[path.extname(file)]}; charset=utf-8`});res.end(await fs.readFile(path.join(__dirname,'..',file)));}catch{res.writeHead(404).end();}});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));return{url:`http://127.0.0.1:${server.address().port}/`,close:()=>new Promise(resolve=>server.close(resolve))};
}
const getDoc=page=>page.evaluate(()=>DiagramEditor.getDocument());
const select=(page,ids)=>page.evaluate(ids=>DiagramEditor.select(ids),ids);
async function menu(page,id){const target=page.locator('#'+id);if(await page.locator('.toolbar').getAttribute('data-compact')==='true'){const needed=await target.evaluate(el=>!!el.closest('#toolbar-options')),expanded=await page.locator('#toolbar-toggle').getAttribute('aria-expanded')==='true';if(needed!==expanded)await page.locator('#toolbar-toggle').click();}if(!await target.evaluate(el=>el.open))await target.locator(':scope > summary').click();}
async function load(page,doc){await page.locator('#file-input').setInputFiles({name:'three-diagrams.diagram.json',mimeType:'application/json',buffer:Buffer.from(C.serializeDocument(doc))});await page.waitForFunction(()=>document.getElementById('storage-open-dialog').open);await page.locator('[data-open-source="local-file"]').click();if(await page.locator('#confirm-dialog').isVisible())await page.locator('#confirm-continue').click();await page.waitForFunction(expected=>JSON.stringify(DiagramEditor.getDocument())===expected,JSON.stringify(C.parseDocument(doc)));}
async function openLayout(page){await menu(page,'align-menu');await page.locator('#auto-layout-button').click();await page.waitForFunction(()=>document.getElementById('layout-dialog').open);}
async function openTransitions(page){await menu(page,'shape-menu');await page.locator('#adjust-transitions').click();await page.waitForFunction(()=>document.getElementById('transition-dialog').open);}
async function close(page,id){await page.keyboard.press('Escape');await page.waitForFunction(id=>!document.getElementById(id).open,id);}
async function undoOnce(page,before,after){await page.locator('#undo').click();assert.deepEqual(await getDoc(page),before,'One undo restores the complete document');await page.locator('#redo').click();assert.deepEqual(await getDoc(page),after);}
async function saved(page){await menu(page,'file-menu');const promise=page.waitForEvent('download');await page.locator('#save-file').click();const download=await promise,chunks=[];for await(const c of await download.createReadStream())chunks.push(c);return C.parseDocument(Buffer.concat(chunks).toString('utf8'));}
async function printPreview(page,doc){await menu(page,'file-menu');await page.locator('#print-button').click();assert.equal(await page.locator('#print-preview .print-diagram svg > g:last-of-type > g').count(),doc.nodes.length);await close(page,'print-dialog');}
async function structuredLayout(page){
  for(const id of ['flow-choice','flow-while','flow-repeat','flow-branch']){
    const doc=C.createTemplate(id),ids=doc.nodes.map(n=>n.id);await load(page,doc);await select(page,ids);const undo=await page.locator('#undo').isDisabled();await openLayout(page);
    await page.locator('#layout-direction').selectOption('vertical');await page.locator('#layout-gap').fill('64');await page.locator('#layout-branch-gap').fill('100');await page.locator('#layout-flip').uncheck();await page.locator('#layout-route').check();
    assert.equal(await page.locator('#layout-apply').isDisabled(),false,`${id}: ${await page.locator('#layout-message').textContent()}`);assert.match(await page.locator('#layout-message').textContent(),id==='flow-choice'?/分岐と合流/:/反復/);assert.deepEqual(await getDoc(page),doc);assert.equal(await page.locator('#undo').isDisabled(),undo);
    await page.locator('#layout-branch-gap').fill('401');assert.equal(await page.locator('#layout-apply').isDisabled(),true);await page.locator('#layout-branch-gap').fill('100');await close(page,'layout-dialog');assert.deepEqual(await getDoc(page),doc);
    await openLayout(page);await page.locator('#layout-apply').click();let after=await getDoc(page);assert.deepEqual(after,Q.plan(doc,ids,{gap:64,branchGap:100}).document);await undoOnce(page,doc,after);
    await openLayout(page);await page.locator('#layout-direction').selectOption('horizontal');await page.locator('#layout-flip').check();await page.locator('#layout-apply').click();const horizontal=await getDoc(page);assert.deepEqual(horizontal,Q.plan(after,ids,{direction:'horizontal',gap:64,branchGap:100,flipBranches:true}).document);await undoOnce(page,after,horizontal);
    assert.deepEqual(await saved(page),horizontal);await printPreview(page,horizontal);
  }
}
async function transitions(page){
  const doc=C.createTemplate('state-device'),edge=doc.edges[0],loop=doc.edges.find(e=>e.from.nodeId===e.to.nodeId);await load(page,doc);await select(page,[edge.id]);await openTransitions(page);
  assert.match(await page.locator('#transition-note').textContent(),/曲線/);await page.locator('#transition-related').uncheck();assert.equal(await page.locator('#transition-apply').isDisabled(),true);await page.locator('#transition-related').check();await page.locator('#transition-spacing').fill('72');assert.deepEqual(await getDoc(page),doc);await close(page,'transition-dialog');
  await openTransitions(page);await page.locator('#transition-apply').click();const spaced=await getDoc(page);assert.deepEqual(spaced,T.plan(doc,[edge.id],{spacing:72}).document);await undoOnce(page,doc,spaced);
  await select(page,[loop.id]);await openTransitions(page);assert.equal(await page.locator('#transition-mode').inputValue(),'loop');await page.locator('#transition-side').selectOption('top');await page.locator('#transition-distance').fill('120');await page.locator('#transition-apply').click();const looped=await getDoc(page);assert.equal(looped.edges.find(e=>e.id===loop.id).from.side,'top');await undoOnce(page,spaced,looped);
  await select(page,[edge.id]);await openTransitions(page);await page.locator('#transition-mode').selectOption('label');await page.locator('#transition-related').uncheck();await page.locator('#transition-label-t').selectOption('0.8');await page.locator('#transition-label-x').fill('24');await page.locator('#transition-label-y').fill('-32');await page.locator('#transition-apply').click();const labeled=await getDoc(page);assert.deepEqual(labeled,T.plan(looped,[edge.id],{mode:'label',related:false,t:.8,dx:24,dy:-32}).document);await undoOnce(page,looped,labeled);
  await openTransitions(page);await page.locator('#transition-mode').selectOption('reset-label');assert.equal(await page.locator('#transition-label-fields').isVisible(),false);await page.locator('#transition-apply').click();assert.deepEqual((await getDoc(page)).edges[0].label,{text:edge.label.text,t:.5,dx:0,dy:-12});await page.locator('#undo').click();assert.deepEqual(await getDoc(page),labeled);assert.deepEqual(await saved(page),labeled);await printPreview(page,labeled);await load(page,labeled);
  const fixed=C.clone(doc);fixed.edges[1].locked=true;await load(page,fixed);await select(page,[edge.id]);await openTransitions(page);await page.locator('#transition-related').check();assert.equal(await page.locator('#transition-apply').isDisabled(),true);assert.match(await page.locator('#transition-message').textContent(),/固定/);assert.deepEqual(await getDoc(page),fixed);await close(page,'transition-dialog');
}
function lanes(){const d=C.createDocument('activity');d.nodes=[C.createNode('action',90,130,{id:'a',laneId:d.lanes[0].id,text:'依頼'}),C.createNode('action',125,335,{id:'b',laneId:d.lanes[0].id,text:'受取'}),C.createNode('action',410,210,{id:'c',laneId:d.lanes[1].id,text:'確認'})];d.edges=[C.createEdge({nodeId:'a'},{nodeId:'b'},{id:'ab'}),C.createEdge({nodeId:'a'},{nodeId:'c'},{id:'ac',waypoints:[{x:315,y:100},{x:375,y:100}]})];return d;}
async function activity(page){
  for(const kind of ['branch','parallel']){
    const doc=C.createDocument('activity');await load(page,doc);await page.locator(`[data-activity-set="${kind}"]`).click();assert.ok(await page.locator('#activity-set-preview svg').count());assert.deepEqual(await getDoc(page),doc);await close(page,'activity-set-dialog');await page.waitForFunction(kind=>document.activeElement?.dataset.activitySet===kind,kind);
    await page.locator(`[data-activity-set="${kind}"]`).click();await page.locator('#activity-set-second').selectOption(doc.lanes[0].id);assert.equal(await page.locator('#activity-set-apply').isDisabled(),true);assert.match(await page.locator('#activity-set-message').textContent(),/余白/);assert.deepEqual(await getDoc(page),doc);await page.locator('#activity-set-second').selectOption(doc.lanes[1].id);await page.locator('#activity-set-y').fill('100');await page.locator('#activity-set-apply').click();const after=await getDoc(page);assert.equal(after.nodes.length,4);assert.equal(after.edges.length,4);assert.equal(after.groups.length,1);assert.deepEqual(after.lanes,doc.lanes);await undoOnce(page,doc,after);assert.deepEqual(await saved(page),after);await printPreview(page,after);
    await select(page,after.nodes.map(n=>n.id));await openLayout(page);await page.locator('#layout-mode').selectOption('lanes');assert.equal(await page.locator('#layout-apply').isDisabled(),true);await close(page,'layout-dialog');
  }
  const doc=lanes();await load(page,doc);await select(page,doc.nodes.map(n=>n.id));await openLayout(page);await page.locator('#layout-mode').selectOption('lanes');await page.locator('#layout-gap').fill('70');assert.equal(await page.locator('#layout-direction').isDisabled(),true);assert.equal(await page.locator('#layout-branch-options').isVisible(),false);await page.locator('#layout-apply').click();const after=await getDoc(page);assert.deepEqual(after,Q.plan(doc,doc.nodes.map(n=>n.id),{mode:'lanes',gap:70}).document);assert.deepEqual(after.edges.find(e=>e.id==='ac'),doc.edges[1]);await undoOnce(page,doc,after);
  await menu(page,'layer-menu');await page.locator('button[data-layer="lanes"]').click();assert.equal(await page.locator('#layer-menu > summary').isVisible(),true);await menu(page,'layer-menu');await page.locator('button[data-layer="diagram"]').click();assert.deepEqual(await getDoc(page),after);
}
async function templates(page){
  for(const type of ['flowchart','activity','state']){
    await load(page,C.createDocument(type));await page.locator('[data-pane-button="templates"]').click();assert.equal(await page.locator('[data-template]').count(),C.TEMPLATES.filter(t=>t.diagramType===type).length);
    const meta=C.TEMPLATES.find(t=>t.diagramType===type&&['flow-repeat','activity-choice','state-progress'].includes(t.id));await page.locator(`[data-template="${meta.id}"]`).click();if(await page.locator('#confirm-dialog').isVisible())await page.locator('#confirm-continue').click();await page.waitForFunction(title=>DiagramEditor.getDocument().title===title,meta.title);const doc=await getDoc(page);assert.equal(doc.diagramType,type);assert.deepEqual(await saved(page),doc);await printPreview(page,doc);
  }
}
async function fits(page,id,width){for(const target of [`#${id} h2`,`#${id} .dialog-actions`]){const box=await page.locator(target).boundingBox();assert.ok(box&&box.x>=0&&box.y>=0&&box.x+box.width<=width+.5&&box.y+box.height<=820.5,`${target} visible at ${width}`);}assert.equal(await page.locator('#'+id).evaluate(el=>el.scrollWidth<=el.clientWidth+1),true);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);for(const checkbox of await page.locator(`#${id} .check input[type=checkbox]`).all()){if(!await checkbox.isVisible())continue;const box=await checkbox.boundingBox(),label=await checkbox.locator('..').boundingBox();assert.ok(box.width<=24&&box.height<=24&&label.height>=44,'Compact checkboxes keep a label sized for touch');}}
async function snapshot(page,name){if(!process.env.FLOWCHART_ARTIFACT_DIR)return;await fs.mkdir(process.env.FLOWCHART_ARTIFACT_DIR,{recursive:true});await page.screenshot({path:path.join(process.env.FLOWCHART_ARTIFACT_DIR,name+'.png')});}
async function responsive(browser,url,width,errors){
  const context=await browser.newContext({viewport:{width,height:820},hasTouch:width===390}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
  try{await page.goto(url);await page.waitForFunction(()=>!!window.DiagramEditor);await menu(page,'settings-menu');await page.locator('#theme').selectOption('dark');await page.locator('#text-size').selectOption('largest');await page.keyboard.press('Escape');
    const doc=C.createTemplate('flow-choice');await load(page,doc);await select(page,doc.nodes.map(n=>n.id));await openLayout(page);await fits(page,'layout-dialog',width);await snapshot(page,`layout-${width}`);await page.locator('#layout-direction').focus();await page.keyboard.press('Tab');assert.equal(await page.locator('#layout-gap').evaluate(el=>el===document.activeElement),true);await page.keyboard.press('Shift+Tab');assert.equal(await page.locator('#layout-direction').evaluate(el=>el===document.activeElement),true);await close(page,'layout-dialog');
    const state=C.createTemplate('state-device');await load(page,state);await select(page,[state.edges[0].id]);await openTransitions(page);await fits(page,'transition-dialog',width);await snapshot(page,`transition-${width}`);await page.locator('#transition-mode').selectOption('label');await page.locator('#transition-label-x').fill('20');await fits(page,'transition-dialog',width);if(width===390)await page.locator('#transition-apply').tap();else await page.locator('#transition-apply').press('Enter');assert.equal((await getDoc(page)).edges[0].label.dx,20);
    await load(page,C.createDocument('activity'));await page.locator('[data-activity-set="parallel"]').click();await fits(page,'activity-set-dialog',width);await snapshot(page,`activity-set-${width}`);if(width===390)await page.locator('#activity-set-apply').tap();else await page.locator('#activity-set-apply').press('Enter');assert.equal((await getDoc(page)).nodes.length,4);
    const toolbar=await page.locator('.toolbar').boundingBox();assert.ok(toolbar.height<90,'The top toolbar remains one row');
  }finally{await context.close();}
}
(async()=>{const local=process.env.FLOWCHART_TEST_URL?null:await serve(),url=process.env.FLOWCHART_TEST_URL||local.url,browser=await pw.chromium.launch({channel:'chrome',headless:true}),errors=[];
  try{const requested=process.argv.slice(2).filter(arg=>arg!=='--chrome-only');if(requested.some(name=>!['structuredLayout','transitions','activity','templates','responsive'].includes(name)))throw new Error('Unknown test case');const enabled=name=>!requested.length||requested.includes(name);const page=await browser.newPage({viewport:{width:1280,height:820}});page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400&&!r.url().includes('favicon'))errors.push(`${r.status()} ${r.url()}`);});await page.goto(url);await page.waitForFunction(()=>!!window.DiagramEditor);for(const run of [structuredLayout,transitions,activity,templates])if(enabled(run.name)){await run(page);console.log(`${run.name} PASS`);}await page.close();if(enabled('responsive'))for(const width of [1280,736,390])await responsive(browser,url,width,errors);assert.deepEqual(errors,[]);console.log(`Chrome three diagrams PASS (${requested.join(' / ')||'1280 / 736 / 390, preview / undo / files / print / keyboard / touch / dark / largest'})`);}
  finally{await browser.close();if(local)await local.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
