/* eslint-disable */
/**
 * Auto-generated FAQ data.
 * Generated at: 2026-05-08 13:52:43 JST
 * Do not edit this file directly.
 *
 * course:
 *  - il
 *  - html
 *  - ss
 *  - py
 *
 * displayPages:
 *  - pageKey array without ".html"
 *  - [] means "show on all pages matching course"
 */

(function(global) {
  'use strict';

  const FAQ_CATEGORY_DATA = [
  {
    "type": "category",
    "key": "operation",
    "label": "操作方法",
    "parent": "",
    "sortOrder": 10,
    "enabled": true
  },
  {
    "type": "category",
    "key": "trouble",
    "label": "トラブル",
    "parent": "",
    "sortOrder": 20,
    "enabled": true
  },
  {
    "type": "category",
    "key": "submit",
    "label": "保存・提出",
    "parent": "",
    "sortOrder": 30,
    "enabled": true
  },
  {
    "type": "category",
    "key": "term",
    "label": "用語",
    "parent": "",
    "sortOrder": 40,
    "enabled": true
  },
  {
    "type": "category",
    "key": "concept",
    "label": "考え方",
    "parent": "",
    "sortOrder": 50,
    "enabled": true
  },
  {
    "type": "category",
    "key": "error",
    "label": "エラー",
    "parent": "",
    "sortOrder": 60,
    "enabled": true
  },
  {
    "type": "category",
    "key": "design",
    "label": "デザイン判断",
    "parent": "",
    "sortOrder": 70,
    "enabled": true
  },
  {
    "type": "category",
    "key": "assessment",
    "label": "採点・評価",
    "parent": "",
    "sortOrder": 80,
    "enabled": true
  },
  {
    "type": "category",
    "key": "advanced",
    "label": "発展",
    "parent": "",
    "sortOrder": 90,
    "enabled": true
  },
  {
    "type": "course",
    "key": "il",
    "label": "Illustrator実習",
    "parent": "",
    "sortOrder": 10,
    "enabled": true
  },
  {
    "type": "course",
    "key": "html",
    "label": "HTML実習",
    "parent": "",
    "sortOrder": 20,
    "enabled": true
  },
  {
    "type": "course",
    "key": "ss",
    "label": "スプレッドシート実習",
    "parent": "",
    "sortOrder": 30,
    "enabled": true
  },
  {
    "type": "course",
    "key": "py",
    "label": "Python講座",
    "parent": "",
    "sortOrder": 40,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "html_basic",
    "label": "HTMLの基本",
    "parent": "html",
    "sortOrder": 10,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "html_tag",
    "label": "タグ",
    "parent": "html",
    "sortOrder": 20,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "html_link",
    "label": "リンク",
    "parent": "html",
    "sortOrder": 30,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "html_image",
    "label": "画像",
    "parent": "html",
    "sortOrder": 40,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "html_css",
    "label": "CSSの基本",
    "parent": "html",
    "sortOrder": 50,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "html_layout",
    "label": "レイアウト",
    "parent": "html",
    "sortOrder": 60,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "html_submit",
    "label": "提出・確認",
    "parent": "html",
    "sortOrder": 70,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "il_basic",
    "label": "基本操作",
    "parent": "il",
    "sortOrder": 10,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "il_save",
    "label": "保存・書き出し",
    "parent": "il",
    "sortOrder": 20,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "il_ui",
    "label": "画面・ツール",
    "parent": "il",
    "sortOrder": 30,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "il_path",
    "label": "線とパス",
    "parent": "il",
    "sortOrder": 40,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "il_text",
    "label": "文字",
    "parent": "il",
    "sortOrder": 50,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "il_pictogram",
    "label": "ピクトグラム",
    "parent": "il",
    "sortOrder": 60,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "il_color",
    "label": "配色",
    "parent": "il",
    "sortOrder": 70,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "il_submit",
    "label": "提出・相互評価",
    "parent": "il",
    "sortOrder": 80,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "py_colab",
    "label": "Colabの基本",
    "parent": "py",
    "sortOrder": 10,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "py_variable",
    "label": "printと変数",
    "parent": "py",
    "sortOrder": 20,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "py_input",
    "label": "入力",
    "parent": "py",
    "sortOrder": 30,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "py_if",
    "label": "条件分岐",
    "parent": "py",
    "sortOrder": 40,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "py_loop",
    "label": "繰り返し",
    "parent": "py",
    "sortOrder": 50,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "py_list",
    "label": "リスト",
    "parent": "py",
    "sortOrder": 60,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "py_function",
    "label": "関数",
    "parent": "py",
    "sortOrder": 70,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "py_graph",
    "label": "グラフ",
    "parent": "py",
    "sortOrder": 80,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "py_error",
    "label": "エラー対応",
    "parent": "py",
    "sortOrder": 90,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "ss_basic",
    "label": "基本操作",
    "parent": "ss",
    "sortOrder": 10,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "ss_ref",
    "label": "セル参照",
    "parent": "ss",
    "sortOrder": 20,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "ss_formula",
    "label": "数式",
    "parent": "ss",
    "sortOrder": 30,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "ss_function",
    "label": "関数",
    "parent": "ss",
    "sortOrder": 40,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "ss_autofill",
    "label": "オートフィル",
    "parent": "ss",
    "sortOrder": 50,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "ss_graph",
    "label": "グラフ",
    "parent": "ss",
    "sortOrder": 60,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "ss_analysis",
    "label": "データ分析",
    "parent": "ss",
    "sortOrder": 70,
    "enabled": true
  }
];

  const FAQ_DATA = [
  {
    "faqId": "il-001",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "保存・書き出し",
    "category": "保存・提出",
    "priority": 1,
    "sortOrder": 10,
    "question": "PNGファイルはどうやって書き出すか",
    "shortAnswer": "選択ツールで対象を選び、書き出し用に追加します。高さ400px、PNG形式で書き出してください。",
    "shortAnswerHtml": "選択ツールで対象を選び、書き出し用に追加します。高さ400px、PNG形式で書き出してください。",
    "bodyHtml": "まず、書き出したい図形を<span class=\"faq-tool\"><img src=\"./img/illustrator/selection_tool.png\" alt=\"\" class=\"faq-tool-icon\"><b>選択ツール</b></span>で選択します。<br><br><ol class=\"faq-steps\"><li>図形全体を選択する</li><li>右クリックする</li><li>書き出し用に追加を選ぶ</li><li>単一のアセットとしてを選ぶ</li><li>高さを <code>400 px</code> にする</li><li>保存形式を <code>PNG</code> にする</li><li>書き出しをクリックする</li></ol><br><br><aside class=\"faq-box faq-check\"><div class=\"faq-box-title\">確認</div><div class=\"faq-box-body\"><ul><li>保存先フォルダの中に <code>400h</code> フォルダができているか確認する</li><li>PNGファイルがその中に入っているか確認する</li><li>提出フォームで指定されたファイル形式になっているか確認する</li></ul></div></aside><br><br><aside class=\"faq-box faq-mistake\"><div class=\"faq-box-title\">よくあるミス</div><div class=\"faq-box-body\"><ul><li>図形を選択しないまま書き出そうとしている</li><li>PDFで保存する操作とPNGで書き出す操作を混同している</li><li>400hフォルダではなく親フォルダを見ている</li></ul></div></aside><br><br>詳しい手順は、<a href=\"il01.html#headline_4\" class=\"faq-page-link\" target=\"_blank\" rel=\"noopener noreferrer\">画像ファイルの書き出し方法</a>を確認してください。",
    "keywords": [
      "png",
      "書き出し",
      "画像",
      "400px",
      "400h",
      "アセット",
      "提出"
    ],
    "displayPages": [
      "il01",
      "il11",
      "il12"
    ],
    "relatedPage": "il01.html#headline_4",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-002",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "保存・書き出し",
    "category": "トラブル",
    "priority": 1,
    "sortOrder": 20,
    "question": "書き出したPNGファイルが見つからない",
    "shortAnswer": "保存先フォルダの中にできた400hフォルダを確認してください。",
    "shortAnswerHtml": "保存先フォルダの中にできた400hフォルダを確認してください。",
    "bodyHtml": "書き出したPNGファイルは、保存先として選んだフォルダの中に作成される <code>400h</code> フォルダに入ります。<br><br><ol class=\"faq-steps\"><li>書き出し時に選んだ保存先フォルダを開く</li><li>その中の <code>400h</code> フォルダを開く</li><li>PNGファイルが入っているか確認する</li></ol><br><br><aside class=\"faq-box faq-mistake\"><div class=\"faq-box-title\">よくあるミス</div><div class=\"faq-box-body\"><ul><li>保存先フォルダそのものを見ていて、400hフォルダを開いていない</li><li>別の場所に書き出している</li><li>PNGではなくPDFやAIファイルを探している</li></ul></div></aside><br><br>見つからない場合は、もう一度<a href=\"il01.html#headline_4\" class=\"faq-page-link\" target=\"_blank\" rel=\"noopener noreferrer\">画像ファイルの書き出し方法</a>を見ながら書き出してください。",
    "keywords": [
      "png",
      "見つからない",
      "400h",
      "保存先",
      "書き出し"
    ],
    "displayPages": [
      "il01",
      "il11",
      "il12"
    ],
    "relatedPage": "il01.html#headline_4",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-003",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "画面・ツール",
    "category": "トラブル",
    "priority": 1,
    "sortOrder": 30,
    "question": "ツールバーが消えた",
    "shortAnswer": "ウィンドウ ＞ ツールバー ＞ 基本 を選ぶと再表示できます。",
    "shortAnswerHtml": "ウィンドウ ＞ ツールバー ＞ 基本 を選ぶと再表示できます。",
    "bodyHtml": "ツールバーを誤って非表示にしてしまった場合は、メニューから再表示できます。<br><br><ol class=\"faq-steps\"><li><span class=\"faq-menu-path\"><span class=\"faq-menu-item\">ウィンドウ</span><span class=\"faq-menu-sep\">›</span><span class=\"faq-menu-item\">ツールバー</span><span class=\"faq-menu-sep\">›</span><span class=\"faq-menu-item\">基本</span></span> を選ぶ</li><li>左側にツールバーが表示されたことを確認する</li></ol><br><br><aside class=\"faq-box faq-check\"><div class=\"faq-box-title\">確認</div><div class=\"faq-box-body\"><ul><li>画面左側にツールバーが表示されているか</li><li>選択ツールや文字ツールが見えるか</li></ul></div></aside><br><br>それでも戻らない場合は、画面の状態を先生に見せてください。",
    "keywords": [
      "ツールバー",
      "消えた",
      "表示",
      "ウィンドウ",
      "基本"
    ],
    "displayPages": [
      "il02",
      "il03",
      "il04",
      "il11",
      "il12"
    ],
    "relatedPage": "il02.html#headline_1",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-004",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "基本操作",
    "category": "トラブル",
    "priority": 1,
    "sortOrder": 40,
    "question": "操作を間違えた。戻せるか",
    "shortAnswer": "⌘+Zで直前の操作を取り消せます。",
    "shortAnswerHtml": "⌘+Zで直前の操作を取り消せます。",
    "bodyHtml": "直前の操作は、<kbd class=\"faq-kbd\">⌘+Z</kbd> で取り消すことができます。<br><br><aside class=\"faq-box faq-point\"><div class=\"faq-box-title\">ポイント</div><div class=\"faq-box-body\"><ul><li>Illustratorでは、かなり前の操作まで戻せる場合があります。</li><li>ただし、保存やファイル操作のすべてが元に戻るわけではありません。</li></ul></div></aside><br><br><aside class=\"faq-box faq-mistake\"><div class=\"faq-box-title\">よくあるミス</div><div class=\"faq-box-body\"><ul><li>間違えたあとに何度も別の操作をしてしまう</li><li>元ファイルを上書き保存してしまう</li></ul></div></aside><br><br>大きく変更する前には、別名で保存しておくと安全です。",
    "keywords": [
      "戻す",
      "取り消し",
      "undo",
      "コマンドZ",
      "⌘Z"
    ],
    "displayPages": [
      "il01",
      "il02",
      "il03",
      "il04",
      "il11",
      "il12"
    ],
    "relatedPage": "il02.html#headline_1",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-010",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "ピクトグラム",
    "category": "考え方",
    "priority": 1,
    "sortOrder": 100,
    "question": "よいピクトグラムかどうか判断できない",
    "shortAnswer": "シンプルさ、視認性、意味の伝わりやすさ、配色を確認してください。",
    "shortAnswerHtml": "シンプルさ、視認性、意味の伝わりやすさ、配色を確認してください。",
    "bodyHtml": "よいピクトグラムかどうかは、見た目の好みだけではなく、情報が伝わるかどうかで判断します。<br><br><aside class=\"faq-box faq-check\"><div class=\"faq-box-title\">確認</div><div class=\"faq-box-body\"><ul><li>何を表しているか一目でわかる</li><li>形がシンプルである</li><li>細かすぎる装飾がない</li><li>背景と図形のコントラストがある</li><li>テーマに合っている</li></ul></div></aside><br><br><aside class=\"faq-box faq-point\"><div class=\"faq-box-title\">ポイント</div><div class=\"faq-box-body\"><ul><li>友人に一瞬だけ見せて、何を表しているか答えてもらうと確認しやすいです。</li><li>説明しないと伝わらない場合は、形をもう少し単純化してください。</li></ul></div></aside>",
    "keywords": [
      "ピクトグラム",
      "わかりやすい",
      "視認性",
      "シンプル",
      "テーマ"
    ],
    "displayPages": [
      "il11",
      "il12"
    ],
    "relatedPage": "il11.html#headline_2",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-012",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "提出・相互評価",
    "category": "保存・提出",
    "priority": 1,
    "sortOrder": 120,
    "question": "提出前に何を確認するか",
    "shortAnswer": "ファイル形式、ファイル名、PNG/AIファイル、見やすさを確認してください。",
    "shortAnswerHtml": "ファイル形式、ファイル名、PNG/AIファイル、見やすさを確認してください。",
    "bodyHtml": "提出前には、ファイル形式・ファイル名・見やすさを確認してください。<br><br><aside class=\"faq-box faq-check\"><div class=\"faq-box-title\">確認</div><div class=\"faq-box-body\"><ul><li>指定された形式のファイルになっている</li><li>PNGファイルとAIファイルなど、必要なファイルがそろっている</li><li>ファイル名が指示通りになっている</li><li>画像が小さすぎたり、見切れたりしていない</li><li>提出フォームで正しい課題を選んでいる</li></ul></div></aside><br><br><aside class=\"faq-box faq-mistake\"><div class=\"faq-box-title\">よくあるミス</div><div class=\"faq-box-body\"><ul><li>AIファイルだけを提出してPNGを忘れる</li><li>PNGだけを提出してAIファイルを忘れる</li><li>別の課題の提出フォームに送信してしまう</li></ul></div></aside>",
    "keywords": [
      "提出",
      "ファイル形式",
      "ファイル名",
      "PNG",
      "AI",
      "提出フォーム"
    ],
    "displayPages": [
      "il01",
      "il11",
      "il12"
    ],
    "relatedPage": "il11.html",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-013",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "保存・書き出し",
    "category": "トラブル",
    "priority": 1,
    "sortOrder": 130,
    "question": "「単一のアセットとして」がグレーアウトしている",
    "shortAnswer": "編集モードになっている可能性があります。何もないところをダブルクリックするか、画面上部の編集モードの左端の矢印をクリックして解除してください。",
    "shortAnswerHtml": "編集モードになっている可能性があります。何もないところをダブルクリックするか、画面上部の編集モードの左端の矢印をクリックして解除してください。",
    "bodyHtml": "「単一のアセットとして」がグレーアウトしている場合は、オブジェクトの編集モードに入っている可能性があります。<br><br>編集モードのままだと、通常の選択状態ではないため、書き出し用の操作が一部使えないことがあります。<br><br><ol class=\"faq-steps\"><li>アートボード上の何もないところをダブルクリックする</li><li>または、画面上部の編集モードのタブの左端にある矢印をクリックする</li><li>編集モードが解除されたことを確認する</li><li>もう一度、書き出したい図形を<span class=\"faq-tool\"><img src=\"./img/illustrator/selection_tool.png\" alt=\"\" class=\"faq-tool-icon\"><b>選択ツール</b></span>で選択する</li><li>右クリックして「書き出し用に追加」を選ぶ</li></ol><br><br><aside class=\"faq-box faq-check\"><div class=\"faq-box-title\">確認</div><div class=\"faq-box-body\"><ul><li>画面上部に編集モードの表示が残っていないか</li><li>図形全体を選択できているか</li><li>「単一のアセットとして」が選べるようになっているか</li></ul></div></aside><br><br><aside class=\"faq-box faq-mistake\"><div class=\"faq-box-title\">よくあるミス</div><div class=\"faq-box-body\"><ul><li>図形の中をダブルクリックして、さらに深い編集モードに入ってしまう</li><li>編集モードのまま右クリックしている</li><li>一部のパーツだけを選択している</li></ul></div></aside>",
    "keywords": [
      "単一のアセットとして",
      "グレーアウト",
      "編集モード",
      "書き出し",
      "アセット",
      "解除"
    ],
    "displayPages": [
      "il01",
      "il11",
      "il12"
    ],
    "relatedPage": "il01.html#headline_4",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-014",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "文字",
    "category": "操作方法",
    "priority": 1,
    "sortOrder": 140,
    "question": "文字の書式を変更するには",
    "shortAnswer": "文字を選択し、プロパティパネルのアピアランスから変更します。ふちを変える場合は「線」という文字をクリックします。",
    "shortAnswerHtml": "文字を選択し、プロパティパネルのアピアランスから変更します。ふちを変える場合は「線」という文字をクリックします。",
    "bodyHtml": "文字の書式を変更するには、文字を選択してからプロパティパネルを使います。<br><br><ol class=\"faq-steps\"><li><span class=\"faq-tool\"><img src=\"./img/illustrator/selection_tool.png\" alt=\"\" class=\"faq-tool-icon\"><b>選択ツール</b></span>で文字全体を選択する</li><li>プロパティパネルを確認する</li><li>文字の色を変える場合は「塗り」を変更する</li><li>文字のふちを変える場合は、アピアランスの「線」という文字をクリックする</li><li>線の色や線幅を変更する</li></ol><br><br><aside class=\"faq-box faq-point\"><div class=\"faq-box-title\">ポイント</div><div class=\"faq-box-body\"><ul><li>文字そのものの色は「塗り」、文字の輪郭は「線」で設定します。</li><li>文字の一部だけを変えたい場合は、<span class=\"faq-tool\"><img src=\"./img/illustrator/type_tool.png\" alt=\"\" class=\"faq-tool-icon\"><b>文字ツール</b></span>でその文字だけを選択してから変更します。</li></ul></div></aside><br><br><aside class=\"faq-box faq-mistake\"><div class=\"faq-box-title\">よくあるミス</div><div class=\"faq-box-body\"><ul><li>文字全体を選択していない</li><li>「線」の色だけを変えて、塗りの色が変わっていない</li><li>「線」という文字ではなく、別の場所をクリックしている</li></ul></div></aside>",
    "keywords": [
      "文字",
      "書式",
      "プロパティ",
      "アピアランス",
      "線",
      "塗り",
      "ふち",
      "色"
    ],
    "displayPages": [
      "il04"
    ],
    "relatedPage": "il04.html#headline_2",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-015",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "保存・書き出し",
    "category": "保存・提出",
    "priority": 1,
    "sortOrder": 150,
    "question": "AIファイルとPNGファイルの違いは",
    "shortAnswer": "AIファイルは編集用、PNGファイルは画像として提出・確認するためのファイルです。用途が違うので、課題の指示に従って必要な形式を提出してください。",
    "shortAnswerHtml": "AIファイルは編集用、PNGファイルは画像として提出・確認するためのファイルです。用途が違うので、課題の指示に従って必要な形式を提出してください。",
    "bodyHtml": "AIファイルとPNGファイルは用途が違います。<br><br><aside class=\"faq-box faq-check\"><div class=\"faq-box-title\">確認</div><div class=\"faq-box-body\"><ul><li>AIファイル → Illustratorで再編集するための元ファイル</li><li>PNGファイル → 画像として確認・提出するためのファイル</li><li>PDFファイル → 文書として確認・共有するためのファイル</li></ul></div></aside><br><br><aside class=\"faq-box faq-mistake\"><div class=\"faq-box-title\">よくあるミス</div><div class=\"faq-box-body\"><ul><li>AIファイルをPNG画像だと思って提出している</li><li>PNGだけを保存して、元のAIファイルを保存していない</li><li>PDF保存とPNG書き出しを混同している</li></ul></div></aside><br><br>課題で指定された形式をよく確認してください。",
    "keywords": [
      "ai",
      "png",
      "pdf",
      "ファイル形式",
      "提出",
      "保存"
    ],
    "displayPages": [
      "il01",
      "il11",
      "il12"
    ],
    "relatedPage": "il01.html#headline_3",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-016",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "保存・書き出し",
    "category": "トラブル",
    "priority": 1,
    "sortOrder": 160,
    "question": "PDF保存とPNG書き出しの違いは",
    "shortAnswer": "PDFは「別名で保存」、PNGは「書き出し用に追加」から行います。操作が別なので混同しないようにしてください。",
    "shortAnswerHtml": "PDFは「別名で保存」、PNGは「書き出し用に追加」から行います。操作が別なので混同しないようにしてください。",
    "bodyHtml": "PDF保存とPNG書き出しは、操作も用途も違います。<br><br><aside class=\"faq-box faq-check\"><div class=\"faq-box-title\">確認</div><div class=\"faq-box-body\"><ul><li>PDFにする → <span class=\"faq-menu-path\"><span class=\"faq-menu-item\">ファイル</span><span class=\"faq-menu-sep\">›</span><span class=\"faq-menu-item\">別名で保存</span></span> からAdobe PDFを選ぶ</li><li>PNGにする → 図形を選択して、右クリックから「書き出し用に追加」を選ぶ</li></ul></div></aside><br><br><aside class=\"faq-box faq-mistake\"><div class=\"faq-box-title\">よくあるミス</div><div class=\"faq-box-body\"><ul><li>PNGが必要なのにPDFで保存している</li><li>PDFが必要なのにPNGだけを書き出している</li><li>ファイル形式を確認せずに提出している</li></ul></div></aside><br><br>迷ったら、提出フォームで指定されているファイル形式を確認してください。",
    "keywords": [
      "pdf",
      "png",
      "保存",
      "書き出し",
      "別名で保存"
    ],
    "displayPages": [
      "il01",
      "il11",
      "il12"
    ],
    "relatedPage": "il01.html#headline_3",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-005",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "画面・ツール",
    "category": "用語",
    "priority": 2,
    "sortOrder": 50,
    "question": "選択ツールとダイレクト選択ツールの違い",
    "shortAnswer": "選択ツールは図形全体、ダイレクト選択ツールはアンカーポイントなど一部を編集するときに使います。",
    "shortAnswerHtml": "選択ツールは図形全体、ダイレクト選択ツールはアンカーポイントなど一部を編集するときに使います。",
    "bodyHtml": "<span class=\"faq-tool\"><img src=\"./img/illustrator/selection_tool.png\" alt=\"\" class=\"faq-tool-icon\"><b>選択ツール</b></span>は、図形や文字などのオブジェクト全体を選ぶときに使います。<br><br><span class=\"faq-tool\"><img src=\"./img/illustrator/direct_selection_tool.png\" alt=\"\" class=\"faq-tool-icon\"><b>ダイレクト選択ツール</b></span>は、アンカーポイントやセグメントなど、図形の一部を選んで編集するときに使います。<br><br><aside class=\"faq-box faq-check\"><div class=\"faq-box-title\">確認</div><div class=\"faq-box-body\"><ul><li>図形全体を動かしたい → 選択ツール</li><li>点や線の一部を動かしたい → ダイレクト選択ツール</li></ul></div></aside><br><br><aside class=\"faq-box faq-mistake\"><div class=\"faq-box-title\">よくあるミス</div><div class=\"faq-box-body\"><ul><li>アンカーポイントを動かしたいのに選択ツールを使っている</li><li>図形全体を動かしたいのにダイレクト選択ツールを使っている</li></ul></div></aside>",
    "keywords": [
      "選択ツール",
      "ダイレクト選択ツール",
      "白矢印",
      "黒矢印",
      "アンカーポイント"
    ],
    "displayPages": [
      "il02",
      "il03",
      "il04",
      "il11"
    ],
    "relatedPage": "il02.html#headline_4",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-006",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "線とパス",
    "category": "用語",
    "priority": 2,
    "sortOrder": 60,
    "question": "アンカーポイントとは何か",
    "shortAnswer": "図形や線の形を決める点です。",
    "shortAnswerHtml": "図形や線の形を決める点です。",
    "bodyHtml": "アンカーポイントとは、図形や線の形を決める点です。<br><br>Illustratorの図形や線は、アンカーポイントと、それらを結ぶセグメントでできています。<br><br><aside class=\"faq-box faq-check\"><div class=\"faq-box-title\">確認</div><div class=\"faq-box-body\"><ul><li>図形の角や曲線の途中にある点がアンカーポイント</li><li>アンカーポイントを動かすと図形の形が変わる</li><li>曲線ではハンドルの向きや長さでも形が変わる</li></ul></div></aside><br><br>詳しくは、<a href=\"il02.html#headline_4\" class=\"faq-page-link\" target=\"_blank\" rel=\"noopener noreferrer\">Illustratorの基本用語</a>を確認してください。",
    "keywords": [
      "アンカーポイント",
      "パス",
      "セグメント",
      "ハンドル",
      "点"
    ],
    "displayPages": [
      "il02",
      "il03"
    ],
    "relatedPage": "il02.html#headline_4",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-007",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "線とパス",
    "category": "操作方法",
    "priority": 2,
    "sortOrder": 70,
    "question": "直線を曲線にするには",
    "shortAnswer": "アンカーポイントツールでアンカーポイントからドラッグしてハンドルを出します。",
    "shortAnswerHtml": "アンカーポイントツールでアンカーポイントからドラッグしてハンドルを出します。",
    "bodyHtml": "直線を曲線にするには、アンカーポイントからハンドルを出します。<br><br><ol class=\"faq-steps\"><li><span class=\"faq-tool\"><img src=\"./img/illustrator/anchor_point_tool.png\" alt=\"\" class=\"faq-tool-icon\"><b>アンカーポイントツール</b></span>を選ぶ</li><li>曲線にしたいアンカーポイントからドラッグする</li><li>ハンドルが出たら、向きと長さを調整する</li><li>必要に応じて<span class=\"faq-tool\"><img src=\"./img/illustrator/direct_selection_tool.png\" alt=\"\" class=\"faq-tool-icon\"><b>ダイレクト選択ツール</b></span>で形を整える</li></ol><br><br><aside class=\"faq-box faq-mistake\"><div class=\"faq-box-title\">よくあるミス</div><div class=\"faq-box-body\"><ul><li>クリックだけしていてドラッグしていない</li><li>選択ツールで図形全体を動かしてしまっている</li><li>ハンドルの片側だけを動かそうとして、意図しない形になっている</li></ul></div></aside>",
    "keywords": [
      "曲線",
      "ハンドル",
      "アンカーポイントツール",
      "ダイレクト選択ツール"
    ],
    "displayPages": [
      "il03"
    ],
    "relatedPage": "il03.html#headline_2",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-008",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "文字",
    "category": "操作方法",
    "priority": 2,
    "sortOrder": 80,
    "question": "文字を入れるには",
    "shortAnswer": "文字ツールでアートボード上をクリックします。",
    "shortAnswerHtml": "文字ツールでアートボード上をクリックします。",
    "bodyHtml": "文字を入れるには、<span class=\"faq-tool\"><img src=\"./img/illustrator/type_tool.png\" alt=\"\" class=\"faq-tool-icon\"><b>文字ツール</b></span>を使います。<br><br><ol class=\"faq-steps\"><li><span class=\"faq-tool\"><img src=\"./img/illustrator/type_tool.png\" alt=\"\" class=\"faq-tool-icon\"><b>文字ツール</b></span>を選ぶ</li><li>アートボード上で文字を入れたい場所をクリックする</li><li>文字を入力する</li><li>文字全体を動かすときは<span class=\"faq-tool\"><img src=\"./img/illustrator/selection_tool.png\" alt=\"\" class=\"faq-tool-icon\"><b>選択ツール</b></span>に戻す</li></ol><br><br><aside class=\"faq-box faq-mistake\"><div class=\"faq-box-title\">よくあるミス</div><div class=\"faq-box-body\"><ul><li>文字ツールのまま図形を動かそうとしている</li><li>文字を編集したいのに選択ツールで文字全体を選んでいる</li></ul></div></aside>",
    "keywords": [
      "文字",
      "文字ツール",
      "テキスト",
      "入力"
    ],
    "displayPages": [
      "il04"
    ],
    "relatedPage": "il04.html#headline_1",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-009",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "文字",
    "category": "操作方法",
    "priority": 2,
    "sortOrder": 90,
    "question": "文字の色やふちを変えるには",
    "shortAnswer": "文字の色は塗り、ふちは線の色と線幅で設定します。",
    "shortAnswerHtml": "文字の色は塗り、ふちは線の色と線幅で設定します。",
    "bodyHtml": "文字の色は「塗り」、文字のふちは「線」で設定します。<br><br>文字のふちや線幅を変更したい場合は、プロパティパネルのアピアランスから設定します。<br><br><ol class=\"faq-steps\"><li><span class=\"faq-tool\"><img src=\"./img/illustrator/selection_tool.png\" alt=\"\" class=\"faq-tool-icon\"><b>選択ツール</b></span>で文字を選択する</li><li>プロパティパネルを開く</li><li>アピアランスの中にある「線」という文字をクリックする</li><li>線の色や線幅を変更する</li></ol><br><br><aside class=\"faq-box faq-mistake\"><div class=\"faq-box-title\">よくあるミス</div><div class=\"faq-box-body\"><ul><li>文字の色を変えたいのに線だけを変更している</li><li>ふちを太くしたいのに「塗り」を変更している</li><li>文字ツールで一部だけ選択していて、文字全体に反映されていない</li></ul></div></aside>",
    "keywords": [
      "文字",
      "書式",
      "色",
      "ふち",
      "線",
      "塗り",
      "アピアランス",
      "プロパティ"
    ],
    "displayPages": [
      "il04"
    ],
    "relatedPage": "il04.html#headline_2",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-011",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "配色",
    "category": "デザイン判断",
    "priority": 2,
    "sortOrder": 110,
    "question": "ピクトグラムの色はどう決めるか",
    "shortAnswer": "背景とのコントラスト、色の意味、一貫性を意識して決めます。",
    "shortAnswerHtml": "背景とのコントラスト、色の意味、一貫性を意識して決めます。",
    "bodyHtml": "ピクトグラムの色は、見た目の好みだけでなく、意味と見やすさで決めます。<br><br><aside class=\"faq-box faq-check\"><div class=\"faq-box-title\">確認</div><div class=\"faq-box-body\"><ul><li>背景と図形のコントラストが十分にある</li><li>色の意味がテーマに合っている</li><li>同じ意味のものに一貫した色を使っている</li><li>色数が多すぎない</li></ul></div></aside><br><br><aside class=\"faq-box faq-point\"><div class=\"faq-box-title\">ポイント</div><div class=\"faq-box-body\">迷った場合は、背景色と図形色の2色を基本にすると、見やすいピクトグラムになりやすいです。</div></aside><br><br>詳しくは、<a href=\"il12.html#headline_1\" class=\"faq-page-link\" target=\"_blank\" rel=\"noopener noreferrer\">ピクトグラムの配色</a>を確認してください。",
    "keywords": [
      "配色",
      "色",
      "コントラスト",
      "視認性",
      "背景",
      "ピクトグラム"
    ],
    "displayPages": [
      "il12"
    ],
    "relatedPage": "il12.html#headline_1",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-017",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "保存・書き出し",
    "category": "トラブル",
    "priority": 2,
    "sortOrder": 170,
    "question": "図形を選択しているのに書き出せない",
    "shortAnswer": "グループや編集モード、選択対象が原因の可能性があります。いったん編集モードを解除し、選択ツールで図形全体を選び直してください。",
    "shortAnswerHtml": "グループや編集モード、選択対象が原因の可能性があります。いったん編集モードを解除し、選択ツールで図形全体を選び直してください。",
    "bodyHtml": "図形を選択しているつもりでも、編集モードや一部選択の状態では正しく書き出せないことがあります。<br><br><ol class=\"faq-steps\"><li>何もないところをダブルクリックして編集モードを解除する</li><li><span class=\"faq-tool\"><img src=\"./img/illustrator/selection_tool.png\" alt=\"\" class=\"faq-tool-icon\"><b>選択ツール</b></span>に切り替える</li><li>書き出したい図形全体をドラッグして選択する</li><li>右クリックして「書き出し用に追加」を選ぶ</li></ol><br><br><aside class=\"faq-box faq-check\"><div class=\"faq-box-title\">確認</div><div class=\"faq-box-body\"><ul><li>一部のアンカーポイントだけでなく、図形全体が選ばれているか</li><li>編集モードに入っていないか</li><li>複数の図形をまとめて書き出したい場合、すべて選択されているか</li></ul></div></aside>",
    "keywords": [
      "選択",
      "書き出せない",
      "編集モード",
      "グループ",
      "アセット"
    ],
    "displayPages": [
      "il01",
      "il11",
      "il12"
    ],
    "relatedPage": "il01.html#headline_4",
    "relatedSlide": "",
    "relatedFaq": [
      "il-013"
    ],
    "updatedAt": ""
  },
  {
    "faqId": "il-018",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "画面・ツール",
    "category": "トラブル",
    "priority": 2,
    "sortOrder": 180,
    "question": "プロパティパネルが見つからない",
    "shortAnswer": "右側のパネルに表示されていない場合は、メニューのウィンドウからプロパティを表示してください。",
    "shortAnswerHtml": "右側のパネルに表示されていない場合は、メニューのウィンドウからプロパティを表示してください。",
    "bodyHtml": "プロパティパネルが見つからない場合は、非表示になっている可能性があります。<br><br><ol class=\"faq-steps\"><li><span class=\"faq-menu-path\"><span class=\"faq-menu-item\">ウィンドウ</span><span class=\"faq-menu-sep\">›</span><span class=\"faq-menu-item\">プロパティ</span></span> を選ぶ</li><li>右側にプロパティパネルが表示されたか確認する</li><li>表示されたら、選択中の図形や文字に応じた設定項目を確認する</li></ol><br><br><aside class=\"faq-box faq-point\"><div class=\"faq-box-title\">ポイント</div><div class=\"faq-box-body\"><ul><li>何も選択していないと、必要な設定項目が表示されないことがあります。</li><li>先に図形や文字を選択してから、プロパティパネルを確認してください。</li></ul></div></aside>",
    "keywords": [
      "プロパティ",
      "パネル",
      "表示",
      "ウィンドウ"
    ],
    "displayPages": [
      "il02",
      "il03",
      "il04",
      "il11"
    ],
    "relatedPage": "il02.html#headline_1",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-019",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "線とパス",
    "category": "操作方法",
    "priority": 2,
    "sortOrder": 190,
    "question": "線の太さや色を変えるには",
    "shortAnswer": "選択ツールで線を選び、プロパティパネルで線の太さや色を変更します。",
    "shortAnswerHtml": "選択ツールで線を選び、プロパティパネルで線の太さや色を変更します。",
    "bodyHtml": "線の太さや色を変えるには、まず線を選択します。<br><br><ol class=\"faq-steps\"><li><span class=\"faq-tool\"><img src=\"./img/illustrator/selection_tool.png\" alt=\"\" class=\"faq-tool-icon\"><b>選択ツール</b></span>で線を選択する</li><li>プロパティパネルを確認する</li><li>線の色を変更する</li><li>線の太さを変更する</li></ol><br><br><aside class=\"faq-box faq-mistake\"><div class=\"faq-box-title\">よくあるミス</div><div class=\"faq-box-body\"><ul><li>線ではなく塗りを変更している</li><li>線を選択していない状態で設定を探している</li><li>ダイレクト選択ツールで一部だけを選んでいる</li></ul></div></aside>",
    "keywords": [
      "線",
      "太さ",
      "色",
      "プロパティ",
      "パス"
    ],
    "displayPages": [
      "il03"
    ],
    "relatedPage": "il03.html#headline_1",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-020",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "線とパス",
    "category": "操作方法",
    "priority": 2,
    "sortOrder": 200,
    "question": "アンカーポイントを追加するには",
    "shortAnswer": "アンカーポイントの追加ツールで線上をクリックします。その後、ダイレクト選択ツールで動かせます。",
    "shortAnswerHtml": "アンカーポイントの追加ツールで線上をクリックします。その後、ダイレクト選択ツールで動かせます。",
    "bodyHtml": "アンカーポイントを追加すると、線を折り曲げたり、形を細かく調整したりできます。<br><br><ol class=\"faq-steps\"><li><span class=\"faq-tool\"><img src=\"./img/illustrator/add_anchor_point_tool.png\" alt=\"\" class=\"faq-tool-icon\"><b>アンカーポイントの追加ツール</b></span>を選ぶ</li><li>線上の追加したい場所をクリックする</li><li><span class=\"faq-tool\"><img src=\"./img/illustrator/direct_selection_tool.png\" alt=\"\" class=\"faq-tool-icon\"><b>ダイレクト選択ツール</b></span>で追加した点を動かす</li></ol><br><br><aside class=\"faq-box faq-mistake\"><div class=\"faq-box-title\">よくあるミス</div><div class=\"faq-box-body\"><ul><li>線上ではない場所をクリックしている</li><li>選択ツールで図形全体を動かしてしまっている</li><li>追加した点ではなく別の点を動かしている</li></ul></div></aside>",
    "keywords": [
      "アンカーポイント",
      "追加",
      "折れ線",
      "ダイレクト選択ツール"
    ],
    "displayPages": [
      "il03"
    ],
    "relatedPage": "il03.html#headline_2",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-021",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "線とパス",
    "category": "トラブル",
    "priority": 2,
    "sortOrder": 210,
    "question": "ハンドルがうまく動かせない",
    "shortAnswer": "ダイレクト選択ツールでアンカーポイントやハンドルを選び、必要に応じてアンカーポイントツールでコーナーポイントに切り替えます。",
    "shortAnswerHtml": "ダイレクト選択ツールでアンカーポイントやハンドルを選び、必要に応じてアンカーポイントツールでコーナーポイントに切り替えます。",
    "bodyHtml": "曲線のハンドルを動かすときは、使っているツールを確認してください。<br><br><aside class=\"faq-box faq-check\"><div class=\"faq-box-title\">確認</div><div class=\"faq-box-body\"><ul><li>曲線全体を調整する → <span class=\"faq-tool\"><img src=\"./img/illustrator/direct_selection_tool.png\" alt=\"\" class=\"faq-tool-icon\"><b>ダイレクト選択ツール</b></span></li><li>スムーズポイントとコーナーポイントを切り替える → <span class=\"faq-tool\"><img src=\"./img/illustrator/anchor_point_tool.png\" alt=\"\" class=\"faq-tool-icon\"><b>アンカーポイントツール</b></span></li></ul></div></aside><br><br><aside class=\"faq-box faq-mistake\"><div class=\"faq-box-title\">よくあるミス</div><div class=\"faq-box-body\"><ul><li>選択ツールで図形全体を動かしている</li><li>ハンドルではなくアンカーポイント本体を動かしている</li><li>左右のハンドルを別々に動かしたいのにスムーズポイントのまま操作している</li></ul></div></aside>",
    "keywords": [
      "ハンドル",
      "曲線",
      "スムーズポイント",
      "コーナーポイント",
      "アンカーポイント"
    ],
    "displayPages": [
      "il03"
    ],
    "relatedPage": "il03.html#headline_2",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-022",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "文字",
    "category": "トラブル",
    "priority": 2,
    "sortOrder": 220,
    "question": "文字を編集できない",
    "shortAnswer": "文字そのものを直すときは文字ツール、文字全体を移動・拡大するときは選択ツールを使います。",
    "shortAnswerHtml": "文字そのものを直すときは文字ツール、文字全体を移動・拡大するときは選択ツールを使います。",
    "bodyHtml": "文字が編集できない場合は、使っているツールが目的に合っているか確認します。<br><br><aside class=\"faq-box faq-check\"><div class=\"faq-box-title\">確認</div><div class=\"faq-box-body\"><ul><li>文字の内容を直したい → <span class=\"faq-tool\"><img src=\"./img/illustrator/type_tool.png\" alt=\"\" class=\"faq-tool-icon\"><b>文字ツール</b></span>で文字をクリック</li><li>文字全体を動かしたい → <span class=\"faq-tool\"><img src=\"./img/illustrator/selection_tool.png\" alt=\"\" class=\"faq-tool-icon\"><b>選択ツール</b></span>で文字オブジェクトを選択</li><li>一部の文字だけ書式を変えたい → <span class=\"faq-tool\"><img src=\"./img/illustrator/type_tool.png\" alt=\"\" class=\"faq-tool-icon\"><b>文字ツール</b></span>でその部分を選択</li></ul></div></aside><br><br><aside class=\"faq-box faq-mistake\"><div class=\"faq-box-title\">よくあるミス</div><div class=\"faq-box-body\"><ul><li>選択ツールで文字の中身を直そうとしている</li><li>文字ツールのまま文字全体を移動しようとしている</li><li>文字を選択せずにプロパティを探している</li></ul></div></aside>",
    "keywords": [
      "文字",
      "編集",
      "文字ツール",
      "選択ツール",
      "テキスト"
    ],
    "displayPages": [
      "il04"
    ],
    "relatedPage": "il04.html#headline_1",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-023",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "ピクトグラム",
    "category": "デザイン判断",
    "priority": 2,
    "sortOrder": 230,
    "question": "テーマが決まらない",
    "shortAnswer": "学校生活・安全・交通・環境・デジタル生活など、身近な場面の「伝えたいこと」から考えると決めやすいです。",
    "shortAnswerHtml": "学校生活・安全・交通・環境・デジタル生活など、身近な場面の「伝えたいこと」から考えると決めやすいです。",
    "bodyHtml": "テーマが決まらない場合は、「何を描きたいか」ではなく、「何を伝えたいか」から考えます。<br><br><aside class=\"faq-box faq-check\"><div class=\"faq-box-title\">確認</div><div class=\"faq-box-body\"><ul><li>学校生活のルール</li><li>安全に関する注意</li><li>交通や移動に関する案内</li><li>環境や節電に関する呼びかけ</li><li>デジタル生活での注意</li></ul></div></aside><br><br><aside class=\"faq-box faq-point\"><div class=\"faq-box-title\">ポイント</div><div class=\"faq-box-body\"><ul><li>よいピクトグラムは、絵が上手いことよりも、意味がすぐ伝わることが大切です。</li><li>まずは「禁止」「注意」「案内」「安全」など、目的を決めると作りやすくなります。</li></ul></div></aside>",
    "keywords": [
      "テーマ",
      "ピクトグラム",
      "アイデア",
      "学校生活",
      "安全",
      "注意",
      "案内"
    ],
    "displayPages": [
      "il11"
    ],
    "relatedPage": "il11.html#headline_2",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-024",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "ピクトグラム",
    "category": "デザイン判断",
    "priority": 2,
    "sortOrder": 240,
    "question": "細かい絵を描いてもよいか",
    "shortAnswer": "細かすぎる絵は、ピクトグラムとしては伝わりにくくなります。遠くから見ても意味が伝わる程度に単純化してください。",
    "shortAnswerHtml": "細かすぎる絵は、ピクトグラムとしては伝わりにくくなります。遠くから見ても意味が伝わる程度に単純化してください。",
    "bodyHtml": "ピクトグラムでは、細かい描き込みよりも、意味がすぐ伝わることを優先します。<br><br><aside class=\"faq-box faq-check\"><div class=\"faq-box-title\">確認</div><div class=\"faq-box-body\"><ul><li>小さく表示しても意味がわかる</li><li>遠くから見ても形が判別できる</li><li>説明しなくても何を表しているかわかる</li><li>不要な装飾を減らしている</li></ul></div></aside><br><br><aside class=\"faq-box faq-point\"><div class=\"faq-box-title\">ポイント</div><div class=\"faq-box-body\">迷った場合は、一度小さく表示してみて、何を表しているか判断できるか確認してください。</div></aside>",
    "keywords": [
      "細かい",
      "装飾",
      "単純化",
      "シンプル",
      "視認性",
      "ピクトグラム"
    ],
    "displayPages": [
      "il11",
      "il12"
    ],
    "relatedPage": "il11.html#headline_2",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-025",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "配色",
    "category": "デザイン判断",
    "priority": 2,
    "sortOrder": 250,
    "question": "色をたくさん使ってもよいか",
    "shortAnswer": "意味が伝わりにくくなる場合は、色数を減らしてください。基本は背景色と図形色の2色で考えると見やすくなります。",
    "shortAnswerHtml": "意味が伝わりにくくなる場合は、色数を減らしてください。基本は背景色と図形色の2色で考えると見やすくなります。",
    "bodyHtml": "色をたくさん使うと、見た目はにぎやかになりますが、ピクトグラムとしては意味が伝わりにくくなることがあります。<br><br><aside class=\"faq-box faq-check\"><div class=\"faq-box-title\">確認</div><div class=\"faq-box-body\"><ul><li>背景と図形がはっきり区別できる</li><li>色の意味がテーマに合っている</li><li>同じ意味には同じ色を使っている</li><li>色が多すぎて主役がわかりにくくなっていない</li></ul></div></aside><br><br><aside class=\"faq-box faq-point\"><div class=\"faq-box-title\">ポイント</div><div class=\"faq-box-body\">まずは2色で作り、必要な場合だけ色を追加するのがおすすめです。</div></aside>",
    "keywords": [
      "色",
      "色数",
      "2色",
      "配色",
      "コントラスト",
      "ピクトグラム"
    ],
    "displayPages": [
      "il12"
    ],
    "relatedPage": "il12.html#headline_1",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  }
];

  global.FAQ_CATEGORY_DATA = FAQ_CATEGORY_DATA;
  global.FAQ_DATA = FAQ_DATA;

})(typeof window !== 'undefined' ? window : this);
