/* eslint-disable */
/**
 * Auto-generated FAQ data.
 * Generated at: 2026-05-08 09:39:21 JST
 * Do not edit this file directly.
 *
 * course:
 *  - il
 *  - html
 *  - ss
 *  - py
 *
 * displayPages:
 *  - pageKey array without ".html"
 *  - [] means "show on all pages matching course"
 */

(function(global) {
  'use strict';

  const FAQ_CATEGORY_DATA = [
  {
    "type": "category",
    "key": "operation",
    "label": "操作方法",
    "parent": "10",
    "sortOrder": 1,
    "enabled": true
  },
  {
    "type": "category",
    "key": "trouble",
    "label": "トラブル",
    "parent": "20",
    "sortOrder": 1,
    "enabled": true
  },
  {
    "type": "category",
    "key": "submit",
    "label": "保存・提出",
    "parent": "30",
    "sortOrder": 1,
    "enabled": true
  },
  {
    "type": "category",
    "key": "term",
    "label": "用語",
    "parent": "40",
    "sortOrder": 1,
    "enabled": true
  },
  {
    "type": "category",
    "key": "concept",
    "label": "考え方",
    "parent": "50",
    "sortOrder": 1,
    "enabled": true
  },
  {
    "type": "category",
    "key": "error",
    "label": "エラー",
    "parent": "60",
    "sortOrder": 1,
    "enabled": true
  },
  {
    "type": "category",
    "key": "design",
    "label": "デザイン判断",
    "parent": "70",
    "sortOrder": 1,
    "enabled": true
  },
  {
    "type": "category",
    "key": "assessment",
    "label": "採点・評価",
    "parent": "80",
    "sortOrder": 1,
    "enabled": true
  },
  {
    "type": "category",
    "key": "advanced",
    "label": "発展",
    "parent": "90",
    "sortOrder": 1,
    "enabled": true
  },
  {
    "type": "course",
    "key": "il",
    "label": "Illustrator実習",
    "parent": "10",
    "sortOrder": 1,
    "enabled": true
  },
  {
    "type": "course",
    "key": "html",
    "label": "HTML実習",
    "parent": "20",
    "sortOrder": 1,
    "enabled": true
  },
  {
    "type": "course",
    "key": "ss",
    "label": "スプレッドシート実習",
    "parent": "30",
    "sortOrder": 1,
    "enabled": true
  },
  {
    "type": "course",
    "key": "py",
    "label": "Python講座",
    "parent": "40",
    "sortOrder": 1,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "html_basic",
    "label": "HTMLの基本",
    "parent": "html",
    "sortOrder": 10,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "html_tag",
    "label": "タグ",
    "parent": "html",
    "sortOrder": 20,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "html_link",
    "label": "リンク",
    "parent": "html",
    "sortOrder": 30,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "html_image",
    "label": "画像",
    "parent": "html",
    "sortOrder": 40,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "html_css",
    "label": "CSSの基本",
    "parent": "html",
    "sortOrder": 50,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "html_layout",
    "label": "レイアウト",
    "parent": "html",
    "sortOrder": 60,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "html_submit",
    "label": "提出・確認",
    "parent": "html",
    "sortOrder": 70,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "il_basic",
    "label": "基本操作",
    "parent": "il",
    "sortOrder": 10,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "il_save",
    "label": "保存・書き出し",
    "parent": "il",
    "sortOrder": 20,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "il_ui",
    "label": "画面・ツール",
    "parent": "il",
    "sortOrder": 30,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "il_path",
    "label": "線とパス",
    "parent": "il",
    "sortOrder": 40,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "il_text",
    "label": "文字",
    "parent": "il",
    "sortOrder": 50,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "il_pictogram",
    "label": "ピクトグラム",
    "parent": "il",
    "sortOrder": 60,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "il_color",
    "label": "配色",
    "parent": "il",
    "sortOrder": 70,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "il_submit",
    "label": "提出・相互評価",
    "parent": "il",
    "sortOrder": 80,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "py_colab",
    "label": "Colabの基本",
    "parent": "py",
    "sortOrder": 10,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "py_variable",
    "label": "printと変数",
    "parent": "py",
    "sortOrder": 20,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "py_input",
    "label": "入力",
    "parent": "py",
    "sortOrder": 30,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "py_if",
    "label": "条件分岐",
    "parent": "py",
    "sortOrder": 40,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "py_loop",
    "label": "繰り返し",
    "parent": "py",
    "sortOrder": 50,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "py_list",
    "label": "リスト",
    "parent": "py",
    "sortOrder": 60,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "py_function",
    "label": "関数",
    "parent": "py",
    "sortOrder": 70,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "py_graph",
    "label": "グラフ",
    "parent": "py",
    "sortOrder": 80,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "py_error",
    "label": "エラー対応",
    "parent": "py",
    "sortOrder": 90,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "ss_basic",
    "label": "基本操作",
    "parent": "ss",
    "sortOrder": 10,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "ss_ref",
    "label": "セル参照",
    "parent": "ss",
    "sortOrder": 20,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "ss_formula",
    "label": "数式",
    "parent": "ss",
    "sortOrder": 30,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "ss_function",
    "label": "関数",
    "parent": "ss",
    "sortOrder": 40,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "ss_autofill",
    "label": "オートフィル",
    "parent": "ss",
    "sortOrder": 50,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "ss_graph",
    "label": "グラフ",
    "parent": "ss",
    "sortOrder": 60,
    "enabled": true
  },
  {
    "type": "unit",
    "key": "ss_analysis",
    "label": "データ分析",
    "parent": "ss",
    "sortOrder": 70,
    "enabled": true
  }
];

  const FAQ_DATA = [
  {
    "faqId": "il-001",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "保存・書き出し",
    "category": "保存・提出",
    "priority": 1,
    "sortOrder": 10,
    "question": "PNGファイルはどうやって書き出しますか？",
    "shortAnswer": "選択ツールで対象を選び、書き出し用に追加します。高さ400px、PNG形式で書き出してください。",
    "shortAnswerHtml": "選択ツールで対象を選び、書き出し用に追加します。高さ400px、PNG形式で書き出してください。",
    "bodyHtml": "まず、書き出したい図形を<span class=\"faq-tool\"><img src=\"./img/illustrator/selection_tool.png\" alt=\"\" class=\"faq-tool-icon\"><b>選択ツール</b></span>で選択します。<br><br><ol class=\"faq-steps\"><li>図形全体を選択する</li><li>右クリックする</li><li>書き出し用に追加を選ぶ</li><li>単一のアセットとしてを選ぶ</li><li>高さを <code>400 px</code> にする</li><li>保存形式を <code>PNG</code> にする</li><li>書き出しをクリックする</li></ol><br><br><aside class=\"faq-box faq-check\"><div class=\"faq-box-title\">確認</div><div class=\"faq-box-body\"><ul><li>保存先フォルダの中に <code>400h</code> フォルダができているか確認する</li><li>PNGファイルがその中に入っているか確認する</li><li>提出フォームで指定されたファイル形式になっているか確認する</li></ul></div></aside><br><br><aside class=\"faq-box faq-mistake\"><div class=\"faq-box-title\">よくあるミス</div><div class=\"faq-box-body\"><ul><li>図形を選択しないまま書き出そうとしている</li><li>PDFで保存する操作とPNGで書き出す操作を混同している</li><li>400hフォルダではなく親フォルダを見ている</li></ul></div></aside><br><br>詳しい手順は、<a href=\"il01.html#headline<sub>4\" class=\"faq-page-link\" target=\"</sub>blank\" rel=\"noopener noreferrer\">画像ファイルの書き出し方法</a>を確認してください。",
    "keywords": [],
    "displayPages": [],
    "relatedPage": "il01.html#headline_4",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-002",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "保存・書き出し",
    "category": "トラブル",
    "priority": 1,
    "sortOrder": 20,
    "question": "書き出したPNGファイルが見つかりません。",
    "shortAnswer": "保存先フォルダの中にできた400hフォルダを確認してください。",
    "shortAnswerHtml": "保存先フォルダの中にできた400hフォルダを確認してください。",
    "bodyHtml": "保存先フォルダの中にできた400hフォルダを確認してください。",
    "keywords": [],
    "displayPages": [],
    "relatedPage": "il01.html#headline_4",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-003",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "画面・ツール",
    "category": "トラブル",
    "priority": 1,
    "sortOrder": 30,
    "question": "ツールバーが消えました。",
    "shortAnswer": "ウィンドウ ＞ ツールバー ＞ 基本 を選ぶと再表示できます。",
    "shortAnswerHtml": "ウィンドウ ＞ ツールバー ＞ 基本 を選ぶと再表示できます。",
    "bodyHtml": "ツールバーを誤って非表示にしてしまった場合は、メニューから再表示できます。<br><br><ol class=\"faq-steps\"><li><span class=\"faq-menu-path\"><span class=\"faq-menu-item\">ウィンドウ</span><span class=\"faq-menu-sep\">›</span><span class=\"faq-menu-item\">ツールバー</span><span class=\"faq-menu-sep\">›</span><span class=\"faq-menu-item\">基本</li</span><span class=\"faq-menu-sep\">›</span><span class=\"faq-menu-item\"></ol</span><span class=\"faq-menu-sep\">›</span><span class=\"faq-menu-item\">を選ぶ<br>左側にツールバーが表示されたことを確認する</span></span><br><br><aside class=\"faq-box faq-check\"><div class=\"faq-box-title\">確認</div><div class=\"faq-box-body\"><ul><li>画面左側にツールバーが表示されているか</li><li>選択ツールや文字ツールが見えるか</li></ul></div></aside><br><br>それでも戻らない場合は、画面の状態を先生に見せてください。",
    "keywords": [],
    "displayPages": [],
    "relatedPage": "il02.html#headline_1",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-004",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "基本操作",
    "category": "トラブル",
    "priority": 1,
    "sortOrder": 40,
    "question": "操作を間違えました。戻せますか？",
    "shortAnswer": "⌘+Zで直前の操作を取り消せます。",
    "shortAnswerHtml": "⌘+Zで直前の操作を取り消せます。",
    "bodyHtml": "直前の操作は、<kbd class=\"faq-kbd\">⌘+Z</kbd> で取り消すことができます。<br><br><aside class=\"faq-box faq-point\"><div class=\"faq-box-title\">ポイント</div><div class=\"faq-box-body\"><ul><li>Illustratorでは、かなり前の操作まで戻せる場合があります。</li><li>ただし、保存やファイル操作のすべてが元に戻るわけではありません。</li></ul></div></aside><br><br><aside class=\"faq-box faq-mistake\"><div class=\"faq-box-title\">よくあるミス</div><div class=\"faq-box-body\"><ul><li>間違えたあとに何度も別の操作をしてしまう</li><li>元ファイルを上書き保存してしまう</li></ul></div></aside><br><br>大きく変更する前には、別名で保存しておくと安全です。",
    "keywords": [],
    "displayPages": [],
    "relatedPage": "il02.html#headline_1",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-010",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "ピクトグラム",
    "category": "考え方",
    "priority": 1,
    "sortOrder": 100,
    "question": "よいピクトグラムかどうか判断できません。",
    "shortAnswer": "シンプルさ、視認性、意味の伝わりやすさ、配色を確認してください。",
    "shortAnswerHtml": "シンプルさ、視認性、意味の伝わりやすさ、配色を確認してください。",
    "bodyHtml": "よいピクトグラムかどうかは、見た目の好みだけではなく、情報が伝わるかどうかで判断します。<br><br><aside class=\"faq-box faq-check\"><div class=\"faq-box-title\">確認</div><div class=\"faq-box-body\"><ul><li>何を表しているか一目でわかる</li><li>形がシンプルである</li><li>細かすぎる装飾がない</li><li>背景と図形のコントラストがある</li><li>テーマに合っている</li></ul></div></aside><br><br><aside class=\"faq-box faq-point\"><div class=\"faq-box-title\">ポイント</div><div class=\"faq-box-body\"><ul><li>友人に一瞬だけ見せて、何を表しているか答えてもらうと確認しやすいです。</li><li>説明しないと伝わらない場合は、形をもう少し単純化してください。</li></ul></div></aside>",
    "keywords": [],
    "displayPages": [],
    "relatedPage": "il11.html#headline_2",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-012",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "提出・相互評価",
    "category": "保存・提出",
    "priority": 1,
    "sortOrder": 120,
    "question": "提出前に何を確認すればよいですか？",
    "shortAnswer": "ファイル形式、ファイル名、PNG/AIファイル、見やすさを確認してください。",
    "shortAnswerHtml": "ファイル形式、ファイル名、PNG/AIファイル、見やすさを確認してください。",
    "bodyHtml": "ファイル形式、ファイル名、PNG/AIファイル、見やすさを確認してください。",
    "keywords": [],
    "displayPages": [],
    "relatedPage": "il11.html",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-005",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "画面・ツール",
    "category": "用語",
    "priority": 2,
    "sortOrder": 50,
    "question": "選択ツールとダイレクト選択ツールの違いは何ですか？",
    "shortAnswer": "選択ツールは図形全体、ダイレクト選択ツールはアンカーポイントなど一部を編集するときに使います。",
    "shortAnswerHtml": "選択ツールは図形全体、ダイレクト選択ツールはアンカーポイントなど一部を編集するときに使います。",
    "bodyHtml": "<span class=\"faq-tool\"><img src=\"./img/illustrator/selection_tool.png\" alt=\"\" class=\"faq-tool-icon\"><b>選択ツール</b></span>は、図形や文字などのオブジェクト全体を選ぶときに使います。<br><br><span class=\"faq-tool\"><img src=\"./img/illustrator/direct<sub>selection</sub>tool.png\" alt=\"\" class=\"faq-tool-icon\"><b>ダイレクト選択ツール</b></span>は、アンカーポイントやセグメントなど、図形の一部を選んで編集するときに使います。<br><br><aside class=\"faq-box faq-check\"><div class=\"faq-box-title\">確認</div><div class=\"faq-box-body\"><ul><li>図形全体を動かしたい → 選択ツール</li><li>点や線の一部を動かしたい → ダイレクト選択ツール</li></ul></div></aside><br><br><aside class=\"faq-box faq-mistake\"><div class=\"faq-box-title\">よくあるミス</div><div class=\"faq-box-body\"><ul><li>アンカーポイントを動かしたいのに選択ツールを使っている</li><li>図形全体を動かしたいのにダイレクト選択ツールを使っている</li></ul></div></aside>",
    "keywords": [],
    "displayPages": [],
    "relatedPage": "il02.html#headline_4",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-006",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "線とパス",
    "category": "用語",
    "priority": 2,
    "sortOrder": 60,
    "question": "アンカーポイントとは何ですか？",
    "shortAnswer": "図形や線の形を決める点です。",
    "shortAnswerHtml": "図形や線の形を決める点です。",
    "bodyHtml": "図形や線の形を決める点です。",
    "keywords": [],
    "displayPages": [],
    "relatedPage": "il03.html#headline_2",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-007",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "線とパス",
    "category": "操作方法",
    "priority": 2,
    "sortOrder": 70,
    "question": "直線を曲線にするにはどうしますか？",
    "shortAnswer": "アンカーポイントツールでアンカーポイントからドラッグしてハンドルを出します。",
    "shortAnswerHtml": "アンカーポイントツールでアンカーポイントからドラッグしてハンドルを出します。",
    "bodyHtml": "アンカーポイントツールでアンカーポイントからドラッグしてハンドルを出します。",
    "keywords": [],
    "displayPages": [],
    "relatedPage": "il03.html#headline_2",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-008",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "文字",
    "category": "操作方法",
    "priority": 2,
    "sortOrder": 80,
    "question": "文字を入れるにはどうしますか？",
    "shortAnswer": "文字ツールでアートボード上をクリックします。",
    "shortAnswerHtml": "文字ツールでアートボード上をクリックします。",
    "bodyHtml": "文字ツールでアートボード上をクリックします。",
    "keywords": [],
    "displayPages": [],
    "relatedPage": "il04.html#headline_1",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-009",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "文字",
    "category": "操作方法",
    "priority": 2,
    "sortOrder": 90,
    "question": "文字の色やふちを変えるにはどうしますか？",
    "shortAnswer": "文字の色は塗り、ふちは線の色と線幅で設定します。",
    "shortAnswerHtml": "文字の色は塗り、ふちは線の色と線幅で設定します。",
    "bodyHtml": "文字の色は塗り、ふちは線の色と線幅で設定します。",
    "keywords": [],
    "displayPages": [],
    "relatedPage": "il04.html#headline_2",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  },
  {
    "faqId": "il-011",
    "status": "公開",
    "course": "il",
    "courseLabel": "Illustrator実習",
    "unit": "配色",
    "category": "デザイン判断",
    "priority": 2,
    "sortOrder": 110,
    "question": "ピクトグラムの色はどう決めればよいですか？",
    "shortAnswer": "背景とのコントラスト、色の意味、一貫性を意識して決めます。",
    "shortAnswerHtml": "背景とのコントラスト、色の意味、一貫性を意識して決めます。",
    "bodyHtml": "背景とのコントラスト、色の意味、一貫性を意識して決めます。",
    "keywords": [],
    "displayPages": [],
    "relatedPage": "il12.html#headline_1",
    "relatedSlide": "",
    "relatedFaq": [],
    "updatedAt": ""
  }
];

  global.FAQ_CATEGORY_DATA = FAQ_CATEGORY_DATA;
  global.FAQ_DATA = FAQ_DATA;

})(typeof window !== 'undefined' ? window : this);
