/* Local icon/component/image assets. No network access. */
(function(root,factory){var api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;root.IlapoAssets=api;}(typeof globalThis!=='undefined'?globalThis:this,function(root){'use strict';
  var KEY='kaijo-ilapo:components', MAX_COMPONENTS=100, MAX_OBJECTS=200, MAX_BYTES=3*1024*1024;
  var style={fill:'#FFFFFF',stroke:'#111827',strokeWidth:2,opacity:1,dash:'',linecap:'round',linejoin:'round',fontSize:16,fontFamily:'sans-serif',bold:false,italic:false};
  var defs=[['person','人','基本','M50 8 A14 14 0 1 0 50 36 A14 14 0 1 0 50 8 Z M25 92 C26 60 36 45 50 45 C64 45 74 60 75 92 Z'],['key','鍵','基本','M12 52 A25 25 0 1 0 54 34 L88 34 L88 48 L78 48 L78 60 L65 60 L65 47 L54 47 A25 25 0 0 0 12 52 Z'],['pc','PC','機器','M12 18 H88 V68 H12 Z M38 82 H62 M50 68 V82'],['server','サーバー','機器','M14 16 H86 V42 H14 Z M14 56 H86 V82 H14 Z M25 29 H27 M25 69 H27'],['cloud','クラウド','基本','M18 70 C2 70 5 42 25 43 C31 20 60 18 70 38 C94 35 101 70 78 70 Z'],['folder','フォルダ','基本','M8 28 H42 L50 38 H92 V82 H8 Z'],['document','書類','基本','M25 8 H65 L82 25 V92 H25 Z M65 8 V25 H82 M36 45 H70 M36 60 H70 M36 75 H60'],['phone','スマホ','機器','M28 8 H72 V92 H28 Z M46 80 H54'],['check','チェック','記号','M12 52 L39 78 L88 20'],['warning','注意','記号','M50 8 L94 88 H6 Z M50 37 V61 M50 74 V76']];
  function clone(x){return JSON.parse(JSON.stringify(x));} function core(){if(!root.IlapoCore||!root.IlapoCore.validateObject||!root.IlapoCore.uid)throw new Error('部品: IlapoCore が必要です。');return root.IlapoCore;} function uid(){return core().uid('object');}
  function check(o){return core().validateObject(o);}
  function icons(){return defs.map(function(d){return{id:d[0],name:d[1],category:d[2]};});}
  function instantiateIcon(id,opt){opt=opt||{};var d=defs.find(function(x){return x[0]===id;});if(!d)throw new RangeError('部品: アイコンが見つかりません。');var size=Number(opt.size);if(!Number.isFinite(size)||size<=0)size=48;var x=Number(opt.x)||0,y=Number(opt.y)||0;var o={id:uid(),type:'path',name:d[1],group:null,locked:false,matrix:[size/100,0,0,size/100,x,y],style:clone(style),d:d[3]};return [check(o)];}
  function validComponent(c, seen){
    if(!c||typeof c.id!=='string'||!c.id||typeof c.name!=='string'||!c.name.trim()||c.name.length>120||!Array.isArray(c.objects)||!c.objects.length||c.objects.length>MAX_OBJECTS||seen&&seen.has(c.id))throw new Error('部品: 不正なライブラリデータです。');
    if(seen)seen.add(c.id);
    var page=core().createPage('部品');page.objects=c.objects;
    var os=core().validateDocument({format:'kaijo-ilapo',version:2,id:'components',name:'部品',pages:[page]}).pages[0].objects;
    var ids=new Set(os.map(function(o){return o.id;}));
    if(os.some(function(o){return o.type==='image'&&o.reference;}))throw new Error('部品: 参照画像は部品に登録できません。');
    os.forEach(function(o){if(o.type==='connector')for(var e of [o.from,o.to])if(e.objectId&&!ids.has(e.objectId)){e.objectId=null;delete e.normal;}});
    return {id:c.id,name:c.name,objects:os};
  }
  function bounds(objects){var G=root.IlapoGeometry;if(!G||!G.bounds)throw new Error('部品: Geometry が必要です。');var bs=objects.map(G.bounds);if(!bs.length)throw new Error('部品: 保存できる図形がありません。');var x=Math.min.apply(null,bs.map(function(b){return b.x;})),y=Math.min.apply(null,bs.map(function(b){return b.y;})),r=Math.max.apply(null,bs.map(function(b){return b.x+b.width;})),bt=Math.max.apply(null,bs.map(function(b){return b.y+b.height;}));return{x:x,y:y,width:r-x,height:bt-y};}
  function translate(o,dx,dy){var n=clone(o);if(n.type==='connector'){if(!root.IlapoConnectors||!root.IlapoConnectors.transform)throw new Error('部品: IlapoConnectors が必要です。');return root.IlapoConnectors.transform(n,[1,0,0,1,dx,dy]);} n.matrix=(n.matrix||[1,0,0,1,0,0]).slice();n.matrix[4]+=dx;n.matrix[5]+=dy;return n;}
  function createLibrary(storage){core();storage=storage||(typeof localStorage!=='undefined'?localStorage:null);if(!storage||!storage.getItem||!storage.setItem)throw new TypeError('部品: Storage が必要です。');function read(){var raw=storage.getItem(KEY);if(!raw)return[];if(raw.length>MAX_BYTES)throw new Error('部品: 保存容量の上限を超えました。');var v;try{v=JSON.parse(raw);}catch(_){throw new Error('部品: 保存済みライブラリが壊れています。');}if(!v||v.format!=='kaijo-ilapo-components'||v.version!==1||!Array.isArray(v.components)||v.components.length>MAX_COMPONENTS)throw new Error('部品: 保存済みライブラリが壊れています。');var seen=new Set();return v.components.map(function(c){return validComponent(c,seen);});}function write(a){var text=JSON.stringify({format:'kaijo-ilapo-components',version:1,components:a});if(text.length>MAX_BYTES)throw new Error('部品: 保存容量の上限を超えました。');storage.setItem(KEY,text);}
    return {list:function(){return clone(read()).map(function(c){delete c.objects;return c;});},save:function(name,objects){if(typeof name!=='string'||!name.trim()||name.trim().length>120||!Array.isArray(objects)||!objects.length||objects.length>MAX_OBJECTS)throw new Error('部品: 名前と選択図形を指定してください。');if(objects.some(function(o){return o.type==='image'&&o.reference;}))throw new Error('部品: 参照画像は部品に登録できません。');var checked=objects.map(check), ids=new Set();checked.forEach(function(o){if(ids.has(o.id))throw new Error('部品: オブジェクトIDが重複しています。');ids.add(o.id);});var base=bounds(checked), os=checked.map(function(o){return translate(o,-base.x,-base.y);}),all=read();if(all.length>=MAX_COMPONENTS)throw new Error('部品: 登録数の上限です。');var c=validComponent({id:core().uid('component'),name:name.trim(),objects:os},new Set(all.map(function(x){return x.id;})));write(all.concat([c]));return clone(c);},remove:function(id){var all=read(),next=all.filter(function(c){return c.id!==id;});if(next.length===all.length)throw new RangeError('部品: 見つかりません。');write(next);},instantiate:function(id,opt){opt=opt||{};var c=read().find(function(x){return x.id===id;});if(!c)throw new RangeError('部品: 見つかりません。');var base=bounds(c.objects), target=opt.size==null?Math.max(base.width,base.height):Number(opt.size),scale=target/Math.max(base.width,base.height), ids=new Map(),group=core().uid('group'), m=[scale,0,0,scale,(Number(opt.x)||0)-base.x*scale,(Number(opt.y)||0)-base.y*scale];if(!Number.isFinite(scale)||scale<=0)throw new Error('部品: サイズが不正です。');c.objects.forEach(function(o){ids.set(o.id,uid());});var out=c.objects.map(function(o){var n=clone(o);n.id=ids.get(o.id);n.group=group;n.locked=false;if(n.type==='connector'){if(!root.IlapoConnectors||!root.IlapoConnectors.transform)throw new Error('部品: IlapoConnectors が必要です。');n=root.IlapoConnectors.transform(n,m);n.style.fontSize*=scale;n.style.strokeWidth*=scale;['from','to'].forEach(function(k){if(n[k].objectId)n[k].objectId=ids.get(n[k].objectId)||null;});}else{n.matrix=(n.matrix||[1,0,0,1,0,0]).slice();n.matrix[0]*=scale;n.matrix[1]*=scale;n.matrix[2]*=scale;n.matrix[3]*=scale;n.matrix[4]=n.matrix[4]*scale+m[4];n.matrix[5]=n.matrix[5]*scale+m[5];}return check(n);});return out;},exportJSON:function(){return JSON.stringify({format:'kaijo-ilapo-components',version:1,components:read()});},importJSON:function(text){if(typeof text!=='string'||text.length>MAX_BYTES)throw new Error('部品: インポートデータが不正です。');var v;try{v=JSON.parse(text);}catch(_){throw new Error('部品: インポートデータが不正です。');}if(!v||v.format!=='kaijo-ilapo-components'||v.version!==1||!Array.isArray(v.components)||v.components.length>MAX_COMPONENTS)throw new Error('部品: インポートデータが不正です。');var seen=new Set(),next;try{next=v.components.map(function(c){return validComponent(c,seen);});}catch(_){throw new Error('部品: インポートデータが不正です。');}write(next);return this.list();}};}
  async function imageFromFile(file,opt){opt=opt||{};if(!file||!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>8*1024*1024)throw new Error('画像: PNG/JPEG/WebP（8MiB以下）を指定してください。');if(typeof createImageBitmap!=='function'||typeof document==='undefined')throw new Error('画像: このブラウザでは読み込めません。');var bmp;try{bmp=await createImageBitmap(file);}catch(_){throw new Error('画像: 画像を解読できません。');}try{if(bmp.width*bmp.height>16000000)throw new Error('画像: 1600万画素以下にしてください。');var maxW=Number(opt.maxWidth)||bmp.width,maxH=Number(opt.maxHeight)||bmp.height,r=Math.min(1,maxW/bmp.width,maxH/bmp.height),w=Math.max(1,Math.round(bmp.width*r)),h=Math.max(1,Math.round(bmp.height*r)),canvas=document.createElement('canvas');canvas.width=bmp.width;canvas.height=bmp.height;canvas.getContext('2d').drawImage(bmp,0,0);var src=canvas.toDataURL('image/png');if(src.length>5*1024*1024)throw new Error('画像: 変換後の画像が大きすぎます。');return check({id:uid(),type:'image',name:file.name||'画像',group:null,locked:true,matrix:[1,0,0,1,0,0],style:Object.assign(clone(style),{opacity:.4}),x:Number(opt.x)||0,y:Number(opt.y)||0,width:w,height:h,src:src,reference:true});}finally{bmp.close();}}
  return{icons:icons,instantiateIcon:instantiateIcon,createLibrary:createLibrary,imageFromFile:imageFromFile};
}));
