(function (root, factory) {
  const expression = typeof module === 'object' && module.exports ? require('./expression.js') : root.GraphExpression;
  const api = factory(expression);
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.GraphCore = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function (Expression) {
  'use strict';
  const fail = m => { throw new Error(m); }, object = v => v && typeof v === 'object' && !Array.isArray(v);
  const clone = value => JSON.parse(JSON.stringify(value)); let serial = 0;
  const uid = () => 'series_' + Date.now().toString(36) + '_' + (++serial).toString(36) + '_' + Math.random().toString(36).slice(2, 8);
  const STYLE = { color:'#2563eb', width:2, dash:'solid', points:false, lines:true, opacity:.85 };
  function createDocument() { return { format:'kaijo-graph', version:1, name:'無題のグラフ', mode:'2d', angle:'rad', axes:{ x:{label:'x',unit:'',min:-10,max:10,scale:'linear'}, y:{label:'y',unit:'',min:-10,max:10,scale:'linear'}, z:{label:'z',unit:'',min:-10,max:10,scale:'linear'} }, equalScale:false, grid:true, legend:true, parameters:[], series:[] }; }
  function createSeries(kind = 'function') { if (!['function','surface','data2d','data3d'].includes(kind)) fail('グラフの種類が不正です。'); return { id:uid(), kind, name:'', expression:kind === 'surface' ? 'z=x^2+y^2' : 'y=x', domain:{x:[-10,10],y:[-10,10]}, rows:[], visible:true, style:clone(STYLE), source:{kind:'user',title:'',url:'',notes:''} }; }
  function finite(n, message, min=-1e9, max=1e9) { if (typeof n !== 'number' || !Number.isFinite(n) || n < min || n > max) fail(message); return n; }
  function text(v, message, limit=500) { if (typeof v !== 'string' || v.length > limit) fail(message); return v; }
  function validAxis(v, name) { if (!object(v)) fail('軸の設定が不正です。'); const min=finite(v.min,'軸の範囲が不正です。'), max=finite(v.max,'軸の範囲が不正です。'); if (min >= max) fail('軸の最小値は最大値より小さくしてください。'); const scale=v.scale === undefined ? 'linear' : v.scale; if (!['linear','log'].includes(scale) || (scale === 'log' && min <= 0)) fail('対数軸は正の範囲にしてください。'); return {label:text(v.label ?? name,'軸ラベルが不正です。',80),unit:text(v.unit ?? '','単位が不正です。',80),min,max,scale}; }
  function validateDocument(input) {
    let raw=input; if (typeof raw === 'string') { if (raw.length > 2*1024*1024) fail('ファイルが大きすぎます。'); try { raw=JSON.parse(raw); } catch { fail('JSONファイルを読み取れません。'); } }
    if (!object(raw) || raw.format !== 'kaijo-graph' || raw.version !== 1) fail('グラフエディタの再編集ファイルを選んでください。');
    if (!Array.isArray(raw.parameters) || !Array.isArray(raw.series) || raw.series.length > 100 || raw.parameters.length > 20 || !object(raw.axes)) fail('文書の一覧または設定が不正です。');
    const out=createDocument(); out.name=text(raw.name,'グラフ名が不正です。',160); if (!['2d','3d'].includes(raw.mode) || !['rad','deg'].includes(raw.angle)) fail('表示設定が不正です。'); out.mode=raw.mode; out.angle=raw.angle;
    for (const key of ['equalScale','grid','legend']) { if (typeof raw[key] !== 'boolean') fail('表示設定が不正です。'); out[key]=raw[key]; } out.axes={x:validAxis(raw.axes.x,'x'),y:validAxis(raw.axes.y,'y'),z:validAxis(raw.axes.z,'z')};
    const reserved=new Set(['x','y','z','e','pi','sin','cos','tan','asin','acos','atan','sqrt','abs','exp','ln','log','floor','ceil','round','min','max','constructor','prototype','__proto__']); const names=new Set();
    out.parameters=raw.parameters.map(p=>{ if(!object(p)||typeof p.name!=='string'||! /^[A-Za-z][A-Za-z0-9_]{0,31}$/.test(p.name)||reserved.has(p.name)||names.has(p.name)) fail('パラメーター名が不正または重複しています。'); names.add(p.name); const min=finite(p.min,'パラメーターの範囲が不正です。'),max=finite(p.max,'パラメーターの範囲が不正です。'),value=finite(p.value,'パラメーターの値が不正です。'),step=finite(p.step,'パラメーターの刻みが不正です。',Number.MIN_VALUE); if(min>=max||value<min||value>max) fail('パラメーターの範囲が不正です。'); return {name:p.name,value,min,max,step}; });
    const ids=new Set(); out.series=raw.series.map(s=>validateSeries(s,out,names,ids)); if(out.series.reduce((total,s)=>total+s.rows.length,0)>50000) fail('数表の総点数は50000点までです。'); if (JSON.stringify(out).length>2*1024*1024) fail('グラフのデータは2MB以内にしてください。'); return out;
  }
  function validateSeries(s, doc, names, ids) { if(!object(s)||!['function','surface','data2d','data3d'].includes(s.kind)||typeof s.id!=='string'||!/^[A-Za-z0-9_-]{1,100}$/.test(s.id)||ids.has(s.id)) fail('系列のIDまたは種類が不正です。'); ids.add(s.id); if(!object(s.domain)||!Array.isArray(s.domain.x)||!Array.isArray(s.domain.y)||s.domain.x.length!==2||s.domain.y.length!==2) fail('表示範囲が不正です。'); const domain={x:s.domain.x.map(v=>finite(v,'表示範囲が不正です。')),y:s.domain.y.map(v=>finite(v,'表示範囲が不正です。'))}; if(domain.x[0]>=domain.x[1]||domain.y[0]>=domain.y[1]) fail('表示範囲が不正です。'); if(!Array.isArray(s.rows)||s.rows.length>10000||typeof s.visible!=='boolean'||!object(s.style)||!object(s.source)) fail('系列の設定が不正です。'); const dims=s.kind==='data3d'?3:2, rows=s.rows.map(row=>{if(!Array.isArray(row)||row.length!==dims)fail('数表の列数が不正です。');return row.map(v=>v===null?null:finite(v,'数表に不正な数値があります。'));}); const st=s.style; if(!/^#[0-9a-f]{6}$/i.test(st.color)||!Number.isFinite(st.width)||st.width<.5||st.width>20||!['solid','dot','dash'].includes(st.dash)||typeof st.points!=='boolean'||typeof st.lines!=='boolean'||!Number.isFinite(st.opacity)||st.opacity<0||st.opacity>1)fail('系列の書式が不正です。'); const src=s.source; let safeUrl=true; if(src.url){try{safeUrl=new URL(src.url).protocol==='https:';}catch{safeUrl=false;}} if(!['user','reference','model'].includes(src.kind)||typeof src.title!=='string'||src.title.length>300||typeof src.notes!=='string'||src.notes.length>3000||typeof src.url!=='string'||src.url.length>2000||!safeUrl)fail('出典が不正です。'); const vars=[...(s.kind==='surface'?['x','y']:['x']),...names]; if(['function','surface'].includes(s.kind)){if(typeof s.expression!=='string'||s.expression.length>1000)fail('数式が不正です。'); if(!Expression)fail('数式処理を読み込めません。'); Expression.compile(s.expression,{variables:vars,angle:doc.angle,target:s.kind==='surface'?'z':'y'});} return {id:s.id,kind:s.kind,name:text(s.name ?? '','系列名が不正です。',160),expression:typeof s.expression==='string'?s.expression:'',domain,rows,visible:s.visible,style:{color:st.color,width:st.width,dash:st.dash,points:st.points,lines:st.lines,opacity:st.opacity},source:{kind:src.kind,title:src.title,url:src.url,notes:src.notes}}; }
  class History {
    constructor(document) { this._undo=[];this._redo=[];this.document=validateDocument(document||createDocument()); }
    get canUndo(){return this._undo.length>0;}
    get canRedo(){return this._redo.length>0;}
    change(mutator){if(typeof mutator!=='function')fail('変更処理が不正です。');const next=clone(this.document);mutator(next);return this.replace(next);}
    replace(doc){
      const clean=validateDocument(doc);
      if(JSON.stringify(clean)===JSON.stringify(this.document))return this.document;
      this._undo.push(clone(this.document));if(this._undo.length>100)this._undo.shift();
      this._redo=[];this.document=clean;return clean;
    }
    undo(){if(!this.canUndo)return this.document;this._redo.push(clone(this.document));this.document=this._undo.pop();return this.document;}
    redo(){if(!this.canRedo)return this.document;this._undo.push(clone(this.document));this.document=this._redo.pop();return this.document;}
  }
  class Store { constructor(storage){if(!storage||typeof storage.getItem!=='function'||typeof storage.setItem!=='function')fail('保存領域を利用できません。');this.storage=storage;} _key(k){if(k!=='auto'&&k!=='saved')fail('保存種類が不正です。');return 'kaijo-graph:'+k;} save(kind,doc){const clean=validateDocument(doc), entry={document:clean,at:new Date().toISOString()};this.storage.setItem(this._key(kind),JSON.stringify(entry));return entry;} load(kind){const raw=this.storage.getItem(this._key(kind));if(raw===null||raw===undefined)return null;try{const x=JSON.parse(raw);if(!object(x)||typeof x.at!=='string')throw Error();return {document:validateDocument(x.document),at:x.at};}catch{fail('保存データを読み取れません。');}} list(){return ['auto','saved'].map(kind=>{const x=this.load(kind);return x?{kind,at:x.at,name:x.document.name}:null;}).filter(Boolean);} }
  function parseTable(text, dimensions) { if(typeof text!=='string'||![2,3].includes(dimensions)||text.length>1024*1024)fail('表データが不正です。'); const normalized=text.replace(/^\uFEFF/,'').replace(/\r\n?/g,'\n'), sep=normalized.includes('\t')?'\t':','; const lines=normalized.split('\n').filter(line=>line.trim()!==''); const fields=line=>{const out=[];let value='',quoted=false,closed=false;for(let i=0;i<line.length;i++){const c=line[i];if(quoted){if(c==='"'&&line[i+1]==='"'){value+='"';i++;}else if(c==='"'){quoted=false;closed=true;}else value+=c;}else if(c==='"'){if(value!==''||closed)fail('CSVの引用符が不正です。');quoted=true;}else if(c===sep){out.push(value);value='';closed=false;}else {if(closed)fail('CSVの引用符が不正です。');value+=c;}}if(quoted)fail('CSVの引用符が閉じていません。');out.push(value);return out;}; const numberCell=v=>{const t=v.trim();return t===''?null:(/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?$/.test(t)?Number(t):undefined);}; if(!lines.length)return[];const first=fields(lines[0]).map(numberCell);let start=0;if(first.some(v=>v===undefined)){if(first.every(v=>v===undefined)&&first.length===dimensions)start=1;else fail('数表に不正な数値があります。');}const rows=[];for(let i=start;i<lines.length;i++){const row=fields(lines[i]).map(numberCell);if(row.length!==dimensions||row.some(v=>v===undefined||v!==null&&!Number.isFinite(v)))fail((i+1)+'行目の数値が不正です。');rows.push(row);}return rows; }
  function tableCSV(rows,headers){if(!Array.isArray(rows))fail('数表が不正です。');const esc=v=>{const s=v===null?'':String(v);return /[",\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s;};return (headers?[headers,...rows]:rows).map(row=>{if(!Array.isArray(row))fail('数表が不正です。');return row.map(esc).join(',');}).join('\n');}
  return {createDocument,createSeries,validateDocument,clone,uid,History,Store,parseTable,tableCSV};
});
