/* Animation effect cards are exercised through the running editor, not source text. */
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs/promises'),http=require('node:http'),path=require('node:path'),os=require('node:os');
const C=require('../core.js'); let chromium;try{({chromium}=require('playwright'));}catch{({chromium}=require(path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')));}
const root=path.resolve(__dirname,'../..');
const server=http.createServer(async(req,res)=>{const rel=decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\/+/,''),file=path.resolve(root,rel.endsWith('/')?rel+'index.html':rel);if(!file.startsWith(root+path.sep))return res.writeHead(403).end();try{res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml'})[path.extname(file)]||'text/plain');res.end(await fs.readFile(file));}catch{res.writeHead(404).end();}});
const settle=page=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
function fixture(){const d=C.createDocument(),p=d.pages[0];d.id='animation-icons';p.board={width:640,height:400,unit:'px',infinite:false};const box=C.makeShape('rect',80,90,140,100,{fill:'#2563EB'});box.id='box';box.name='青い長方形';const image={...C.makeShape('ellipse',0,0,1,1),id:'image',name:'画像',type:'image',reference:false,x:310,y:90,width:110,height:90,src:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScL8xQAAAABJRU5ErkJggg=='};delete image.d;const hidden=C.makeShape('triangle',480,100,90,90,{fill:'#ef4444'});hidden.id='hidden';hidden.name='非表示の三角形';hidden.visible=false;p.objects=[box,image,hidden];p.animations=[{id:'existing',targets:['box'],effect:'fade',mode:'in',trigger:'click',duration:600,delay:0},{id:'hidden-motion',targets:['hidden'],effect:'wipe',mode:'out',direction:'left',trigger:'click',duration:400,delay:0}];return C.validateDocument(d);}
(async()=>{const supplied=process.argv.find(value=>/^https?:/.test(value));if(!supplied)await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome',headless:true}),context=await browser.newContext({viewport:{width:1280,height:860}}),page=await context.newPage(),errors=[];page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));const read=()=>page.evaluate(()=>IlapoEditor.getDocument());
 async function load(){const d=fixture();await page.locator('#file-input').setInputFiles({name:'animation-icons.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(d))});await page.waitForFunction(id=>IlapoEditor.getDocument().id===id,d.id);await settle(page);}
 async function select(id){await page.locator('#objects-toggle').click();await page.locator(`[data-pick-object="${id}"]`).click();await page.locator('#inspector-close').click();await settle(page);}
 async function list(){const quick=page.locator('#selection-bar [data-action="animations"]');if(await quick.isVisible())await quick.click();else{await page.locator('#selection-more').click();await page.locator('#command-menu [data-action="animations"]').click();}await page.locator('#inspector-panel').waitFor();}
 async function edit(){await list();await page.locator('[data-animation-edit="0"]').click();await page.locator('[data-animation-choice]').first().waitFor();}
 async function submit(){const button=page.locator('#inspector-submit');if(await button.isVisible())await button.click();await settle(page);}
 try{await page.goto(supplied||`http://127.0.0.1:${server.address().port}/illustslide/`);await page.waitForFunction(()=>!!window.IlapoEditor);
  const expected={'fade-in':{effect:'fade',mode:'in'},'fade-out':{effect:'fade',mode:'out'},'wipe-right-in':{effect:'wipe',direction:'right',mode:'in'},'wipe-left-in':{effect:'wipe',direction:'left',mode:'in'},'wipe-down-in':{effect:'wipe',direction:'down',mode:'in'},'wipe-up-in':{effect:'wipe',direction:'up',mode:'in'},'wipe-right-out':{effect:'wipe',direction:'right',mode:'out'},'wipe-left-out':{effect:'wipe',direction:'left',mode:'out'},'wipe-down-out':{effect:'wipe',direction:'down',mode:'out'},'wipe-up-out':{effect:'wipe',direction:'up',mode:'out'},color:{effect:'color'},move:{effect:'move'}};
  for(const [key,want] of Object.entries(expected)){await load();await select('box');await edit();assert.equal(await page.locator('[data-animation-choice]').count(),12);await page.locator(`[data-animation-choice="${key}"]`).click();assert.equal(await page.locator(`[data-animation-choice="${key}"]`).getAttribute('aria-pressed'),'true',key);assert.equal(await page.locator('#inspector-form').evaluate(form=>form.checkValidity()),true);await page.locator('#animation-duration').fill('.75');await page.locator('#animation-delay').fill('.2');if(key==='move'){await page.locator('#animation-dx').fill('37');await page.locator('#animation-dy').fill('-12');}if(key==='color')await page.locator('[data-animation-color="#EF4444"]').click();await submit();assert.equal(await page.locator('#inspector-error').isHidden(),true);const a=(await read()).pages[0].animations[0];for(const [field,value]of Object.entries(want))assert.equal(a[field],value,key);assert.equal(a.duration,750);assert.equal(a.delay,200);if(key==='move')assert.deepEqual([a.dx,a.dy],[37,-12]);if(key==='color')assert.equal(a.color,'#EF4444');assert.deepEqual(C.validateDocument(await read()),await read());}
  await load();await select('box');await edit();const before=await read();await page.locator('[data-animation-choice="move"]').click();await submit();const changed=await read();assert.notDeepEqual(changed,before,'既存編集は即時反映');await page.locator('#canvas').focus();await page.keyboard.press('Meta+z');await settle(page);assert.deepEqual(await read(),before,'既存編集は1 Undo');
  await load();await select('box');await edit();const validBefore=await read();await page.locator('#animation-duration').fill('-1');await settle(page);assert.equal(await page.locator('#inspector-form').evaluate(form=>form.checkValidity()),false,'不正な時間はフォーム検証で拒否する');assert.deepEqual(await read(),validBefore,'不正な自動編集は保存しない');
  await load();await select('box');await list();const noAdd=await read();await page.locator('#animation-add').click();await page.locator('[data-animation-choice="wipe-up-out"]').click();assert.deepEqual(await read(),noAdd,'新規追加は確定前に保存しない');await submit();assert.equal((await read()).pages[0].animations.length,3);
  await load();await select('image');await list();await page.locator('#animation-add').click();assert.equal(await page.locator('[data-animation-choice="color"]').isDisabled(),true,'画像で色変更を無効にする');await page.locator('#inspector-close').click();
  await load();await select('box');await list();assert.equal(await page.locator('.animation-row-unavailable').count(),1);assert.match(await page.locator('#inspector-body').innerText(),/クリック 1回/);assert.equal(await page.locator('.animation-row .object-preview').count(),2);assert.equal(await page.locator('.animation-row .animation-effect-icon').count(),2);
  await page.evaluate(()=>document.documentElement.dataset.theme='dark');await page.screenshot({path:'/private/tmp/illustslide-animation-list.png'});await page.locator('[data-animation-edit="0"]').click();await page.mouse.move(100,700);await page.screenshot({path:'/private/tmp/illustslide-animation-effects.png'});
  const triggers=page.locator('[data-animation-trigger]');
  assert.equal(await triggers.count(),3);
  assert.deepEqual(await triggers.evaluateAll(buttons=>buttons.map(b=>b.getAttribute('aria-label'))),['クリック時','前の動きと同時','前の動きの後']);
  assert.equal(await triggers.evaluateAll(buttons=>buttons.every(b=>b.querySelector('svg')&&b.innerText.trim()==='')),true,'開始タイミングは名前付きのアイコンだけで表示');
  await page.locator('.animation-trigger-group').scrollIntoViewIfNeeded();await settle(page);await page.screenshot({path:'/private/tmp/illustslide-animation-timing.png'});
  for(const width of [320,390,1280]){await page.setViewportSize({width,height:860});await settle(page);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await page.evaluate(()=>{const p=document.getElementById('inspector-panel');return p.scrollWidth<=p.clientWidth;}),true);}
  assert.deepEqual(errors,[]);console.log('animation-icons-browser.test.cjs: passed');
 }finally{await context.close();await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
