'use strict';
const assert=require('node:assert/strict'),A=require('../arrange.js');
const near=(actual,expected,message)=>assert.ok(Math.abs(actual-expected)<1e-9,(message||'値')+`: ${actual} != ${expected}`);
const page=objects=>({objects});
const measure=(ids,p)=>{
  const found=p.objects.filter(object=>ids.includes(object.id));
  const left=Math.min(...found.map(object=>object.x)),top=Math.min(...found.map(object=>object.y));
  const right=Math.max(...found.map(object=>object.x+object.width)),bottom=Math.max(...found.map(object=>object.y+object.height));
  return {x:left,y:top,width:right-left,height:bottom-top};
};
const make=(id,x,y,width,height,extra={})=>({id,name:id,x,y,width,height,group:null,...extra});
const shift=(box,m)=>({x:m[0]*box.x+m[2]*box.y+m[4],y:m[1]*box.x+m[3]*box.y+m[5],width:Math.abs(m[0])*box.width+Math.abs(m[2])*box.height,height:Math.abs(m[1])*box.width+Math.abs(m[3])*box.height});
const byId=(steps,id)=>steps.find(step=>step.ids.includes(id));
let p=page([make('a',-20,5,10,10,{name:'長方形'}),make('b',20,30,20,8),make('c',70,-2,5,20)]);
let units=A.collect(p,['b','unknown','a','c'],measure);
assert.deepEqual(units.map(unit=>unit.key),['b','a','c'],'選択順を保ち、未知IDを無視する');
assert.equal(units[1].label,'長方形');assert.deepEqual(p.objects.map(object=>object.id),['a','b','c'],'collectはページを変更しない');
let steps=A.plan(units,'left',{reference:'object',key:'a'});near(byId(steps,'b').matrix[4],-40);near(byId(steps,'c').matrix[4],-90);assert.equal(byId(steps,'a'),undefined,'基準図形は動かさない');
steps=A.plan(units,'right',{reference:'selection'});near(byId(steps,'a').matrix[4],85);near(byId(steps,'b').matrix[4],35);assert.equal(byId(steps,'c'),undefined,'選択範囲の端は保つ');
steps=A.plan(units,'center',{reference:'board',board:{width:200,height:100}});near(byId(steps,'a').matrix[4],115);near(byId(steps,'b').matrix[4],70);near(byId(steps,'c').matrix[4],27.5);
steps=A.plan(units,'center',{reference:'selection'});near(byId(steps,'a').matrix[4],42.5);near(byId(steps,'b').matrix[4],-2.5);near(byId(steps,'c').matrix[4],-45,'選択範囲の左右中央にそろえる');
steps=A.plan(units,'top',{reference:'board',board:{x:999,y:999,width:200,height:100}});near(byId(steps,'a').matrix[5],-5);near(byId(steps,'b').matrix[5],-30);near(byId(steps,'c').matrix[5],2,'用紙の原点は常に0,0');
steps=A.plan(units,'bottom',{reference:'board',board:{width:200,height:100}});near(byId(steps,'a').matrix[5],85);near(byId(steps,'b').matrix[5],62);near(byId(steps,'c').matrix[5],82);
steps=A.plan([units[0]],'middle',{reference:'board',board:{width:200,height:100}});near(steps[0].matrix[5],16,'1個でも用紙中央へ整列できる');
assert.throws(()=>A.plan([units[0]],'left',{reference:'object'}),/2つ以上/);
assert.throws(()=>A.plan([units[0]],'size',{reference:'board',board:{width:200,height:100}}),/2つ以上/,'大きさ合わせは用紙基準でも2個以上必要');
assert.throws(()=>A.plan(units,'left',{reference:'board',board:{width:1,height:1,infinite:true}}),/無限キャンバス/);
const grouped=page([make('g1',10,0,10,10,{group:'g',name:'長方形'}),make('g2',30,5,10,10,{group:'g'}),make('x',100,0,10,10)]);
units=A.collect(grouped,['g2','x','g1'],measure);assert.deepEqual(units[0].ids,['g1','g2']);assert.equal(units[0].label,'長方形など2個');
steps=A.plan(units,'left',{reference:'object',key:'x'});near(byId(steps,'g1').matrix[4],90);assert.deepEqual(byId(steps,'g1').ids,['g1','g2'],'グループ全体へ同じ変換を返す');
p=page([make('a',0,0,10,2),make('b',20,0,20,2),make('c',80,0,10,2)]);units=A.collect(p,['a','b','c'],measure);
steps=A.plan(units,'distribute-x',{reference:'object',key:'b'});near(byId(steps,'b').matrix[4],15);assert.equal(byId(steps,'a'),undefined);assert.equal(byId(steps,'c'),undefined,'等間隔は既存の両端を保つ');
steps=A.plan(units,'distribute-x',{reference:'board',board:{width:200,height:100}});near(byId(steps,'b').matrix[4],70);near(byId(steps,'c').matrix[4],110);
const vertical=A.collect(page([make('a',0,10,2,10),make('b',0,30,2,20),make('c',0,100,2,10)]),['a','b','c'],measure);
steps=A.plan(vertical,'distribute-y',{reference:'selection'});near(byId(steps,'b').matrix[5],20);assert.equal(byId(steps,'a'),undefined);assert.equal(byId(steps,'c'),undefined,'縦方向でも既存の両端を保つ');
steps=A.plan(units,'width',{reference:'board',key:'b'});let resized=shift(units[0].b,byId(steps,'a').matrix);near(resized.width,20);near(resized.x+resized.width/2,5,'幅合わせは中心を保つ');assert.equal(byId(steps,'b'),undefined);
steps=A.plan(units,'size',{reference:'selection',key:'a'});resized=shift(units[1].b,byId(steps,'b').matrix);near(resized.width,10);near(resized.height,2);near(resized.x+resized.width/2,30,'大きさ合わせは基準図形で決まり中心を保つ');
const zero=A.plan([{key:'a',ids:['a'],b:{x:0,y:0,width:0,height:4}},{key:'b',ids:['b'],b:{x:10,y:5,width:20,height:8}}],'size',{key:'b'});assert.equal(byId(zero,'a').matrix[0],1,'ゼロ幅は拡縮しない');near(byId(zero,'a').matrix[3],2);
for(const bad of ['diagonal',''])assert.throws(()=>A.plan(units,bad,{}),/未対応/);
assert.throws(()=>A.plan(units,'left',{reference:'outside'}),/未対応/);assert.throws(()=>A.plan([{key:'x',ids:['x'],b:{x:0,y:0,width:NaN,height:1}}],'left',{reference:'board',board:{width:1,height:1}}),/有限/);
console.log('arrange.test.cjs: passed');
