'use strict';
const assert=require('node:assert/strict'),G=require('../grid.js'),Guides=require('../guides.js');
const pixel={snapPixel:true,snap:false,gridStep:4},grid={...pixel,snap:true},free={...pixel,snapPixel:false};
const near=(a,b)=>assert(Math.abs(a-b)<1e-7,`${a} != ${b}`);
assert.deepEqual(G.point({x:3.49,y:7.51},pixel),{x:3,y:8});
assert.deepEqual(G.point({x:-3.2,y:-7.7},pixel),{x:-3,y:-8});
assert.deepEqual(G.point({x:3.49,y:7.51},grid),{x:4,y:8});
assert.deepEqual(G.point({x:3.49,y:7.51},pixel,{altKey:true}),{x:3.49,y:7.51});
assert.deepEqual(G.point({x:3.49,y:7.51},free),{x:3.49,y:7.51});
const box={x:1.3,y:2.7,width:4,height:6},delta=G.moveDelta(box,{x:2.2,y:1.5},pixel);
near(box.x+delta.x,4);near(box.y+delta.y,4);
const nudge=G.nudgeDelta(box,{x:1,y:0},pixel);near(box.x+nudge.x,2);assert.equal(nudge.y,0);
const resized=G.resize(box,{x:1.3,y:2.7,width:7.3,height:8.1},{x:'end',y:'end'},pixel);
near(resized.x,box.x);near(resized.y,box.y);near(resized.x+resized.width,9);near(resized.y+resized.height,11);
const start=G.resize(box,{x:.3,y:.2,width:5,height:8.5},{x:'start',y:'start'},pixel);
near(start.x,0);near(start.y,0);near(start.x+start.width,5.3);near(start.y+start.height,8.7);
const ratio=G.resize(box,{x:1.3,y:2.7,width:6.3,height:9.45},{x:'end',y:'end',uniform:true},pixel);
near(ratio.width/ratio.height,4/6);near(ratio.x+ratio.width,8);
const tiny=G.resize({x:0,y:0,width:4,height:6},{x:0,y:0,width:.04,height:.06},{x:'end',y:'end'},pixel);
assert.deepEqual(tiny,{x:0,y:0,width:1,height:1},'minimum size stays on the pixel grid');
const session={box:{x:1,y:2,width:2,height:2},targets:[{id:'fraction',box:{x:5.2,y:8.2,width:2,height:2},board:false}]};
const proposed={x:3,y:6},fallback=G.moveDelta(session.box,proposed,pixel),accept=(_axis,value)=>G.matches(value,1);
const aligned=Guides.move(session,proposed,{zoom:20,fallback,accept});
assert.deepEqual(aligned.delta,fallback,'fractional guides do not override the pixel lattice');
assert.equal(aligned.lines.length,0,'rejected guides must not draw a false alignment');
const continuous=Guides.move(session,proposed,{zoom:20});assert(continuous.lines.length,'free mode can still align to fractional objects');
assert.deepEqual(box,{x:1.3,y:2.7,width:4,height:6},'source geometry is untouched');
console.log('grid.test.cjs: passed');
