'use strict';
const assert=require('node:assert/strict');
const M=require('../objects-model.js');
const make=()=>({objects:[{id:'a',group:'g'},{id:'other',group:'h'},{id:'b',group:'g'},{id:'single',group:null},{id:'h-last',group:'h'},{id:'c',group:'g'}]});
const ids=page=>page.objects.map(object=>object.id);
let page=make();const before=JSON.stringify(page);
assert.deepEqual(M.units(page.objects).map(unit=>unit.key),['g:g','g:h','o:single']);
assert.equal(JSON.stringify(page),before,'一覧の作成は作品を変更しない');
M.reorderChild(page,'a','b',true);
assert.deepEqual(ids(page),['b','other','a','single','h-last','c'],'前面へ移動し、他の図形が占める位置は不変');
M.reorderChild(page,'a','b',false);
assert.equal(JSON.stringify(page),before,'背面へ戻して元の配列に戻る');
M.reorderChild(page,'a','other',true);assert.equal(JSON.stringify(page),before,'別グループへ移動しない');
M.reorder(page,'g:g','o:single',false);
assert.deepEqual(ids(page),['other','a','b','c','single','h-last']);
assert.deepEqual(page.objects.filter(o=>o.group!=='g').map(o=>o.id),['other','single','h-last'],'対象以外の相対順を保つ');
page=make();M.reorder(page,'o:single','g:g',true);
assert.deepEqual(ids(page),['a','other','b','h-last','c','single']);
assert.equal(M.units([{id:'g',group:null},{id:'child',group:'g'}]).length,2,'同名のgroup IDとobject IDは混同しない');
console.log('illustSlide objects model tests passed');
