/* 発表者ノートと発表スキップは、ページごとに即時保存して履歴へ入れる。 */
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),http=require('node:http');
const C=require('../core.js');
let chromium;try{({chromium}=require('playwright'));}catch{({chromium}=require(path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')));}
const root=path.resolve(__dirname,'../..');
const server=http.createServer(async(req,res)=>{const relative=decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\/+/,''),file=path.resolve(root,relative.endsWith('/')?relative+'index.html':relative);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml'})[path.extname(file)]||'text/plain');res.end(await fs.readFile(file));}catch{res.writeHead(404).end();}});
const settle=page=>page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
const documentValue=()=>{const doc=C.createDocument();doc.id='presenter-pages';doc.name='発表者メモ';doc.pages[0].id='first';doc.pages[0].name='最初';const second=C.createPage('次',{width:640,height:480,unit:'px',infinite:false});second.id='second';doc.pages.push(second);return doc;};
(async()=>{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const browser=await chromium.launch({channel:'chrome',headless:true}),context=await browser.newContext({viewport:{width:1280,height:800}}),page=await context.newPage();try{await page.goto(`http://127.0.0.1:${server.address().port}/illustslide/`);await page.waitForFunction(()=>!!window.IlapoEditor);const doc=documentValue();await page.locator('#file-input').setInputFiles({name:'presenter.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(doc))});await page.waitForFunction(()=>IlapoEditor.getDocument().id==='presenter-pages');await page.locator('#pages-toggle').click();await settle(page);
  const notes=page.locator('#page-notes');await notes.focus();await notes.fill('最初の説明');await settle(page);assert.equal((await page.evaluate(()=>IlapoEditor.getDocument())).pages[0].notes,'最初の説明');
  await page.keyboard.press('Meta+z');await settle(page);assert.equal((await page.evaluate(()=>IlapoEditor.getDocument())).pages[0].notes||'','');await page.keyboard.press('Shift+Meta+z');await settle(page);
  await page.locator('[data-page-pick="1"]').click();await settle(page);assert.equal(await notes.inputValue(),'');await notes.evaluate(element=>{element.value='日本語入力';element.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));element.dispatchEvent(new InputEvent('input',{bubbles:true,isComposing:true,data:'日本語入力'}));element.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true,data:'日本語入力'}));});await settle(page);assert.equal((await page.evaluate(()=>IlapoEditor.getDocument())).pages[1].notes,'日本語入力');
  const beforeHover=await page.evaluate(()=>JSON.stringify(IlapoEditor.getDocument()));
  await page.locator('[data-page-more="second"]').hover();assert(await page.locator('#page-more-menu-second').isVisible());assert.equal(await page.evaluate(()=>JSON.stringify(IlapoEditor.getDocument())),beforeHover);
  await page.locator('[data-page-more="second"]').focus();await page.keyboard.press('Escape');assert.equal(await page.locator('#page-more-menu-second').isVisible(),false);assert(await notes.isVisible());
  await page.keyboard.press('ArrowDown');assert.equal(await page.locator('[data-page-skip="second"]').evaluate(el=>el===document.activeElement),true);await page.locator('[data-page-skip="second"]').click();await settle(page);const saved=await page.evaluate(()=>IlapoEditor.getDocument());assert.equal(saved.pages[1].skip,true);assert.equal(await page.locator('.page-card.presentation-skipped').count(),1);assert.match(await page.locator('[data-page-pick="1"]').getAttribute('aria-label'),/発表スキップ/);
  await page.locator('.top [data-action=undo]').click();await settle(page);assert.notEqual((await page.evaluate(()=>IlapoEditor.getDocument())).pages[1].skip,true);console.log('presenter-pages-browser.test.cjs: passed');
}finally{await context.close();await browser.close();await new Promise(resolve=>server.close(resolve));}})().catch(error=>{console.error(error);process.exitCode=1;});
