/* Rich text editing: contenteditable selection, inline runs, Markdown, IME and paste. */
'use strict';
const assert = require('node:assert/strict'), fs = require('node:fs/promises'), http = require('node:http'), path = require('node:path'), os = require('node:os');
let chromium; try { ({ chromium } = require('playwright')); } catch { ({ chromium } = require(path.join(os.homedir(), '.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'))); }
const root = path.resolve(__dirname, '../..');
const server = http.createServer(async (req, res) => { const relative = decodeURIComponent(new URL(req.url, 'http://localhost').pathname).replace(/^\/+/, '') || 'illustslide/index.html', file = path.resolve(root, relative.endsWith('/') ? relative + 'index.html' : relative); if (!file.startsWith(root + path.sep)) return res.writeHead(403).end(); try { res.writeHead(200, { 'Content-Type': ({ '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.svg': 'image/svg+xml' })[path.extname(file)] || 'application/octet-stream' }); res.end(await fs.readFile(file)); } catch { res.writeHead(404).end(); } });
const settle = page => page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
async function selection(page, start, end) { await page.locator('#text-input').evaluate((el, pair) => { const w=document.createTreeWalker(el,NodeFilter.SHOW_TEXT); let n,at=0,a,b,ao,bo; while((n=w.nextNode())){const next=at+n.data.length;if(!a&&pair[0]>=at&&pair[0]<=next){a=n;ao=pair[0]-at;}if(!b&&pair[1]>=at&&pair[1]<=next){b=n;bo=pair[1]-at;}at=next;}const r=document.createRange(),s=getSelection();r.setStart(a||el,a?ao:0);r.setEnd(b||el,b?bo:0);el.focus();s.removeAllRanges();s.addRange(r); }, [start,end]); }
async function doc(page) { return page.evaluate(() => IlapoEditor.getDocument()); }
async function textObject(page) { return (await doc(page)).pages[0].objects.find(o => o.type === 'text'); }
(async()=>{
  const supplied=process.argv.find(value=>/^https?:/.test(value)); if(!supplied) await new Promise(resolve => server.listen(0,'127.0.0.1',resolve)); const browser=await chromium.launch({channel:'chrome',headless:true}), context=await browser.newContext({viewport:{width:1280,height:800}}), page=await context.newPage(); page.setDefaultTimeout(12000); const errors=[];page.on('pageerror',e=>errors.push(e.message));
  try {
    await page.goto(supplied||`http://127.0.0.1:${server.address().port}/illustslide/`); await page.waitForFunction(()=>!!IlapoEditor&&!!IlapoTextMarkdown);
    const freshCdp=await context.newCDPSession(page); await page.locator('[data-tool=text]').click(); await page.locator('#canvas').click({position:{x:120,y:120}}); await page.locator('#text-input').focus(); await freshCdp.send('Input.imeSetComposition',{text:'へんかん',selectionStart:4,selectionEnd:4,replacementStart:0,replacementEnd:0}); await settle(page); assert.equal((await doc(page)).pages[0].objects.filter(o=>o.type==='text').length,0,'新規文字のIME変換中は空オブジェクトを作らない'); await freshCdp.send('Input.insertText',{text:'変換'}); await settle(page); assert.equal((await doc(page)).pages[0].objects.find(o=>o.type==='text').runs.map(r=>r.text).join(''),'変換','新規文字は最初のIME確定だけで作成する'); await page.reload(); await page.waitForFunction(()=>!!IlapoEditor&&!!IlapoTextMarkdown);
    await page.locator('[data-tool=text]').click(); await page.locator('#canvas').click({position:{x:300,y:240}}); await page.locator('#text-input').fill('ABCD');
    assert.equal(await page.locator('#text-input').getAttribute('contenteditable'),'true'); assert.equal(await page.locator('#text-input').getAttribute('role'),'textbox');
    await selection(page,1,3); await page.locator('#text-bold').click(); await settle(page); let object=await textObject(page);
    assert.deepEqual(object.runs,[{text:'A',script:'normal'},{text:'BC',script:'normal',bold:true},{text:'D',script:'normal'}],'選択範囲だけを太字にする');
    assert.equal(await page.locator('#text-bold').getAttribute('aria-pressed'),'true'); assert.equal(await page.locator('#text-input').evaluate(el=>[...el.querySelectorAll('span')].some(span=>Number(getComputedStyle(span).fontWeight)>=700)),true,'入力欄自身が太字をプレビューする');
    await selection(page,2,2); await page.locator('#text-italic').click(); await page.keyboard.insertText('x'); await settle(page); object=await textObject(page);
    assert.equal(object.runs.map(r=>r.text).join(''),'ABxCD'); assert(object.runs.some(r=>r.text==='x'&&r.italic),'範囲なしの書式は次の入力へ適用する');
    await page.locator('#text-select-all').click(); await page.locator('#text-colors summary').click(); await page.locator('#text-color-hex').fill('#0F766E'); await page.locator('#text-color-hex').dispatchEvent('input'); await settle(page); object=await textObject(page);
    assert(object.runs.every(r=>r.fill==='#0F766E'),'全選択後の色指定は全runへ適用する');
    await selection(page,0,1); assert(await page.locator('#text-input').evaluate(el=>document.activeElement===el)); await page.locator('#text-bold').click(); assert(await page.locator('#text-input').evaluate(el=>document.activeElement===el),'書式ボタン後も入力欄へフォーカスを戻す');
    await page.locator('#text-markdown-tools summary').click(); await page.locator('#text-markdown-input').fill('**太字** *斜体* x^2^ H_2_O {{color=#CC0000|赤}}'); await settle(page);
    assert.match(await page.locator('#text-markdown-preview').textContent(),/太字\s*斜体\s*x2\s*H2O\s*赤/); await page.locator('#text-select-all').click(); await page.locator('#text-markdown-insert').click(); await settle(page); object=await textObject(page);
    assert.match(object.runs.map(r=>r.text).join(''),/太字\s*斜体\s*x2\s*H2O\s*赤/); assert(object.runs.some(r=>r.bold)&&object.runs.some(r=>r.italic)&&object.runs.some(r=>r.script==='super')&&object.runs.some(r=>r.script==='sub')&&object.runs.some(r=>r.fill==='#CC0000'),'Markdown挿入は許可されたrunへ変換する'); const rendered=await page.locator(`#artwork [data-object="${object.id}"] text`).evaluate(el=>[...el.querySelectorAll('tspan')].map(span=>({text:span.textContent,weight:Number(getComputedStyle(span).fontWeight),italic:getComputedStyle(span).fontStyle,fill:span.getAttribute('fill')||getComputedStyle(span).fill,script:span.getAttribute('baseline-shift')}))); assert(rendered.some(run=>run.text.includes('太字')&&run.weight>=700),'キャンバスは太字runを描画する'); assert(rendered.some(run=>run.text.includes('斜体')&&run.italic==='italic'),'キャンバスは斜体runを描画する'); assert(rendered.some(run=>run.text.includes('赤')&&(/#CC0000/i.test(run.fill)||/rgb\(204,\s*0,\s*0\)/.test(run.fill))),'キャンバスは赤色runを描画する'); assert(rendered.some(run=>run.text.includes('2')&&run.script==='super'),'キャンバスは上付きrunへbaseline-shift=superを付ける'); assert(rendered.some(run=>run.text.includes('2')&&run.script==='sub'),'キャンバスは下付きrunへbaseline-shift=subを付ける'); await page.locator('#text-markdown-tools summary').click(); await page.locator('#text-input').scrollIntoViewIfNeeded(); await fs.mkdir('/private/tmp/illustslide-text-qa',{recursive:true}); await page.screenshot({path:'/private/tmp/illustslide-text-qa/rich-text-light-1280.png',fullPage:true});
    const beforeComposition=JSON.stringify(await textObject(page)), cdp=await context.newCDPSession(page); await page.locator('#text-input').focus(); await cdp.send('Input.imeSetComposition',{text:'へんかん',selectionStart:4,selectionEnd:4,replacementStart:0,replacementEnd:0}); await settle(page); assert.equal(JSON.stringify(await textObject(page)),beforeComposition,'IME変換中は作品を更新しない'); await cdp.send('Input.insertText',{text:'変換'}); await settle(page); assert.match((await textObject(page)).runs.map(r=>r.text).join(''),/変換/,'IME確定は作品へ反映する');
    await page.locator('#text-input').evaluate(el=>{el.focus();const dt=new DataTransfer();dt.setData('text/plain','<b>安全</b>');dt.setData('text/html','<img src=x onerror=alert(1)>危険');el.dispatchEvent(new ClipboardEvent('paste',{bubbles:true,clipboardData:dt}));}); await settle(page); object=await textObject(page); assert.match(object.runs.map(r=>r.text).join(''),/<b>安全<\/b>/,'貼り付けはplain textとして保持する'); assert.equal(await page.locator('#text-input img').count(),0,'貼り付けHTMLをDOMへ入れない');
    await page.keyboard.press('Meta+z'); await settle(page); await page.keyboard.press('Shift+Meta+z'); await settle(page); assert.match((await textObject(page)).runs.map(r=>r.text).join(''),/<b>安全<\/b>/,'貼り付けをUndo/Redoできる');
    await page.locator('[data-tool=rect]').click(); await page.locator('#canvas').click({position:{x:500,y:300}}); await page.locator('#canvas').press('v'); await page.locator('#artwork [data-object]').last().dblclick(); await page.locator('#text-input').waitFor(); const labelId=(await doc(page)).pages[0].objects.find(o=>o.type==='path').id, labelCdp=await context.newCDPSession(page); await page.locator('#text-input').focus(); await labelCdp.send('Input.imeSetComposition',{text:'へんかん',selectionStart:4,selectionEnd:4,replacementStart:0,replacementEnd:0}); await settle(page); assert.equal((await doc(page)).pages[0].objects.find(o=>o.id===labelId).label,undefined,'図形ラベルのIME変換中はlabelを作らない'); await labelCdp.send('Input.insertText',{text:'図形内'}); await settle(page); assert.equal((await doc(page)).pages[0].objects.find(o=>o.id===labelId).label.runs.map(r=>r.text).join(''),'図形内','図形ラベルはIME確定だけで作品へ反映する');
    await page.setViewportSize({width:390,height:736}); await page.locator('#inspector-close').click(); await page.locator('#board-toggle').click(); await page.locator('#view-toggle').click(); await page.locator('#view-theme').selectOption('dark'); await settle(page); await page.locator('#inspector-close').click(); await page.locator(`#artwork [data-object="${object.id}"]`).dblclick(); await page.locator('#text-input').waitFor(); await page.locator('#text-input').scrollIntoViewIfNeeded(); await page.screenshot({path:'/private/tmp/illustslide-text-qa/rich-text-dark-390.png',fullPage:true}); assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'390px darkで横はみ出しがない');
    assert.deepEqual(errors,[],errors.join('\n')); console.log('text-rich-ui-browser.test.cjs: passed');
  } finally { await context.close();await browser.close();if(!supplied)await new Promise(resolve=>server.close(resolve)); }
})().catch(error=>{console.error(error);process.exitCode=1;server.close();});
