const assert = require('node:assert/strict');
const C = require('../core.js'), T = require('../tables.js'), A = require('../analysis.js');
const Statistics = require('../statistics.js'), Templates = require('../template-library.js');
const table = {columns:['時刻','測定値','偏差','割合'],rows:[[0,10,999,999],[1,20,999,999],[2,30,999,999]],mapping:{x:0,y:2,z:null,errorX:null,errorY:null},formulas:[null,null,'[@測定値] - AVERAGE([測定値])','[@測定値] / SUM([測定値]) * 100']};
const raw = JSON.stringify(table), clean = T.validate(table);
assert.equal(JSON.stringify(table),raw,'validation does not modify source data');
assert.deepEqual(clean.rows.map(r=>r[2]),[-10,0,10]);
assert.equal(clean.rows[0][3],10/60*100,'stored results retain precision');
assert.deepEqual(T.calculationErrors(clean),[]);
const source=C.createSeries('data2d');source.id='observed';source.name='観測';T.assign(source,table);
const doc=C.createDocument();doc.series=[source];
const fit=C.createAnnotation('regression');fit.id='fit';fit.seriesId=source.id;doc.annotations=[fit];
const before=C.validateDocument(doc);assert.equal(before.version,14);assert.deepEqual(before.series[0].rows,[[0,-10],[1,0],[2,10]]);
const history=new C.History(before);
history.change(d=>{d.series[0].dataTable.rows[2][1]=60;});
assert.deepEqual(history.document.series[0].rows.map(r=>r[1]),[-20,-10,30]);
assert(Math.abs(A.fit(history.document.series[0],'linear').coefficients[1]-25)<1e-10,'regression follows recalculated values');
assert.equal(Statistics.summarize(T.fromSeries(history.document.series[0]),[2])[0].mean,0);
assert.equal(history.document.series[0].dataTable.rows[2][1],60,'raw measurement remains available');
history.undo();assert.deepEqual(history.document,before);history.redo();
const saved=JSON.stringify(history.document);assert.deepEqual(C.validateDocument(saved),history.document);
const tampered=C.clone(history.document);tampered.series[0].rows=[[0,0],[1,0],[2,0]];tampered.series[0].dataTable.rows.forEach(row=>row[2]=123);
assert.deepEqual(C.validateDocument(tampered),history.document,'calculated caches are rebuilt from inputs and formulas');
const old=C.createDocument();old.version=11;assert.equal(C.validateDocument(old).version,14);
const falseVersion=C.clone(before);falseVersion.version=11;assert.throws(()=>C.validateDocument(falseVersion),/版と計算列/);
const wrongFormula=C.clone(before);wrongFormula.series[0].dataTable.formulas[2]='[@存在しない]';assert.throws(()=>C.validateDocument(wrongFormula),/不明|見つか/);
const cycle=C.clone(before);cycle.series[0].dataTable.formulas[2]='[@割合]';cycle.series[0].dataTable.formulas[3]='[@偏差]';assert.throws(()=>C.validateDocument(cycle),/循環/);
const template=Templates.create(history.document,{name:'計算のひな形',includeData:false});assert.deepEqual(template.document.series[0].rows,[]);assert.deepEqual(template.document.series[0].dataTable.formulas,table.formulas);
const reused=C.clone(template.document);reused.series[0].dataTable.rows=[[0,1,null,null],[1,3,null,null]];reused.series[0].rows=[[0,0],[1,0]];
assert.deepEqual(C.validateDocument(reused).series[0].rows,[[0,-1],[1,1]],'empty templates calculate new observations');
const failure={...table,formulas:[null,null,'1 / [@測定値]',null],rows:[[0,0,null,0],[1,null,null,0],[2,2,null,0]]};
const failed=T.validate(failure);assert.deepEqual(failed.rows.map(row=>row[2]),[null,null,.5]);
assert.deepEqual(T.calculationErrors(failed).map(error=>[error.row,error.column]),[[0,2]],'missing data is distinct from a calculation error');
assert.match(T.calculationWarning(failed),/1件/);
assert.equal(T.validate({...table,formulas:Array(4).fill(null)}).formulas,undefined,'plain tables retain their old shape');
const numeric=C.createDocument(),n=C.createSeries('data2d');T.assign(n,{columns:['x','y'],rows:[[1,2]],mapping:{x:0,y:1,z:null,errorX:null,errorY:null}});numeric.series=[n];numeric.series[0].rows[0][1]=3;assert.throws(()=>C.validateDocument(numeric),/一致/,'uncalculated table projection validation is unchanged');
const three=C.createSeries('data3d');T.assign(three,{columns:['x','y','z'],rows:[[1,2,0],[3,4,0]],mapping:{x:0,y:1,z:2,errorX:null,errorY:null},formulas:[null,null,'[@x]^2+[@y]^2']});assert.deepEqual(three.rows,[[1,2,5],[3,4,25]]);
console.log('calculation-core.test.cjs: ok');
