const assert=require('assert');
global.GraphExpression=require('../expression.js');
const C=require('../calculations.js');
let out=C.evaluate({columns:['x','y','z'],rows:[[1,2,9],[3,null,9],[5,6,9]],formulas:[null,'[@x]*2','AVERAGE([x])+[@y]']});
assert.deepStrictEqual(out.rows,[[1,2,5],[3,6,9],[5,10,13]]);assert.deepStrictEqual(out.errors,[]);
const source={columns:['x','z'],rows:[[1,99],[null,99]],formulas:[null,'sqrt([@x])']};out=C.evaluate(source);assert.equal(out.rows[1][1],null);assert.deepStrictEqual(out.errors,[]);assert.deepStrictEqual(source.rows,[[1,99],[null,99]]);
out=C.evaluate({columns:['x','z'],rows:[[1,0],[0,0]],formulas:[null,'1/[@x]']});assert.equal(out.rows[0][1],1);assert.equal(out.rows[1][1],null);assert.match(out.errors[0].message,/定義/);
out=C.evaluate({columns:['x','z'],rows:[[null,0]],formulas:[null,'SUM([x])']});assert.equal(out.rows[0][1],0);
out=C.evaluate({columns:['x','z'],rows:[[null,0]],formulas:[null,'COUNT([x])']});assert.equal(out.rows[0][1],0);
out=C.evaluate({columns:['x','z'],rows:[[null,0]],formulas:[null,'AVERAGE([x])']});assert.match(out.errors[0].message,/数値/);
out=C.evaluate({columns:['x','z'],rows:[[1,0]],formulas:[null,'STDEV.S([x])']});assert.match(out.errors[0].message,/2個/);
out=C.evaluate({columns:['x','sum','avg','min','max','count','pop','sample'],rows:[[1,0,0,0,0,0,0,0],[2,0,0,0,0,0,0,0],[3,0,0,0,0,0,0,0]],formulas:[null,'SUM([x])','AVERAGE([x])','MIN([x])','MAX([x])','COUNT([x])','STDEV.P([x])','STDEV.S([x])']});assert.deepStrictEqual(out.rows[0].slice(1),[6,2,1,3,3,Math.sqrt(2/3),1]);
out=C.evaluate({columns:['x','a','b'],rows:[[4,0,0]],formulas:[null,'[@x]*2','[@a]+1']});assert.deepStrictEqual(out.rows[0],[4,8,9]);
assert.throws(()=>C.evaluate({columns:['a','b'],rows:[[1,2]],formulas:['[@b]','[@a]']}),/循環/);
assert.throws(()=>C.evaluate({columns:['a'],rows:[[1]],formulas:['[@a]']}),/自分自身/);
assert.throws(()=>C.evaluate({columns:['a','a','z'],rows:[[1,2,3]],formulas:[null,null,'[@a]']}),/重複/);
assert.throws(()=>C.evaluate({columns:['date','z'],columnTypes:['date','number'],rows:[['2026-01-01',0]],formulas:[null,'[@date]']}),/数値/);
assert.equal(C.reference('a]b'), '["a]b"]');assert.equal(C.reference('a]b',true), '[@"a]b"]');
assert.equal(C.renameReferences('[@x]+["a]b"]','a]b','new'), '[@x]+[new]');
out=C.evaluate({columns:['a]b','z'],rows:[[2,0]],formulas:[null,'[@"a]b"]^2']});assert.equal(out.rows[0][1],4);
out=C.evaluate({columns:['x','z'],rows:[[1e-9,0],[2e-9,0],[3e-9,0]],formulas:[null,'STDEV.P([x])']});assert.ok(Math.abs(out.rows[0][1]-Math.sqrt(2/3)*1e-9)<1e-20);
out=C.evaluate({columns:['x','z'],rows:[[1e9,0],[1e-8,0],[-1e9,0]],formulas:[null,'SUM([x])']});assert.ok(Math.abs(out.rows[0][1]-1e-8)<1e-20);
out=C.evaluate({columns:['n','ratio'],rows:Array.from({length:10},()=>[1e9,0]),formulas:[null,'[@n]/SUM([n])*100']});assert.equal(out.rows[0][1],10);
out=C.evaluate({columns:['x','bad','next'],rows:[[0,0,0],[2,0,0]],formulas:[null,'1/[@x]','[@bad]+1']});assert.equal(out.rows[0][2],null);assert.equal(out.rows[1][2],1.5);assert.equal(out.errors.filter(e=>e.row===0).length,2);
out=C.evaluate({columns:['x','bad','next'],rows:[[null,0,0]],formulas:[null,'1/0','[@x]+[@bad]']});assert.equal(out.errors.length,2);assert.match(out.errors[1].message,/参照先/);
assert.throws(()=>C.evaluate({columns:['x','z'],rows:[[1,0]],formulas:[null,'vref0+1']}),/内部/);
assert.throws(()=>C.evaluate({columns:['x','z'],rows:[[1,0]],formulas:[null,'[x]']}),/集計関数/);
assert.throws(()=>C.evaluate({columns:['x','z'],rows:[[1,0]],formulas:[null,'[@unknown]']}),/不明/);
assert.throws(()=>C.evaluate({columns:['x','z'],rows:[[1,0]],formulas:[null,'y=[@x]']}),/等号/);
const complex=Array.from({length:120},()=> '[@c0]').join('+');
assert.throws(()=>C.evaluate({columns:Array.from({length:20},(_,i)=>'c'+i),rows:Array.from({length:10000},()=>Array(20).fill(1)),formulas:[null,...Array.from({length:19},()=>complex)]}),/計算量/);
out=C.evaluate({columns:['derived','later','raw'],rows:[[null,null,4]],formulas:['[@later]+1','[@raw]*2',null]});assert.deepStrictEqual(out.rows,[[9,8,4]],'later columns are evaluated before their dependants');
out=C.evaluate({columns:['x','failed','aggregate'],rows:[[0,null,null],[2,null,null]],formulas:[null,'1/[@x]','SUM([failed])']});assert.equal(out.rows[1][2],null);assert.match(out.errors.find(error=>error.row===1&&error.column===2).message,/参照先/);
out=C.evaluate({columns:['x','copy','aggregate'],rows:[[null,null,null],[2,null,null]],formulas:[null,'[@x]*2','SUM([copy])']});assert.deepStrictEqual(out.rows,[[null,null,4],[2,4,4]]);assert.deepStrictEqual(out.errors,[]);
out=C.evaluate({columns:['vref0','copy'],rows:[[2,null]],formulas:[null,'[@vref0]+1']});assert.equal(out.rows[0][1],3);
out=C.evaluate({columns:['x','s'],rows:[[1,null]],formulas:[null,'STDEV.P([x])']});assert.equal(out.rows[0][1],0);
out=C.evaluate({columns:['x','s'],rows:[[1e9,null]],formulas:[null,'[@x]*2']});assert.equal(out.rows[0][1],null);assert.match(out.errors[0].message,/範囲/);
out=C.evaluate({columns:['x','s'],rows:[[-1,null]],formulas:[null,'sqrt([@x])']});assert.equal(out.rows[0][1],null);assert.match(out.errors[0].message,/定義/);
out=C.evaluate({columns:['x','s'],rows:[[2,null]],formulas:[null,'aVeRaGe([x])+SQRT([@x]^2)']});assert.equal(out.rows[0][1],4);
assert.throws(()=>C.evaluate({columns:['place','value'],columnTypes:['category','number'],rows:[['Tokyo',null]],formulas:[null,'COUNT([place])']}),/数値/);
assert.throws(()=>C.evaluate({columns:['x','value'],rows:[[1,null]],formulas:[null,'SUM([@x])']}),/列全体/);
assert.deepStrictEqual(C.evaluate({columns:['x','value'],rows:[],formulas:[null,'AVERAGE([x])']}),{rows:[],errors:[]});
console.log('calculations tests passed');
