/* Calculated columns through the actual table UI and saved graph documents. */
const assert=require('node:assert/strict');
const fs=require('node:fs'),http=require('node:http'),path=require('node:path'),os=require('node:os');
const C=require('../core.js'),T=require('../tables.js');
const Toolbar=require('./toolbar-helpers.cjs');
let chromium;
try{({chromium}=require('playwright'));}catch{({chromium}=require(path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')));}
const root=path.resolve(__dirname,'../../..');
const server=http.createServer((req,res)=>{
  const file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));
  if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}
  fs.readFile(file,(error,data)=>{res.writeHead(error?404:200,{'Content-Type':file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.svg')?'image/svg+xml':file.endsWith('.png')?'image/png':'text/html'});res.end(error?'not found':data);});
});
let browser,page;
(async()=>{
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  browser=await chromium.launch({channel:'chrome',headless:true});
  page=await browser.newPage({viewport:{width:1280,height:950},hasTouch:true});page.setDefaultTimeout(10000);
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(process.env.GRAPH_TEST_URL||'http://127.0.0.1:'+server.address().port+'/tools/graph/index.html');
  const settle=()=>page.waitForFunction(()=>window.GraphEditor&&!GraphEditor.getState().drawing);
  const doc=()=>page.evaluate(()=>GraphEditor.getDocument());
  const load=async value=>{await page.locator('#file-input').setInputFiles({name:'calculated.graph.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(value))});await settle();};
  const submit=async()=>{await page.locator('#dialog-submit').click();await page.waitForFunction(()=>!document.querySelector('#editor-dialog').open&&!GraphEditor.getState().drawing);};
  const item=()=>page.locator('[data-object-type="series"][data-object-id="calculated"]');
  const editor=page.locator('.graph-table-editor'),cell=(r,c)=>editor.locator('[data-cell="'+r+','+(c-1)+'"]');
  const editCell=async(r,c,value)=>{const target=cell(r,c);await target.click();await target.press('F2');await target.fill(value);await target.press('Tab');};
  const addCalculation=async()=>{await editor.locator('.graph-table-editor__column-menu summary').click();await editor.getByRole('button',{name:'計算列を追加',exact:true}).click();};
  const apply=()=>editor.getByRole('button',{name:'適用',exact:true}).click();
  async function open(){await item().dblclick();await editor.waitFor();}
  await settle();
  const initial=C.createDocument();initial.name='計算列の動作確認';
  const series=C.createSeries('data2d');series.id='calculated';series.name='観測値';
  T.assign(series,{columns:['時刻','温度'],rows:[[1,10],[2,20],[3,30]],mapping:{x:0,y:1,z:null,errorX:null,errorY:null}});
  initial.series=[series];await load(initial);await open();
  await addCalculation();
  await editor.getByLabel('計算列の名前',{exact:true}).fill('偏差');
  const formula=editor.getByLabel('計算式',{exact:true});
  await editor.getByLabel('列を式へ挿入',{exact:true}).selectOption('row:1');assert.equal(await formula.inputValue(),'[@温度]');
  await formula.fill('[@温度] - ');await formula.press('End');
  await editor.getByLabel('関数を式へ挿入',{exact:true}).selectOption('AVERAGE');
  await editor.getByLabel('列を式へ挿入',{exact:true}).selectOption('all:1');
  assert.equal(await formula.inputValue(),'[@温度] - AVERAGE([温度])');
  assert.match(await editor.locator('.graph-table-editor__calculation-preview').innerText(),/1行目: -10/);await apply();
  assert.equal(await cell(1,3).inputValue(),'-10');assert.equal(await cell(1,3).getAttribute('readonly'),'');
  await editCell(1,2,'11');
  assert(await cell(1,3).evaluate(el=>el===document.activeElement),'updating derived values preserves normal Tab focus');
  assert(Math.abs(Number(await cell(1,3).inputValue())-(-28/3))<1e-6);
  await editor.getByLabel('2列目の名前',{exact:true}).fill('気温');await editor.getByLabel('2列目の名前',{exact:true}).press('Tab');
  await editor.getByRole('button',{name:'偏差の式を編集',exact:true}).click();assert.equal(await formula.inputValue(),'[@気温] - AVERAGE([気温])');
  await formula.fill('[@不明な列]');await apply();assert(await formula.isVisible());assert.equal(await formula.inputValue(),'[@不明な列]');
  assert.match(await editor.locator('.graph-table-editor__status').innerText(),/不明/);
  await editor.getByRole('button',{name:'行を追加',exact:true}).click();assert.equal(await formula.inputValue(),'[@不明な列]','other table actions preserve the draft formula');
  await page.locator('#dialog-submit').click();assert.match(await page.locator('#dialog-error').innerText(),/未適用/);assert.equal((await doc()).series[0].dataTable.formulas,undefined);
  await editor.getByRole('button',{name:'取消',exact:true}).click();
  await editor.getByLabel('縦軸の列',{exact:true}).selectOption('2');
  await editor.getByLabel('1行目を回帰に使用',{exact:true}).uncheck();
  assert(Math.abs(Number(await cell(1,3).inputValue())-(-28/3))<1e-6,'aggregate includes regression-excluded rows');
  await submit();const saved=await doc();assert.equal(saved.version,15);assert.equal(saved.series[0].dataTable.formulas[2],'[@気温] - AVERAGE([気温])');
  assert.equal(saved.series[0].dataTable.rows[0][1],11);assert.equal(saved.series[0].rows[0][1],11-61/3);assert.equal(saved.series[0].dataTable.rows[3][2],null);
  await page.locator('#undo').click();await settle();assert.equal((await doc()).series[0].dataTable.formulas,undefined);
  await page.locator('#redo').click();await settle();assert.deepEqual(await doc(),saved);
  await page.locator('#file-menu summary').click();await page.locator('#save-browser').click();
  assert.deepEqual(await page.evaluate(()=>new GraphDocumentStore.Store(localStorage).load(GraphEditor.getState().tabId,'saved').document),saved);
  await load(C.createDocument());await load(saved);assert.deepEqual(await doc(),saved);
  await open();
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'数値をCSVで保存',exact:true}).click();
  const csv=fs.readFileSync(await (await download).path(),'utf8');assert(!csv.includes('AVERAGE'));assert(csv.includes(String(11-61/3)));assert(csv.includes('気温'));
  await editor.getByRole('button',{name:'偏差の式を編集',exact:true}).click();
  await editor.getByLabel('計算列の名前',{exact:true}).fill('逆数');await formula.fill('1/[@気温]');await apply();
  await editCell(1,2,'0');assert.equal(await cell(1,3).inputValue(),'エラー');assert.match(await cell(1,3).getAttribute('title'),/定義/);
  await editCell(2,2,'');assert.equal(await cell(2,3).inputValue(),'');assert.equal(await cell(2,3).getAttribute('aria-invalid'),'false');
  await editCell(1,2,'3');assert.equal(await cell(1,3).inputValue(),'0.33333333');assert.equal(await cell(1,3).getAttribute('aria-invalid'),'false');
  await editCell(1,2,'0');await submit();
  assert.equal((await doc()).series[0].rows[0][1],null);assert.equal((await doc()).series[0].dataTable.formulas[2],'1/[@気温]');
  assert.match(await page.locator('#plot-notes').innerText(),/計算列/);
  // A source at the end of a table cannot be deleted while another column uses it.
  const dependent=C.clone(saved),dt=dependent.series[0].dataTable;
  dt.columns.push('補正');dt.rows.forEach(row=>row.push(1));dt.formulas.push(null);dt.formulas[2]='[@気温]+[@補正]';
  dependent.series[0].rows=T.project(dt).rows;await load(dependent);await open();
  await editor.locator('.graph-table-editor__column-menu summary').click();await editor.getByRole('button',{name:'最後の列を削除',exact:true}).click();assert.match(await editor.locator('.graph-table-editor__status').innerText(),/不明/);assert.equal(await editor.locator('thead th').count(),6);
  await editor.getByRole('button',{name:'偏差の式を編集',exact:true}).click();await formula.fill('[@気温] / SUM([気温]) * 100');
  assert(await page.locator('#dialog-submit').evaluate(el=>el.getBoundingClientRect().bottom<=innerHeight));
  await page.screenshot({path:'/private/tmp/graph-calculated-desktop.png'});
  await editor.getByRole('button',{name:'取消',exact:true}).click();await page.locator('#dialog-cancel').click();
  await Toolbar.openSettings(page);await page.locator('[data-theme-value="dark"]').click();await page.locator('#text-size').selectOption('largest');await page.keyboard.press('Escape');
  await page.setViewportSize({width:390,height:850});await page.locator('#list-toggle').tap();await item().tap();
  await page.locator('#selection-toolbar').getByRole('button',{name:'数表・出典',exact:true}).tap();await editor.waitFor();
  await editor.locator('.graph-table-editor__column-menu summary').tap();await editor.getByRole('button',{name:'計算列を追加',exact:true}).tap();await formula.fill('[@気温] / SUM([気温]) * 100');
  assert(await page.locator('body').evaluate(el=>el.scrollWidth<=innerWidth));
  assert(await page.locator('#editor-dialog').evaluate(el=>el.scrollWidth<=el.clientWidth+1));
  await editor.getByRole('button',{name:'適用',exact:true}).scrollIntoViewIfNeeded();
  assert(await page.locator('#dialog-submit').evaluate(el=>el.getBoundingClientRect().bottom<=innerHeight));
  assert(await page.locator('#dialog-submit').evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));}),'sticky table headers must not cover the submit button');
  await page.screenshot({path:'/private/tmp/graph-calculated-mobile.png'});
  assert.deepEqual(errors,[]);console.log('calculation-table-browser.test.cjs: ok');
})().catch(async error=>{if(page)await page.screenshot({path:'/private/tmp/graph-calculated-failure.png'}).catch(()=>{});console.error(error);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));});
