const assert=require('assert');
const Charts=require('../charts.js'),S=require('../statistics.js');
const near=(a,b,t=1e-10)=>assert(Math.abs(a-b)<=t,`${a} is not near ${b}`);
const doc={series:[{id:'s',kind:'data2d',name:'<data>',rows:[[1,2],[2,4],[3,6],[4,null],[null,9]],errorBars:{x:[],y:[]},dataTable:{columns:['x<','y&','z'],rows:[[1,2,1],[2,4,2],[3,6,3],[4,null,4],[null,9,5]],mapping:{x:0,y:1,z:null,errorX:null,errorY:null}}}],annotations:[{id:'r',kind:'regression',seriesId:'s',model:'linear'}]};
let d=S.describe([1,2,3,4,5]);assert.equal(d.q1,1.5);assert.equal(d.q3,4.5);assert.equal(d.iqr,3);
d=S.describe([1,2,3,4]);assert.equal(d.q1,1.5);assert.equal(d.q3,3.5);d=S.describe([8]);assert.equal(d.q1,8);assert.equal(d.q3,8);d=S.describe([null]);assert.equal(d.q1,null);
let c={...Charts.create('scatter',{seriesId:'s',xColumn:0,yColumn:1,model:'linear'}),id:'sc'};assert.equal(c.color,'#2563eb');assert.deepStrictEqual(Charts.defaultView().style,{pointSize:8,width:2,dash:'solid'});assert.notEqual(Charts.create('scatter',{id:'sc'}).id,'sc');assert.equal(Charts.validate([c],doc)[0].id,'sc');assert.throws(()=>Charts.validate([{...c,id:'s'}],doc));assert.throws(()=>Charts.validate([{...c,id:'main'}],doc));assert.throws(()=>Charts.validate([{...c,color:'blue'}],doc));assert.throws(()=>Charts.validate([{...c,xColumn:9}],doc));assert.throws(()=>Charts.validate([{...c,axes:{x:{min:0,max:null}}}],doc));assert.throws(()=>Charts.validate([{...c,style:{pointSize:1}}],doc));
assert.equal(c.visible,true);assert.equal(Charts.create('scatter',{visible:undefined}).visible,true);assert.equal(Charts.validate([{...c,visible:undefined}],doc)[0].visible,true);assert.throws(()=>Charts.validate([{...c,visible:'false'}],doc),/表示設定/);
let output=Charts.build(c,doc);assert.equal(output.data[0].x.length,3);assert.equal(output.data.length,2);assert.match(output.layout.xaxis.title.text,/&lt;/);assert.match(output.summary,/R²/);
output=Charts.build({...c,visible:false},doc);assert.deepStrictEqual(output.data,[]);assert.match(output.warnings[0],/非表示/);
output=Charts.build(c,doc,{selectedRow:{seriesId:'s',rowIndex:1}});assert(output.data.some(t=>t.meta&&t.meta.observationHighlight));assert(output.data.find(t=>t.meta&&t.meta.observationHighlight).customdata[0][0]===2);
const styled={...c,axes:{x:{...c.axes.x,style:{color:'#dc2626',width:3,grid:false,gridColor:'#111827',gridWidth:2,gridDash:'dot',tickMarks:false,tickLabels:false,ignored:true}},y:{...c.axes.y,style:{color:null,width:2,grid:true,gridColor:null,gridWidth:1,gridDash:'dash',tickMarks:true,tickLabels:true}}}};
const normalizedStyled=Charts.validate([styled],doc)[0];assert.equal(normalizedStyled.axes.x.style.color,'#dc2626');assert.equal(normalizedStyled.axes.x.style.width,3);assert.equal(normalizedStyled.axes.y.style.color,null);assert.equal(normalizedStyled.axes.x.style.ignored,undefined);assert.equal(Charts.validate([{...c,axes:{...c.axes,x:{...c.axes.x,style:{}}}}],doc)[0].axes.x.style,undefined);assert.throws(()=>Charts.validate([{...c,axes:{...c.axes,x:{...c.axes.x,style:{width:.4}}}}],doc),/軸の書式/);assert.throws(()=>Charts.validate([{...c,axes:{...c.axes,x:{...c.axes.x,style:{color:'blue'}}}}],doc),/軸の書式/);
output=Charts.build(styled,doc);assert.equal(output.layout.xaxis.color,'#dc2626');assert.equal(output.layout.xaxis.linewidth,3);assert.equal(output.layout.xaxis.showline,true);assert.equal(output.layout.xaxis.tickfont.color,'#dc2626');assert.equal(output.layout.xaxis.title.font.color,'#dc2626');assert.equal(output.layout.xaxis.showgrid,false);assert.equal(output.layout.xaxis.gridcolor,'#111827');assert.equal(output.layout.xaxis.griddash,'dot');assert.equal(output.layout.xaxis.ticks,'');assert.equal(output.layout.xaxis.showticklabels,false);assert.equal(output.layout.yaxis.color,'#1f2937');assert.equal(output.layout.yaxis.gridcolor,'#d1d5db');
const edited={...doc,series:[{...doc.series[0],dataTable:{...doc.series[0].dataTable,rows:[[1,20,1],[2,40,2],[3,60,3],[4,null,4],[null,90,5]]}}]};assert.deepStrictEqual(Charts.build(c,edited).data[0].y,[20,40,60]);
c={...Charts.create('residual',{regressionId:'r',horizontal:'x'}),id:'res'};const axesDoc={...doc,axes:{x:{symbol:'t',label:'時間',unit:'s'},y:{symbol:'v',label:'速度',unit:'m/s'}}};output=Charts.build(c,axesDoc,{dark:true});assert.deepStrictEqual(output.data[0].x,[1,2,3]);assert.deepStrictEqual(output.data[0].customdata.map(row=>row[0]),[1,2,3]);near(output.data[0].y[1],0);assert.match(output.layout.xaxis.title.text,/時間/);assert.match(output.layout.yaxis.title.text,/速度/);assert.equal(output.layout.xaxis.gridcolor,'#374151');
c={...c,horizontal:'predicted'};output=Charts.build(c,doc);assert.deepStrictEqual(output.data[0].x,[2,4,6]);
c={...Charts.create('histogram',{seriesId:'s',column:2,bins:2}),id:'h'};output=Charts.build(c,doc);assert.deepStrictEqual(output.data[0].y,[2,3]);assert.match(output.summary,/\[3, 5\]/); // the maximum belongs to the final interval
c={...c,bins:null};output=Charts.build(c,doc);assert.equal(output.data[0].y.reduce((a,b)=>a+b,0),5);
const constant={...doc,series:[{...doc.series[0],dataTable:{...doc.series[0].dataTable,rows:[[1,2,7],[2,4,7]]}}]};output=Charts.build(c,constant);assert.deepStrictEqual(output.data[0].y,[2]);
const decimal={...doc,series:[{...doc.series[0],dataTable:{...doc.series[0].dataTable,rows:[[1,2,0],[2,4,.1],[3,6,.2],[4,8,.3]],mapping:{x:0,y:1,z:null,errorX:null,errorY:null}}}]};output=Charts.build({...c,bins:3},decimal);assert.deepStrictEqual(output.data[0].y,[1,1,2]);assert.match(output.data[0].customdata[0][0],/0\.1/);
const tiny={...doc,series:[{...doc.series[0],dataTable:{...doc.series[0].dataTable,rows:[[1,2,Number.MIN_VALUE],[2,4,Number.MIN_VALUE*2]],mapping:{x:0,y:1,z:null,errorX:null,errorY:null}}}]};output=Charts.build({...c,bins:100},tiny);assert.equal(output.data[0].y.reduce((a,b)=>a+b,0),2);assert(output.data[0].y.every(Number.isFinite));
const matrix={...Charts.create('matrix',{seriesId:'s',columns:[0,1]}),id:'m',axes:{x:{...Charts.create('matrix').axes.x,style:{color:'#7c3aed',grid:false}},y:{...Charts.create('matrix').axes.y,style:{color:'#0891b2',gridColor:'#94a3b8',gridDash:'dash'}}}};
output=Charts.build(matrix,doc);for(const key of ['xaxis','xaxis2','xaxis3','xaxis4']){assert.equal(output.layout[key].color,'#7c3aed');assert.equal(output.layout[key].showgrid,false);assert.equal(output.layout[key].showline,true);assert.equal(output.layout[key].tickfont.color,'#7c3aed');if(output.layout[key].title)assert.equal(output.layout[key].title.font.color,'#7c3aed');}for(const key of ['yaxis','yaxis2','yaxis3','yaxis4']){assert.equal(output.layout[key].color,'#0891b2');assert.equal(output.layout[key].gridcolor,'#94a3b8');assert.equal(output.layout[key].griddash,'dash');assert.equal(output.layout[key].showline,true);assert.equal(output.layout[key].tickfont.color,'#0891b2');if(output.layout[key].title)assert.equal(output.layout[key].title.font.color,'#0891b2');}
c={...Charts.create('box',{seriesId:'s',columns:[0,1]}),id:'b'};output=Charts.build(c,doc);assert.equal(output.data.length,2);assert.deepStrictEqual(output.data[0].q1,[1.5]);assert.deepStrictEqual(output.data[0].lowerfence,[1]);assert.match(output.summary,/中央値を奇数個では除き/);
const missing={...doc,series:[{...doc.series[0],dataTable:{...doc.series[0].dataTable,columns:['x'],rows:[[1]],mapping:{x:0,y:0,z:null,errorX:null,errorY:null}}}]};output=Charts.build(c,missing);assert.match(output.warnings[0],/列/);
const fewerColumns={...doc,series:[{...doc.series[0],dataTable:{...doc.series[0].dataTable,columns:['x','y'],rows:[[1,2]],mapping:{x:0,y:1,z:null,errorX:null,errorY:null}}}]};assert.throws(()=>Charts.validate([{...c,columns:[2]}],fewerColumns),/列/);
assert.deepStrictEqual(Charts.prune([c,{id:'gone',kind:'residual',name:'',color:'#2563eb',regressionId:'gone',horizontal:'x'}],doc),[c]);
console.log('graph charts tests passed');
