/* Chrome integration: saved chart presentation and reversible observation selection. */
const assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path'),os=require('node:os');
const C=require('../core.js'),T=require('../tables.js'),Charts=require('../charts.js');
let chromium;try{({chromium}=require('playwright'));}catch{({chromium}=require(path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')));}
const root=path.resolve(__dirname,'../../..');
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(file,(error,data)=>{res.writeHead(error?404:200,{'Content-Type':file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.svg')?'image/svg+xml':'text/html'});res.end(error?'not found':data);});});
let browser,page;
(async()=>{
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));browser=await chromium.launch({channel:'chrome',headless:true});
  const context=await browser.newContext({viewport:{width:1320,height:950},hasTouch:true,acceptDownloads:true});
  await context.addInitScript(()=>Object.defineProperty(window,'showSaveFilePicker',{value:undefined,configurable:true}));page=await context.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));
  const dialog=page.locator('#editor-dialog'),settle=()=>page.waitForFunction(()=>window.GraphEditor&&!GraphEditor.getState().drawing),doc=()=>page.evaluate(()=>GraphEditor.getDocument());
  const importDoc=async value=>{await page.locator('#file-input').setInputFiles({name:'linked.graph.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(value))});await page.waitForFunction(name=>GraphEditor.getDocument().name===name,value.name);await settle();};
  const submit=async()=>{await page.locator('#dialog-submit').click();await dialog.waitFor({state:'hidden'});await settle();};
  const detail=async(type,id)=>{await page.locator('[data-object-id="'+id+'"]').click();await page.locator('#selection-toolbar').getByRole('button',{name:type==='chart'?'分析グラフの設定':'数表・出典',exact:true}).click();await dialog.waitFor({state:'visible'});};
  const clickCoordinate=async(selector,xy)=>{const screen=await page.locator(selector).evaluate((plot,point)=>GraphPlot.screenPoint(plot,point),xy);assert(screen?.every(Number.isFinite));await page.mouse.click(...screen);await page.waitForTimeout(90);await settle();};
  const state=()=>page.evaluate(()=>GraphEditor.getState());
  await page.goto(process.env.GRAPH_TEST_URL||'http://127.0.0.1:'+server.address().port+'/tools/graph/index.html');await settle();
  const fixture=C.createDocument();fixture.name='行と分析グラフの連動';fixture.axes.x.min=-1;fixture.axes.x.max=6;fixture.axes.y.min=-2;fixture.axes.y.max=25;
  const series=C.createSeries('data2d');series.id='measure';series.name='実験の記録';series.style.points=true;series.style.lines=false;
  T.assign(series,{columns:['時刻','測定値','温度'],rows:[[0,1,10],[1,3,12],[2,null,14],[3,7,16],[4,20,null],[5,11,20]],mapping:{x:0,y:1,z:null,errorX:null,errorY:null}});fixture.series=[series];
  const regression=C.createAnnotation('regression');regression.id='fit';regression.name='実験の回帰';regression.seriesId=series.id;regression.model='linear';fixture.annotations=[regression];
  const scatter=Charts.create('scatter',{seriesId:series.id,name:'測定値の散布図',model:'linear'});scatter.id='scatter';
  const residual=Charts.create('residual',{regressionId:regression.id,name:'残差'});residual.id='residual';
  const second=Charts.create('scatter',{seriesId:series.id,name:'温度と時刻',xColumn:2,yColumn:0});second.id='temperature';fixture.charts=[scatter,residual,second];fixture.comparison={columns:2,items:['main',scatter.id,residual.id,second.id]};
  fixture.axes=C.validateDocument(fixture).axes;
  await importDoc(fixture);assert.deepEqual((await doc()).axes,fixture.axes);assert.deepEqual(await page.locator('#plot').evaluate(plot=>[plot._fullLayout.xaxis.range,plot._fullLayout.yaxis.range]),[[-1,6],[-2,25]],'Imported ranges must be rendered');

  // Presentation is owned by each chart; invalid ranges do not change the document.
  await detail('chart',scatter.id);await dialog.getByRole('tab',{name:'軸',exact:true}).click();
  await dialog.getByLabel('横軸の名前',{exact:true}).fill('経過時間');await dialog.getByLabel('横軸の単位',{exact:true}).fill('s');
  await dialog.getByLabel('横軸の最小値',{exact:true}).fill('-1');await dialog.getByLabel('横軸の最大値',{exact:true}).fill('6');await dialog.getByLabel('横軸の目盛り間隔',{exact:true}).fill('.5');await dialog.getByLabel('横軸の目盛り表記',{exact:true}).selectOption('fraction');
  await dialog.getByLabel('縦軸の名前',{exact:true}).fill('位置');await dialog.getByLabel('縦軸の単位',{exact:true}).fill('m');await dialog.getByLabel('縦軸の最小値',{exact:true}).fill('-2');await dialog.getByLabel('縦軸の最大値',{exact:true}).fill('25');
  await dialog.getByRole('tab',{name:'書式',exact:true}).click();await dialog.getByLabel('点の大きさ',{exact:true}).fill('12');await dialog.getByLabel('線の太さ',{exact:true}).fill('3');await dialog.getByLabel('線種',{exact:true}).selectOption('dash');await dialog.getByLabel('回帰式を図に表示',{exact:true}).check();await dialog.getByLabel('統計指標を図に表示（n・r・R²・RMSE）',{exact:true}).check();await submit();
  let chart=(await doc()).charts[0];assert.deepEqual(chart.axes.x,{label:'経過時間',unit:'s',min:-1,max:6,step:.5,format:'fraction'});assert.deepEqual(chart.style,{pointSize:12,width:3,dash:'dash'});
  let layout=await page.locator('#analysis-plot').evaluate(plot=>({axis:plot._fullLayout.xaxis,annotations:plot.layout.annotations}));assert.equal(layout.axis.title.text,'経過時間 [s]');assert.deepEqual(layout.axis.range,[-1,6]);assert(layout.axis.ticktext.some(text=>text.includes('/')));assert(layout.annotations.some(a=>a.text.includes('R²')&&a.text.includes('n=')));
  const before=await doc();await detail('chart',scatter.id);await dialog.getByRole('tab',{name:'軸',exact:true}).click();await dialog.getByLabel('横軸の最大値',{exact:true}).fill('-3');await page.locator('#dialog-submit').click();assert(await page.locator('#dialog-error').isVisible());assert.deepEqual(await doc(),before);await page.keyboard.press('Escape');
  await page.locator('#analysis-plot').evaluate(plot=>Plotly.relayout(plot,{'xaxis.range':[0,2],'yaxis.range':[0,5]}));await page.locator('#fit-button').click();await settle();assert.deepEqual(await page.locator('#analysis-plot').evaluate(plot=>plot._fullLayout.xaxis.range),[-1,6]);
  // A duplicate preserves the same data reference and presentation with a new ID.
  await page.locator('[data-object-details="chart:'+scatter.id+'"]').click();await page.locator('#object-menu').getByRole('menuitem',{name:'複製',exact:true}).click();await settle();let copied=(await doc()).charts.find(candidate=>candidate.id!==scatter.id&&candidate.name===scatter.name+' のコピー');assert(copied);assert.equal(copied.seriesId,series.id);assert.deepEqual(copied.axes,chart.axes);assert.deepEqual(copied.labels,chart.labels);
  // Quick controls preserve focus, support the extended palette, and have undo history.
  await page.locator('[data-quick-control="chart-point-size"]').fill('15');await page.locator('[data-quick-control="chart-point-size"]').press('Tab');await settle();assert.equal((await doc()).charts.find(candidate=>candidate.id===copied.id).style.pointSize,15);
  await page.locator('[data-quick-control="custom-color"]').click();await dialog.getByLabel('R',{exact:true}).fill('8');await dialog.getByLabel('G',{exact:true}).fill('145');await dialog.getByLabel('B',{exact:true}).fill('178');await submit();assert.equal((await doc()).charts.find(candidate=>candidate.id===copied.id).color,'#0891b2');await page.locator('#undo').click();await settle();assert.equal((await doc()).charts.find(candidate=>candidate.id===copied.id).color,copied.color);

  // Selecting a point keeps its original row number despite missing pairs.
  await page.locator('#workspace-view').selectOption(scatter.id);await page.keyboard.press('Escape');await settle();await clickCoordinate('#analysis-plot',[4,20]);assert.deepEqual((await state()).observedSelection,{seriesId:series.id,rowIndex:4});assert.equal((await state()).selected.type,'row');assert.match(await page.locator('.observation-values').innerText(),/欠測/);
  await page.locator('[data-quick-control="row-regression"]').click();await settle();let current=await doc();assert.deepEqual(current.series[0].excludedRows,[4]);assert.deepEqual(current.series[0].dataTable.rows,series.dataTable.rows);
  let fitted=await page.evaluate(()=>GraphAnalysis.fit(GraphEditor.getDocument().series[0],'linear'));assert.equal(fitted.n,4);assert.equal(fitted.skipped,1);assert.equal(fitted.excluded,1);assert.deepEqual(fitted.residuals.map(row=>row[0]),[1,2,4,6]);
  assert.match(await page.locator('#analysis-summary').innerText(),/除外/);assert.equal(await page.locator('#analysis-plot').evaluate(plot=>plot.data.filter(trace=>trace.meta?.dataRows&&!trace.meta.observationHighlight).flatMap(trace=>trace.customdata).length),5);
  // Source editing cancels safely, then returns to the chart and selected row.
  await page.locator('[aria-label="この行を数表で編集"]').click();await dialog.waitFor({state:'visible'});assert.equal(await dialog.locator('.graph-table-editor__focused-row').getByLabel('5行2列',{exact:true}).inputValue(),'20');
  await dialog.getByLabel('5行目を回帰に使用',{exact:true}).check();await page.locator('#dialog-cancel').click();assert.deepEqual((await doc()).series[0].excludedRows,[4]);
  await page.locator('[aria-label="この行を数表で編集"]').click();await dialog.getByLabel('5行2列',{exact:true}).fill('9');await submit();assert.equal((await state()).workspaceView,scatter.id);assert.equal((await doc()).series[0].rows[4][1],9);assert.deepEqual((await doc()).series[0].excludedRows,[4]);
  await page.locator('[data-quick-control="row-regression"]').click();await settle();assert.deepEqual((await doc()).series[0].excludedRows,[]);fitted=await page.evaluate(()=>GraphAnalysis.fit(GraphEditor.getDocument().series[0],'linear'));assert.equal(fitted.n,5);assert(Math.abs(fitted.r2-1)<1e-12);

  // Switching views keeps one transient observation; all matching panels highlight it.
  await page.locator('#workspace-view').selectOption('comparison');await settle();assert.equal((await state()).workspaceView,'comparison');
  let highlights=await page.locator('.comparison-plot').evaluateAll(plots=>plots.map(plot=>plot.data.filter(trace=>trace.meta?.observationHighlight).length));assert.deepEqual(highlights,[1,1,1,0,1],'The row missing temperature is highlighted only in compatible panels');
  await page.locator('#workspace-view').selectOption(residual.id);await page.keyboard.press('Escape');await settle();const residualPoint=await page.locator('#analysis-plot').evaluate(plot=>{const t=plot.data.find(trace=>trace.meta?.dataRows);const i=t.customdata.findIndex(row=>row[0]===4);return [t.x[i],t.y[i]];});await clickCoordinate('#analysis-plot',residualPoint);assert.equal((await state()).observedSelection.rowIndex,3);
  await page.locator('#workspace-view').selectOption('comparison');await settle();highlights=await page.locator('.comparison-plot').evaluateAll(plots=>plots.map(plot=>plot.data.filter(trace=>trace.meta?.observationHighlight).length));assert.deepEqual(highlights,[1,1,1,1,1]);
  await page.locator('#workspace-view').selectOption('main');await page.keyboard.press('Escape');await settle();assert.deepEqual((await doc()).axes,fixture.axes,'Analysis views must not overwrite main axes');await clickCoordinate('#plot',[1,3]);assert.equal((await state()).observedSelection.rowIndex,1);
  await page.locator('#stage').focus();await page.keyboard.press('Enter');await dialog.waitFor({state:'visible'});assert(await dialog.getByLabel('2行2列',{exact:true}).isVisible());await page.keyboard.press('Escape');
  await clickCoordinate('#plot',[5,-1]);assert.equal((await state()).observedSelection,null);

  // Rendering selection is transient, while masks/presentation round-trip in v10.
  await clickCoordinate('#plot',[1,3]);await page.locator('#workspace-view').selectOption(scatter.id);await settle();
  const exported=await page.evaluate(async()=>{const plot=document.querySelector('#analysis-plot'),original=Plotly.newPlot;let highlights=-1;Plotly.newPlot=async(...args)=>{highlights=args[1].filter(trace=>trace.meta?.observationHighlight).length;return original(...args);};try{const url=await GraphWorkspace.exportChart(plot,{format:'svg',width:800,height:600,margin:48,fontSize:16,scale:1,background:'white'});const svg=new DOMParser().parseFromString(decodeURIComponent(url.split(',').slice(1).join(',')),'image/svg+xml');return {highlights,text:svg.documentElement.textContent,url};}finally{Plotly.newPlot=original;}});assert.equal(exported.highlights,0);assert.match(exported.text,/R²/);assert.match(exported.text,/経過時間/);fs.writeFileSync('/private/tmp/graph-chart-linked.svg',decodeURIComponent(exported.url.split(',').slice(1).join(',')));
  await page.locator('#file-menu summary').click();const downloading=page.waitForEvent('download');await page.locator('#save-local').click();const saved=JSON.parse(fs.readFileSync(await (await downloading).path(),'utf8'));assert.equal(saved.version,14);assert(!('observedSelection' in saved));await importDoc({...C.createDocument(),name:'空の図'});await importDoc(saved);assert.deepEqual(await doc(),saved);assert.equal((await state()).observedSelection,null);assert.deepEqual(await page.locator('#plot').evaluate(plot=>[plot._fullLayout.xaxis.range,plot._fullLayout.yaxis.range]),[[saved.axes.x.min,saved.axes.x.max],[saved.axes.y.min,saved.axes.y.max]],'Reloaded ranges must be rendered');
  // Removing the selected last row must clear its transient reference before rebuilding the toolbar.
  await page.locator('#workspace-view').selectOption(scatter.id);await page.keyboard.press('Escape');await settle();await clickCoordinate('#analysis-plot',[5,11]);await page.locator('[aria-label="この行を数表で編集"]').click();await dialog.getByLabel('6行目を選択',{exact:true}).check();await dialog.getByRole('button',{name:'選択行を削除',exact:true}).click();await submit();assert.equal((await doc()).series[0].rows.length,5);assert.equal((await state()).observedSelection,null);
  const legacy=C.clone(saved);legacy.version=9;for(const axis of Object.values(legacy.axes)){delete axis.type;delete axis.categories;}legacy.name='v9から移行';for(const s of legacy.series)delete s.excludedRows;for(const c of legacy.charts)for(const field of ['axes','style','legend','labels'])delete c[field];await importDoc(legacy);assert.equal((await doc()).version,14);assert.deepEqual((await doc()).charts[0].axes,Charts.defaultView().axes);

  // Phone, dark theme, keyboard and touch retain reachable settings and no overflow.
  await importDoc({...saved,name:'狭い画面の確認'});await page.locator('#view-menu summary').click();await page.locator('#theme').selectOption('dark');await page.locator('#text-size').selectOption('largest');await page.keyboard.press('Escape');await page.setViewportSize({width:390,height:900});await settle();
  await page.locator('#workspace-view').selectOption(scatter.id);await settle();await page.locator('[data-quick-control="chart-color-9333ea"]').tap();await settle();assert.equal((await doc()).charts[0].color,'#9333ea');
  await page.screenshot({path:'/private/tmp/graph-chart-editing-mobile.png'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('[data-quick-control="edit-detail"]').click();await dialog.getByRole('tab',{name:'軸',exact:true}).click();assert(await dialog.getByLabel('横軸の名前',{exact:true}).isVisible());await page.keyboard.press('Escape');
  assert.deepEqual(errors,[]);console.log('chart-editing-link-browser.test.cjs: ok');
})().catch(async error=>{console.error(error);if(page)await page.screenshot({path:'/private/tmp/graph-chart-editing-failure.png'}).catch(()=>{});process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));});
