const assert = require('assert');
const E = require('../expression.js'), C = require('../core.js');
const T = require('../templates.js');
const near=(a,b)=>assert(Math.abs(a-b)<1e-10);
near(E.compile('2x+2(x+1)',{variables:['x']}).evaluate({x:3}),14);
near(E.compile('-x^2',{variables:['x']}).evaluate({x:3}),-9);
near(E.compile('2^3^2').evaluate({}),512);
near(E.compile('2^-2').evaluate({}),.25);
near(E.compile('max(2,min(3,-4),1)').evaluate({}),2);
near(E.compile('a(x+1)',{variables:['a','x']}).evaluate({a:3,x:2}),9);
near(E.compile('y = 2 x + 1',{variables:['x'],target:'y'}).evaluate({x:3}),7);
assert.throws(()=>E.compile('1.2.3'),/数値の間/);
assert.throws(()=>E.compile('2 3'),/数値の間/);
near(E.compile('sin(90)',{angle:'deg'}).evaluate({}),1);
near(E.compile('asin(1)',{angle:'deg'}).evaluate({}),90);
assert(Number.isNaN(E.compile('1/x',{variables:['x']}).evaluate({x:0})));
assert.throws(()=>E.compile('alert(1)'),/許可/);
near(E.compile('y=x+1',{variables:['x'],target:'y'}).evaluate({x:2}),3);
near(E.compile('z=x+y',{variables:['x','y'],target:'z'}).evaluate({x:2,y:3}),5);
assert.throws(()=>E.compile('z=x',{variables:['x'],target:'y'}),/左辺/);
assert.throws(()=>E.compile('constructor+1',{variables:['constructor']}),/変数名/);
const d=C.createDocument(); d.series.push(C.createSeries('function')); C.validateDocument(d);
for (const kind of ['function','surface','data2d','data3d']) { const doc=C.createDocument(); doc.series.push(C.createSeries(kind)); C.validateDocument(doc); }
for (const template of T.list()) C.validateDocument(template.document);
assert.throws(()=>C.validateDocument({...d,series:[d.series[0],{...d.series[0]}]}),/ID/);
assert.deepStrictEqual(C.parseTable('x,y\n1,\n2,3',2),[[1,null],[2,3]]);
assert.deepStrictEqual(C.parseTable('"x value","y,value"\n1,2',2),[[1,2]]);
assert.throws(()=>C.parseTable('1,a',2),/不正/);
assert.throws(()=>C.parseTable('"1"garbage,2',2),/引用符/);
assert.throws(()=>C.parseTable('1e,2',2),/不正/);
const mem=new Map(), store={getItem:k=>mem.has(k)?mem.get(k):null,setItem:(k,v)=>mem.set(k,v)}; const s=new C.Store(store);s.save('auto',d);assert.equal(s.list()[0].kind,'auto');
const h=new C.History(d);h.change(x=>x.name='変更');h.undo();assert.equal(h.document.name,'無題のグラフ');
const repeated=new C.History(d);repeated.change(x=>x.name='一度だけ');repeated.change(x=>x.name='一度だけ');repeated.undo();assert.equal(repeated.document.name,d.name,'同値のchangeはUndoを増やさない');
console.log('graph core tests passed');
