const assert = require('assert');
const E = require('../expression.js'), C = require('../core.js');
const T = require('../templates.js');
const near=(a,b)=>assert(Math.abs(a-b)<1e-10);
near(E.compile('2x+2(x+1)',{variables:['x']}).evaluate({x:3}),14);
near(E.compile('-x^2',{variables:['x']}).evaluate({x:3}),-9);
near(E.compile('2^3^2').evaluate({}),512);
near(E.compile('2^-2').evaluate({}),.25);
near(E.compile('max(2,min(3,-4),1)').evaluate({}),2);
near(E.compile('a(x+1)',{variables:['a','x']}).evaluate({a:3,x:2}),9);
near(E.compile('y = 2 x + 1',{variables:['x'],target:'y'}).evaluate({x:3}),7);
assert.throws(()=>E.compile('1.2.3'),/数値の間/);
assert.throws(()=>E.compile('2 3'),/数値の間/);
near(E.compile('sin(90)',{angle:'deg'}).evaluate({}),1);
near(E.compile('asin(1)',{angle:'deg'}).evaluate({}),90);
assert(Number.isNaN(E.compile('1/x',{variables:['x']}).evaluate({x:0})));
assert.throws(()=>E.compile('alert(1)'),/許可/);
near(E.compile('y=x+1',{variables:['x'],target:'y'}).evaluate({x:2}),3);
near(E.compile('z=x+y',{variables:['x','y'],target:'z'}).evaluate({x:2,y:3}),5);
assert.throws(()=>E.compile('z=x',{variables:['x'],target:'y'}),/左辺/);
assert.throws(()=>E.compile('constructor+1',{variables:['constructor']}),/変数名/);
assert.throws(()=>E.compile('x=1',{variables:['x'],target:false}),/等号/);
near(E.compileEquation('x^2+y^2=9',{variables:['x','y']}).evaluate({x:3,y:0}),0);
near(E.compileEquation('x+y',{variables:['x','y']}).evaluate({x:2,y:3}),5);
assert.throws(()=>E.compileEquation('x=y=1',{variables:['x','y']}),/等号/);
const d=C.createDocument(); d.series.push(C.createSeries('function')); C.validateDocument(d);
for (const kind of ['function','surface','data2d','data3d']) { const doc=C.createDocument(); doc.series.push(C.createSeries(kind)); C.validateDocument(doc); }
for (const template of T.list()) C.validateDocument(template.document);
assert.throws(()=>C.validateDocument({...d,series:[d.series[0],{...d.series[0]}]}),/ID/);
assert.deepStrictEqual(C.parseTable('x,y\n1,\n2,3',2),[[1,null],[2,3]]);
assert.deepStrictEqual(C.parseTable('"x value","y,value"\n1,2',2),[[1,2]]);
assert.throws(()=>C.parseTable('1,a',2),/不正/);
assert.throws(()=>C.parseTable('"1"garbage,2',2),/引用符/);
assert.throws(()=>C.parseTable('1e,2',2),/不正/);
const mem=new Map(), store={getItem:k=>mem.has(k)?mem.get(k):null,setItem:(k,v)=>mem.set(k,v)}; const s=new C.Store(store);s.save('auto',d);assert.equal(s.list()[0].kind,'auto');
const h=new C.History(d);h.change(x=>x.name='変更');h.undo();assert.equal(h.document.name,'無題のグラフ');
const repeated=new C.History(d);repeated.change(x=>x.name='一度だけ');repeated.change(x=>x.name='一度だけ');repeated.undo();assert.equal(repeated.document.name,d.name,'同値のchangeはUndoを増やさない');
const old={...C.createDocument(),version:1};delete old.annotations;for(const key of ['x','y','z']){delete old.axes[key].symbol;delete old.axes[key].ticks;}const migrated=C.validateDocument(old);assert.equal(migrated.version,4);assert.deepStrictEqual(migrated.annotations,[]);assert.equal(migrated.axes.x.symbol,'x');
const old2=C.createDocument();old2.version=2;for(const key of ['x','y','z']){delete old2.axes[key].symbol;delete old2.axes[key].ticks;}old2.annotations=[C.createAnnotation('guide')];delete old2.annotations[0].label;const migrated2=C.validateDocument(old2);assert.equal(migrated2.version,4);assert.deepStrictEqual(migrated2.annotations[0].label,{visible:true,dx:12,dy:-12,size:13});
const legacyV2Field=C.clone(old2);legacyV2Field.annotations[0].showEquation=false;assert.throws(()=>C.validateDocument(legacyV2Field),/版と内容/);
const old3=C.createDocument(), old3Function=C.createSeries('function'), old3Other=C.createSeries('function'), old3Tangent=C.createAnnotation('tangent'), old3Intersection=C.createAnnotation('intersection');old3.version=3;old3Function.id='old3-function';old3Other.id='old3-other';old3Tangent.id='old3-tangent';old3Tangent.seriesId=old3Function.id;delete old3Tangent.showEquation;old3Intersection.seriesIds=[old3Function.id,old3Other.id];old3.series=[old3Function,old3Other];old3.annotations=[old3Tangent,old3Intersection];const migrated3=C.validateDocument(old3);assert.equal(migrated3.version,4);assert.equal(migrated3.annotations[0].showEquation,false,'v3の接線式表示はfalseで移行する');assert.deepStrictEqual(migrated3.annotations[1].seriesIds,[old3Function.id,old3Other.id],'従来の関数交点を保持する');
const legacyV3Field=C.clone(old3);legacyV3Field.annotations[0].showEquation=true;assert.throws(()=>C.validateDocument(legacyV3Field),/版と内容/);const legacyV3Targets=C.clone(old3);legacyV3Targets.annotations[1].targets=[{type:'series',id:old3Function.id},{type:'series',id:old3Other.id}];assert.throws(()=>C.validateDocument(legacyV3Targets),/版と内容/);
const legacyPhase2={...old,series:[C.createSeries('implicit')]};assert.throws(()=>C.validateDocument(legacyPhase2),/版と内容/);
const legacyAnnotation={...old,annotations:[C.createAnnotation('guide')]};assert.throws(()=>C.validateDocument(legacyAnnotation),/版と内容/);
const limits=C.createDocument();for(let i=0;i<100;i++){const series=C.createSeries('function');series.id='s'+i;limits.series.push(series);const annotation=C.createAnnotation('guide');annotation.id='a'+i;limits.annotations.push(annotation);}C.validateDocument(limits);
const tooManyAnnotations=C.clone(limits);tooManyAnnotations.annotations.push(Object.assign(C.createAnnotation('guide'),{id:'a100'}));assert.throws(()=>C.validateDocument(tooManyAnnotations),/一覧/);
const phase=C.createDocument(), implicit=C.createSeries('implicit'), parametric=C.createSeries('parametric'), polar=C.createSeries('polar');phase.series.push(implicit,parametric,polar);phase.annotations.push(Object.assign(C.createAnnotation('point'),{anchor:{type:'curve',seriesId:parametric.id,at:'0'}}),Object.assign(C.createAnnotation('guide'),{axis:'y',value:'2'}),Object.assign(C.createAnnotation('tangent'),{seriesId:C.createSeries('function').id,at:'0'}));
phase.series.push(C.createSeries('function'));phase.annotations.find(a=>a.kind==='tangent').seriesId=phase.series.at(-1).id;C.validateDocument(phase);
const collision=C.clone(phase);collision.parameters.push({name:'t',value:1,min:0,max:2,step:.1});assert.throws(()=>C.validateDocument(collision),/重複/);
const invalidReference=C.clone(phase);invalidReference.annotations[0].anchor.seriesId='missing';assert.throws(()=>C.validateDocument(invalidReference),/参照先/);
const retainedAnnotations=C.clone(phase);retainedAnnotations.mode='3d';assert.equal(C.validateDocument(retainedAnnotations).annotations.length,phase.annotations.length,'注釈は3D表示へ切り替えても保持する');
const removable=C.clone(phase);C.removeSeries(removable,parametric.id);assert(!removable.series.some(s=>s.id===parametric.id));assert(!removable.annotations.some(a=>a.anchor&&a.anchor.seriesId===parametric.id));
const manyRows=C.createDocument();for(let i=0;i<6;i++){const series=C.createSeries('data2d');series.id='rows'+i;series.rows=Array.from({length:10000},(_,x)=>[x,x]);manyRows.series.push(series);}assert.throws(()=>C.validateDocument(manyRows),/総点数/);
const points=C.createDocument(), pointA=C.createAnnotation('point'), pointB=C.createAnnotation('point'), segment=C.createAnnotation('segment');pointA.id='point-a';pointB.id='point-b';segment.id='segment-ab';segment.from=pointA.id;segment.to=pointB.id;points.annotations=[segment,pointB,pointA];assert.equal(C.validateDocument(points).annotations.length,3,'注釈の順に依存しない参照を受け入れる');const badSegment=C.clone(points);badSegment.annotations[0].to='missing';assert.throws(()=>C.validateDocument(badSegment),/線分/);C.removeAnnotation(points,pointA.id);assert.equal(points.annotations.length,1,'端点を削除すると線分も再帰削除する');
const tangentDoc=C.createDocument(), functionSeries=C.createSeries('function');functionSeries.id='function-a';const tangentA=C.createAnnotation('tangent'),tangentB=C.createAnnotation('tangent'),cross=C.createAnnotation('tangentIntersection');tangentA.id='tangent-a';tangentB.id='tangent-b';cross.id='cross';tangentA.seriesId=tangentB.seriesId=functionSeries.id;cross.tangentIds=[tangentA.id,tangentB.id];tangentDoc.series=[functionSeries];tangentDoc.annotations=[cross,tangentA,tangentB];C.validateDocument(tangentDoc);C.removeSeries(tangentDoc,functionSeries.id);assert.equal(tangentDoc.annotations.length,0,'系列削除は接線交点まで再帰削除する');
const targetDoc=C.createDocument(), targetFunction=C.createSeries('function'), targetOther=C.createSeries('function'), targetTangent=C.createAnnotation('tangent'), targetIntersection=C.createAnnotation('intersection');targetFunction.id='target-function';targetOther.id='target-other';targetTangent.id='target-tangent';targetTangent.seriesId=targetFunction.id;targetIntersection.id='target-intersection';delete targetIntersection.seriesIds;targetIntersection.targets=[{type:'tangent',id:targetTangent.id},{type:'series',id:targetOther.id}];targetDoc.series=[targetFunction,targetOther];targetDoc.annotations=[targetIntersection,targetTangent];const targetClean=C.validateDocument(targetDoc);assert.deepStrictEqual(targetClean.annotations[0].targets,targetIntersection.targets,'交点の型付き参照を順不同で検証する');assert.equal(C.createAnnotation('tangent').showEquation,true,'新規接線は式を表示する');const bothReferences=C.clone(targetDoc);bothReferences.annotations[0].seriesIds=[targetFunction.id,targetOther.id];assert.throws(()=>C.validateDocument(bothReferences),/交点/);const duplicateTarget=C.clone(targetDoc);duplicateTarget.annotations[0].targets=[{type:'series',id:targetOther.id},{type:'series',id:targetOther.id}];assert.throws(()=>C.validateDocument(duplicateTarget),/交点/);const missingTangent=C.clone(targetDoc);missingTangent.annotations[0].targets[0].id='missing';assert.throws(()=>C.validateDocument(missingTangent),/交点/);C.removeAnnotation(targetDoc,targetTangent.id);assert.equal(targetDoc.annotations.length,0,'接線削除は型付き参照の交点も再帰削除する');
const targetSeriesDoc=C.clone(targetClean);C.removeSeries(targetSeriesDoc,targetOther.id);assert.equal(targetSeriesDoc.annotations.length,1,'型付き参照の系列削除は交点を再帰削除する');
const duplicateSymbol=C.createDocument();duplicateSymbol.axes.y.symbol='x';assert.throws(()=>C.validateDocument(duplicateSymbol),/記号|軸/);
console.log('graph core tests passed');
