/* 複数文書の分離、保存中の切替、失敗時の保持を実画面で確認する。 */
const assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path'),os=require('node:os');
let chromium;try{({chromium}=require('playwright'));}catch{({chromium}=require(path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')));}
const C=require('../core.js'),Toolbar=require('./toolbar-helpers.cjs');
const root=path.resolve(__dirname,'../../..');
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(file,(error,data)=>{res.writeHead(error?404:200,{'Content-Type':file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.svg')?'image/svg+xml':'text/html'});res.end(error?'not found':data);});});
let browser;
(async()=>{
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  browser=await chromium.launch({channel:'chrome',headless:true});
  const context=await browser.newContext({viewport:{width:1440,height:950}});
  await context.addInitScript(()=>{
    window.testIO={files:{},pickers:0,next:'B.graph.json',cancel:false,fail:false,hold:false};
    const handles=new Map();
    window.showSaveFilePicker=async()=>{
      const io=window.testIO;io.pickers++;if(io.cancel)throw new DOMException('cancel','AbortError');
      if(!handles.has(io.next)){
        const name=io.next;io.files[name]={text:'',at:1};
        const handle={name,queryPermission:async()=> 'granted',isSameEntry:async other=>other===handle,
          getFile:async()=>({name,lastModified:io.files[name].at,size:new TextEncoder().encode(io.files[name].text).length}),
          createWritable:async()=>{let text;return{write:async value=>{if(io.hold)await new Promise(resolve=>{io.release=resolve;});if(io.fail)throw new Error('test disk failure');text=typeof value==='string'?value:await value.text();},close:async()=>{io.files[name]={text,at:io.files[name].at+1};},abort:async()=>{}};}};
        handles.set(name,handle);
      }
      return handles.get(io.next);
    };
  });
  const page=await context.newPage(),errors=[];page.setDefaultTimeout(12000);page.on('pageerror',error=>errors.push(error.message));
  const url=process.env.GRAPH_TEST_URL||`http://127.0.0.1:${server.address().port}/tools/graph/index.html`;
  const settle=()=>page.waitForFunction(()=>window.GraphEditor&&!GraphEditor.getState().drawing);
  const state=()=>page.evaluate(()=>GraphEditor.getState());
  const doc=()=>page.evaluate(()=>GraphEditor.getDocument());
  const entries=()=>page.evaluate(()=>new GraphDocumentStore.Store(localStorage).list().entries);
  const select=async id=>{await page.locator(`[role="tab"][data-document-tab-id="${id}"]`).click();await settle();assert.equal((await state()).tabId,id);};
  const fileMenu=async()=>{const menu=page.locator('#file-menu');if(!await menu.evaluate(el=>el.open))await menu.locator(':scope > summary').click();};
  const rename=async name=>{await Toolbar.openAxes(page);await page.getByLabel('グラフ名',{exact:true}).fill(name);await page.locator('#dialog-submit').click();await settle();};
  const saveBrowser=async()=>{await fileMenu();await page.locator('#save-browser').click();};
  const close=async id=>{await page.locator(`[data-document-tab-close="${id}"]`).click();};
  const fixture=name=>{const d=C.createDocument();d.name=name;d.equalScale=false;const f=C.createSeries('function');f.expression=name==='A'?'x^2':'2*x';d.series=[f];return d;};
  const load=async d=>{await page.locator('#file-input').setInputFiles({name:d.name+'.graph.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(d))});await settle();return (await state()).tabId;};
  await page.goto(url);await settle();const initial=(await state()).tabId;
  assert.equal((await state()).tabs.length,1);
  assert.equal(Math.round((await page.locator('.side-tabs').boundingBox()).width),26);
  for(const id of ['format','templates','export'])assert.equal(await page.locator('#'+id+'-tab > svg').count(),1);
  const a=await load(fixture('A')),b=await load(fixture('B'));
  assert.equal((await state()).tabs.length,3);assert(!(await state()).tabs.find(t=>t.id===b).dirty);
  await rename('B edited');await select(a);await rename('A edited');
  await select(b);assert.equal((await doc()).name,'B edited');await Toolbar.clickToolbarControl(page,'undo');await settle();assert.equal((await doc()).name,'B');
  await select(a);assert.equal((await doc()).name,'A edited');await select(b);await Toolbar.clickToolbarControl(page,'redo');await settle();assert.equal((await doc()).name,'B edited');
  await select(a);await saveBrowser();await page.evaluate(()=>Plotly.relayout(document.querySelector('#plot'),{'xaxis.range':[-1,1]}));await settle();
  assert(!(await state()).tabs.find(t=>t.id===a).dirty,'zoom alone is not an unsaved edit');
  await Toolbar.openAxes(page);await page.getByRole('tab',{name:'範囲',exact:true}).click();
  await page.locator('[data-axis="x"] input[type="number"]').first().fill('-2');await page.locator('#dialog-submit').click();await settle();
  assert((await state()).tabs.find(t=>t.id===a).dirty,'an applied coordinate range is an unsaved edit');
  await Toolbar.clickToolbarControl(page,'undo');await settle();assert(!(await state()).tabs.find(t=>t.id===a).dirty);
  const ax=(await doc()).axes.x;await select(b);assert.notEqual((await doc()).axes.x.min,ax.min);await select(a);assert.equal((await doc()).axes.x.min,ax.min);
  await rename('A latest');await page.waitForTimeout(350);
  assert.equal((await entries()).find(e=>e.id===a&&e.kind==='saved').document.name,'A edited');
  assert.equal((await entries()).find(e=>e.id===a&&e.kind==='auto').document.name,'A latest');
  await select(b);await page.keyboard.press('Control+s');assert(await page.locator('#save-choice-local').isVisible());await page.locator('#dialog-cancel').click();
  assert.equal((await state()).tabs.find(t=>t.id===b).saveTarget,null);
  await page.keyboard.press('Control+s');await page.locator('#save-choice-local').click();await page.waitForFunction(()=>!GraphEditor.getState().tabs.find(t=>t.id===GraphEditor.getState().tabId).busy);
  assert.equal((await state()).tabs.find(t=>t.id===b).saveTarget,'local');
  await rename('B snapshot');await page.evaluate(()=>{testIO.hold=true;});await page.keyboard.press('Control+s');await page.waitForFunction(()=>!!testIO.release);
  const pickers=await page.evaluate(()=>testIO.pickers);await select(a);await rename('A during B save');await select(b);await rename('B after save started');
  await page.evaluate(()=>{testIO.hold=false;testIO.release();});await page.waitForFunction(()=>!GraphEditor.getState().tabs.some(t=>t.busy));
  assert.equal(await page.evaluate(()=>JSON.parse(testIO.files['B.graph.json'].text).name),'B snapshot');
  assert.equal(await page.evaluate(()=>testIO.pickers),pickers,'repeat local save reuses that tab handle');
  assert((await state()).tabs.find(t=>t.id===b).dirty,'later edits remain unsaved');
  assert.equal((await state()).tabs.find(t=>t.id===a).saveTarget,'browser');
  await close(b);await page.locator('#dialog-cancel').click();assert.equal((await state()).tabs.length,3);
  await page.evaluate(()=>{testIO.fail=true;});await close(b);await page.locator('#tab-save-close').click();await page.waitForFunction(()=>!GraphEditor.getState().tabs.some(t=>t.busy));
  assert.equal((await state()).tabs.length,3);assert((await state()).tabs.find(t=>t.id===b).dirty);
  await page.evaluate(()=>{testIO.fail=false;});await saveBrowser();assert.equal((await state()).tabs.find(t=>t.id===b).saveTarget,'browser');
  await page.evaluate(()=>{testIO.next='B.autosave.graph.json';});await fileMenu();await page.locator('#start-local-auto').click();
  await page.waitForFunction(()=>GraphEditor.getState().localAutosave&&!GraphEditor.getState().tabs.some(t=>t.busy));
  await rename('B auto latest');await select(a);await page.waitForFunction(()=>JSON.parse(testIO.files['B.autosave.graph.json'].text).name==='B auto latest');
  await page.evaluate(()=>{testIO.next='A.autosave.graph.json';});await fileMenu();await page.locator('#start-local-auto').click();
  await page.waitForFunction(()=>GraphEditor.getState().localAutosave&&!GraphEditor.getState().tabs.some(t=>t.busy));
  await rename('A auto latest');await page.waitForFunction(()=>JSON.parse(testIO.files['A.autosave.graph.json'].text).name==='A auto latest');
  assert.equal(await page.evaluate(()=>JSON.parse(testIO.files['B.autosave.graph.json'].text).name),'B auto latest');
  await fileMenu();await page.locator('#save-local').click();await page.waitForFunction(()=>!GraphEditor.getState().tabs.some(t=>t.busy));
  assert.equal((await state()).tabs.find(t=>t.id===a).saveTarget,'browser','an autosave file cannot become an explicit destination');
  await page.evaluate(()=>{window.originalSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key.endsWith(':saved'))throw new DOMException('quota','QuotaExceededError');return originalSetItem.call(this,key,value);};});
  await close(a);await page.locator('#tab-save-close').click();await settle();assert((await state()).tabs.some(t=>t.id===a&&t.dirty),'browser save failure retains the tab');
  await page.evaluate(()=>{Storage.prototype.setItem=originalSetItem;});
  await select(b);
  await rename('B final');await close(b);await page.locator('#tab-save-close').click();await settle();assert(!(await state()).tabs.some(t=>t.id===b));
  assert.equal((await entries()).find(e=>e.id===b&&e.kind==='saved').document.name,'B final');
  await select(a);await close(a);await page.locator('#tab-discard-close').click();await settle();assert(!(await state()).tabs.some(t=>t.id===a));
  assert.equal((await entries()).find(e=>e.id===a&&e.kind==='saved').document.name,'A edited','closing does not delete explicit saves');
  assert.equal((await state()).tabId,initial);
  const c=await load(fixture('C'));await rename('C edited');await close(c);await page.locator('#tab-save-close').click();
  await page.evaluate(()=>{testIO.cancel=true;});await page.locator('#save-choice-local').click();await page.waitForFunction(()=>!GraphEditor.getState().tabs.some(t=>t.busy));
  assert((await state()).tabs.some(t=>t.id===c&&t.dirty),'cancelled file picker cannot close the tab');
  await page.evaluate(()=>{testIO.cancel=false;});await close(c);await page.locator('#tab-discard-close').click();await settle();
  const before=(await state()).tabs.length;
  await page.locator('#file-input').setInputFiles({name:'bad.graph.json',mimeType:'application/json',buffer:Buffer.from('{bad')});await settle();assert.equal((await state()).tabs.length,before);
  for(let i=0;i<5;i++)await load(fixture('長い文書名のグラフ '+i));
  await Toolbar.setAppearance(page,{theme:'dark',textSize:'largest'});await page.keyboard.press('Escape');await page.setViewportSize({width:390,height:850});await page.waitForTimeout(200);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  assert.equal(Math.round((await page.locator('.side-tabs').boundingBox()).width),30);
  const top=await page.locator('.top').boundingBox(),help=await page.locator('#help-button').boundingBox();assert(help.x+help.width<=390&&help.y+help.height<=top.y+top.height+.5);
  await page.locator('.graph-document-tabs__menu > summary').click();assert(await page.locator('.graph-document-tabs__menu-panel').isVisible());
  await page.locator('.graph-document-tabs__menu-panel [data-document-tab-id="'+initial+'"]').click();await settle();assert.equal((await state()).tabId,initial);
  await page.screenshot({path:'/private/tmp/graph-documents-narrow.png'});
  await page.setViewportSize({width:1440,height:950});await Toolbar.setAppearance(page,{textSize:'standard'});await page.keyboard.press('Escape');
  await page.locator('#templates-tab').click();const wasOpen=await page.locator('#templates-tab').getAttribute('aria-expanded');
  await page.reload();await settle();assert.equal(await page.locator('#templates-tab').getAttribute('aria-expanded'),wasOpen);
  assert(await page.locator('.saved-option[data-save-kind="auto"]').count());assert(await page.locator('.saved-option[data-save-kind="saved"]').count());
  const stored=(await entries()).length;await page.locator('.saved-option[data-save-kind="saved"][data-saved-id="'+b+'"]').click();await settle();
  assert.equal((await doc()).name,'B final');assert.equal((await state()).tabs.length,2);assert((await entries()).length>=stored);
  await page.screenshot({path:'/private/tmp/graph-documents-wide.png'});
  await page.evaluate(()=>{const id=GraphEditor.getState().tabId,control=document.querySelector('[data-document-tab-close="'+id+'"]');control.click();control.click();});
  await settle();assert.equal((await state()).tabs.length,1,'repeated close must not remove a neighbouring document');assert.equal((await doc()).name,'はじめてのグラフ');
  const firstClose=await load(fixture('一緒に閉じる1')),secondClose=await load(fixture('一緒に閉じる2'));
  await page.evaluate(ids=>{for(const id of ids)document.querySelector('[data-document-tab-close="'+id+'"]').click();},[secondClose,firstClose]);
  await settle();assert.equal((await state()).tabs.length,1,'closing neighbouring tabs during redraw preserves the remaining document');assert.equal((await doc()).name,'はじめてのグラフ');
  await close((await state()).tabId);await settle();assert.equal((await state()).tabs.length,1,'closing the last tab opens one blank document');assert.equal((await doc()).series.length,0);
  assert.deepEqual(errors,[]);
  console.log('document-tabs-browser.test.cjs: ok');
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(async()=>{await browser?.close();if(server.listening)await new Promise(resolve=>server.close(resolve));});
