/* Chrome: compact tangent equations and direct, non-modal object formatting. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const http = require('node:http');
const path = require('node:path');
const os = require('node:os');
let chromium;
try { ({ chromium } = require('playwright')); }
catch { ({ chromium } = require(path.join(os.homedir(), '.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'))); }
const root = path.resolve(__dirname, '../../..');
const server = http.createServer((req, res) => {
  const file = path.resolve(root, '.' + decodeURIComponent(req.url.split('?')[0]));
  if (!file.startsWith(root + path.sep)) { res.writeHead(403); return res.end(); }
  fs.readFile(file, (error, data) => { res.writeHead(error ? 404 : 200, { 'Content-Type': file.endsWith('.js') ? 'text/javascript' : file.endsWith('.css') ? 'text/css' : file.endsWith('.svg') ? 'image/svg+xml' : 'text/html' }); res.end(error ? 'not found' : data); });
});
let browser, page;
(async () => {
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  browser = await chromium.launch({ channel: 'chrome', headless: true });
  const context = await browser.newContext({ viewport: { width: 1360, height: 950 }, hasTouch: true });
  page = await context.newPage(); const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const settle = () => page.waitForFunction(() => window.GraphEditor && !GraphEditor.getState().drawing && !document.querySelector('#editor-dialog').open);
  const doc = () => page.evaluate(() => GraphEditor.getDocument());
  const bar = page.locator('#selection-toolbar'), dialog = page.locator('#editor-dialog');
  const color = hex => bar.locator('[data-quick-control="color-' + hex.slice(1) + '"]');
  const item = id => page.locator('[data-object-id="' + id + '"]');
  const submit = async () => { await page.locator('#dialog-submit').click(); await settle(); };
  const fill = (label, value) => dialog.getByLabel(label, { exact: true }).fill(String(value));
  const annotation = id => page.evaluate(id => GraphEditor.getDocument().annotations.find(a => a.id === id), id);
  const seriesAdd = async () => { if (await page.locator('#series-add-panel').isHidden()) await page.locator('#series-add-toggle').click(); };
  const annotationAdd = async () => { if (await page.locator('#series-add-panel').isHidden()) await page.locator('#series-add-toggle').click(); };
  const addQuickTangent = async (at) => { await annotationAdd(); await page.locator('#add-tangent').click(); const panel=page.locator('#tangent-quick-panel'); await panel.getByLabel(/^接点の .+ 座標$/).fill(String(at)); await panel.getByRole('button',{name:'接線を追加',exact:true}).click(); await settle(); };
  await page.goto(process.env.GRAPH_TEST_URL || `http://127.0.0.1:${server.address().port}/tools/graph/index.html`); await settle();
  const series = (await doc()).series[0].id;
  await item(series).click(); assert.equal(await bar.locator('.quick-color').count(), 6);
  const beforeColor = await doc(); await color('#16a34a').click(); await settle();
  assert(!await dialog.isVisible()); assert.equal((await doc()).series[0].style.color, '#16a34a');
  assert.equal(await color('#16a34a').getAttribute('aria-pressed'), 'true'); assert(await color('#16a34a').evaluate(el => el === document.activeElement));
  await page.keyboard.press('Tab'); assert(await color('#9333ea').evaluate(el => el === document.activeElement)); await page.keyboard.press('Enter'); await settle();
  assert.equal((await doc()).series[0].style.color, '#9333ea');
  await page.locator('#undo').click(); await settle(); assert.equal((await doc()).series[0].style.color, '#16a34a');
  await page.locator('#undo').click(); await settle(); assert.deepEqual(await doc(), beforeColor);
  await item(series).click(); const width = bar.getByLabel('線の太さ', { exact: true }); assert(await width.isVisible()); assert(await bar.getByLabel('線種', { exact: true }).isVisible());
  assert.equal(await bar.locator('.quick-color').count(), 6);
  await bar.getByRole('button',{name:'自由な色（RGB）',exact:true}).click(); await fill('R',8); await fill('G',145); await fill('B',178); await submit(); await settle(); assert.equal((await doc()).series[0].style.color, '#0891b2');
  await width.fill('4'); await width.press('Tab'); await settle();
  assert.equal((await doc()).series[0].style.width, 4);
  assert(await bar.getByLabel('線種', { exact: true }).evaluate(el => el === document.activeElement), 'Tab advances to the next direct control');
  await bar.getByLabel('線種', { exact: true }).selectOption('dot'); await settle(); assert.equal((await doc()).series[0].style.dash, 'dot');
  assert.equal(await page.evaluate(() => document.querySelector('#plot').data[0].line.dash), 'dot');
  await width.fill('50'); await width.press('Tab'); await settle(); assert.equal((await doc()).series[0].style.width, 4); assert.equal(await width.inputValue(), '4');
  await width.fill('7'); await width.press('Escape'); assert.equal((await doc()).series[0].style.width, 4);
  await bar.getByRole('button',{name:'自由な色（RGB）',exact:true}).click(); await fill('R', 12); await fill('G', 34); await fill('B', 56); await submit();
  assert.equal((await doc()).series[0].style.color, '#0c2238');
  await page.locator('[data-object-details="series:'+series+'"]').click();await page.locator('#object-menu').getByRole('menuitem',{name:'複製',exact:true}).click();await settle(); const copy = (await doc()).series.at(-1); assert.deepEqual(copy.style, (await doc()).series[0].style, 'duplicate uses the latest direct formatting');
  await bar.getByLabel('線の太さ', { exact: true }).fill('5'); await item(series).click(); await settle();
  assert.equal((await page.evaluate(() => GraphEditor.getState())).selected.id, series, 'changing a number does not swallow the next object-selection click');
  assert.equal((await doc()).series.find(s => s.id === copy.id).style.width, 5); assert.equal((await doc()).series[0].style.width, 4);
  await item(copy.id).click();
  await page.locator('[data-object-details="series:'+copy.id+'"]').click();await page.locator('#object-menu').getByRole('menuitem',{name:'削除',exact:true}).click();await settle();
  // Reproduce decimal derivatives from the supplied screenshots with actual formulas.
  await item(series).dblclick(); await fill('名前', '放物線'); await fill('数式（例：y = a*x^2）', '0.9*x^2-1.2'); await submit();
  await addQuickTangent(2);
  const tangent = (await doc()).annotations.at(-1).id;
  assert.equal(await page.locator('[data-tangent-equation="' + tangent + '"]').innerText(), 'y ≈ 3.6x − 4.8');
  await bar.getByLabel('接線の方程式を図に表示', { exact: true }).uncheck(); await settle(); assert.equal((await annotation(tangent)).showEquation, false);
  await bar.getByLabel('名前を表示', { exact: true }).uncheck(); await settle(); assert.equal((await annotation(tangent)).label.visible, false);
  await bar.getByLabel('文字サイズ（px）', { exact: true }).fill('18'); await bar.getByLabel('文字サイズ（px）', { exact: true }).press('Tab'); await settle();
  assert.equal((await annotation(tangent)).label.size, 18);
  await bar.getByLabel('接線の方程式を図に表示', { exact: true }).check(); await settle();
  assert(await page.evaluate(id => document.querySelector('#plot').layout.annotations.some(a => a.name === id && a.text === 'y ≈ 3.6x − 4.8' && a.font.size === 18), tangent));
  await bar.getByLabel('横のずれ（右へ px）', { exact: true }).fill('25'); await bar.getByLabel('横のずれ（右へ px）', { exact: true }).press('Tab'); await settle(); assert.equal((await annotation(tangent)).label.dx, 25);
  // Changing the selected object cannot send old controls to the previous object.
  await item(series).click(); assert.equal(await page.locator('#selection-label').count(), 0); await color('#2563eb').click(); await settle(); assert.equal((await annotation(tangent)).style.color, '#dc2626');
  await seriesAdd(); await page.locator('#add-function').click(); await fill('名前', '一次関数'); await fill('数式（例：y = a*x^2）', '0.9*x+0.6'); await submit();
  await addQuickTangent(-0.75);
  const tangent2 = (await doc()).annotations.at(-1).id;
  assert.equal(await page.locator('[data-tangent-equation="' + tangent2 + '"]').innerText(), 'y ≈ 0.9x + 0.6');
  const beforeDisplay = await doc();
  const svg = await page.evaluate(async () => { const url = await GraphPlot.exportImage(document.querySelector('#plot'), { format: 'svg', scale: 1, background: 'white' }); return fetch(url).then(r => r.text()); });
  assert(svg.includes('3.6x') && svg.includes('0.9x')); assert(!svg.includes('999999988')); assert.deepEqual(await doc(), beforeDisplay, 'formatting a displayed equation never rewrites formula data');
  await page.locator('#file-menu summary').click(); await page.locator('#save-browser').click(); await page.reload(); await page.locator('#editor-dialog[open]').waitFor(); await page.getByRole('button', { name: /^明示保存：/ }).click(); await settle(); assert.deepEqual(await doc(), beforeDisplay);
  await item(tangent).click(); await page.screenshot({ path: '/private/tmp/graph-quick-style-desktop.png' });
  await page.locator('#view-menu summary').click(); await page.locator('#theme').selectOption('dark'); await page.locator('#text-size').selectOption('largest'); await page.keyboard.press('Escape'); await settle();
  await page.setViewportSize({ width: 390, height: 850 }); await page.waitForTimeout(220); await settle();
  assert(await page.locator('body').evaluate(el => el.scrollWidth <= innerWidth)); assert(await bar.evaluate(el => el.scrollWidth <= el.clientWidth));
  await color('#111827').tap(); await settle(); assert.equal((await annotation(tangent)).style.color, '#111827'); assert(!await dialog.isVisible());
  assert(await color('#111827').evaluate(el => { const r = el.getBoundingClientRect(); return r.width >= 44 && r.height >= 44; }));
  await page.screenshot({ path: '/private/tmp/graph-quick-style-mobile.png' });
  await bar.getByLabel('名前を表示', { exact: true }).tap(); await settle(); assert.equal((await annotation(tangent)).label.visible, true);
  await page.keyboard.press('Escape'); assert.equal(await page.locator('#selection-label').count(), 1); assert.equal((await page.evaluate(() => GraphEditor.getState())).selected.id, tangent, '入力中のEscapeは選択を保持する');
  await page.locator('#stage').focus(); await page.keyboard.press('Escape'); assert.equal(await page.locator('#selection-label').count(), 0); assert.equal((await page.evaluate(() => GraphEditor.getState())).selected, null, '入力外のEscapeは選択を解除する');
  assert.deepEqual(errors, []); await browser.close(); await new Promise(resolve => server.close(resolve));
  console.log('graph quick-style-browser.test.cjs: ok');
})().catch(async error => { if (page) await page.screenshot({ path: '/private/tmp/graph-quick-style-failure.png' }).catch(() => {}); if (browser) await browser.close(); server.close(); console.error(error); process.exitCode = 1; });
