/* Chrome: non-modal tangent quick entry. */
const assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path'),os=require('node:os');
let chromium;
try { ({chromium}=require('playwright')); }
catch { ({chromium}=require(path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'))); }
const root=path.resolve(__dirname,'../../..');
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(file,(e,data)=>{res.writeHead(e?404:200,{'Content-Type':file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html'});res.end(e?'not found':data);});});
let browser;
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));browser=await chromium.launch({channel:'chrome',headless:true});
 const context=await browser.newContext({viewport:{width:1280,height:850},hasTouch:true});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const settle=()=>page.waitForFunction(()=>window.GraphEditor&&!GraphEditor.getState().drawing&&!document.querySelector('#editor-dialog').open);
 const doc=()=>page.evaluate(()=>GraphEditor.getDocument()); const panel=page.locator('#tangent-quick-panel'); const bar=page.locator('#selection-toolbar');
 const coordinate=()=>panel.getByLabel(/^接点の .+ 座標$/); const add=()=>panel.getByRole('button',{name:'接線を追加',exact:true});
 const fill=(label,value)=>page.locator('#editor-dialog').getByLabel(label,{exact:true}).fill(String(value));const submit=async()=>{await page.locator('#dialog-submit').click();await settle();};
 await page.goto(process.env.GRAPH_TEST_URL||`http://127.0.0.1:${server.address().port}/tools/graph/index.html`);await settle();
 const first=(await doc()).series[0].id;await page.locator('[data-object-id="'+first+'"]').click();const trigger=bar.getByRole('button',{name:'この曲線の接線',exact:true});await trigger.hover();await panel.waitFor({state:'visible'});assert.equal(await panel.getAttribute('role'),'region');assert.equal(await panel.getAttribute('aria-label'),'接線を追加');assert.equal(await trigger.evaluate(el=>el===document.activeElement),false,'hover does not steal focus');
 await coordinate().fill('1');await settle();assert((await panel.getByLabel('接線の方程式',{exact:true}).innerText()).includes('≈'));assert.equal((await doc()).annotations.length,0);assert(await page.evaluate(()=>document.querySelector('#plot').data.some(t=>t.name==='接線（プレビュー）')),'preview is rendered only');await page.keyboard.press(process.platform==='darwin'?'Meta+s':'Control+s');assert.equal((await doc()).annotations.length,0,'Cmd/Ctrl+S does not save a preview');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('kaijo-graph:saved')).document.annotations.length),0,'explicit browser save excludes preview annotations');if(await panel.isHidden()){await page.locator('[data-object-id="'+first+'"]').click();await trigger.click();await coordinate().fill('1');}await page.keyboard.press('Escape');await panel.waitFor({state:'hidden'});assert.equal((await doc()).annotations.length,0,'Escape separately discards preview');
 await trigger.click();await panel.waitFor({state:'visible'});assert(await coordinate().evaluate(el=>el===document.activeElement),'click focuses coordinate');await coordinate().fill('1');await coordinate().press('Enter');await settle();assert.equal((await doc()).annotations.length,1);const tangent=(await doc()).annotations[0];assert.equal(tangent.kind,'tangent');assert.equal(tangent.at,'1');await page.locator('#undo').click();await settle();assert.equal((await doc()).annotations.length,0);await page.locator('#redo').click();await settle();assert.equal((await doc()).annotations.length,1);
 await page.locator('#axes-button').click();await page.locator('[data-axis="x"]').getByLabel('数式で使う記号',{exact:true}).fill('t');await page.locator('[data-axis="y"]').getByLabel('数式で使う記号',{exact:true}).fill('s');await submit();
 await page.locator('#add-function').click();await fill('名前','直線');await fill('数式（例：s = a*t^2）','s=t');await submit();const second=(await doc()).series.at(-1).id;await page.locator('[data-object-id="'+second+'"]').click();await trigger.click();await panel.getByLabel('対象の数式',{exact:true}).selectOption(second);assert.equal(await panel.locator('label',{hasText:'接点の t 座標'}).count(),1);await coordinate().fill('1/2');assert.equal(await add().isDisabled(),false);await add().click();await settle();assert.equal((await doc()).annotations.at(-1).seriesId,second);
 await page.locator('#add-tangent').click();await coordinate().fill('nope');assert(await add().isDisabled(),'invalid expression cannot be added');await coordinate().fill('99');assert(await add().isDisabled(),'outside domain cannot be added');await page.mouse.click(2,2);await panel.waitFor({state:'hidden'});await settle();assert(!await page.evaluate(()=>document.querySelector('#plot').data.some(t=>t.name==='接線（プレビュー）')),'outside click removes preview traces');
 await page.locator('#add-function').click();await fill('名前','角');await fill('数式（例：s = a*t^2）','abs(t)');await submit();const corner=(await doc()).series.at(-1).id;await page.locator('#add-tangent').click();await panel.getByLabel('対象の数式',{exact:true}).selectOption(corner);await coordinate().fill('0');assert(await add().isDisabled(),'corner has no tangent');await page.mouse.click(2,2);await panel.waitFor({state:'hidden'});
 await page.locator('#view-menu summary').click();await page.locator('#theme').selectOption('dark');await page.keyboard.press('Escape');await page.setViewportSize({width:390,height:850});await page.locator('#list-toggle').tap();await page.locator('#add-tangent').tap();await panel.waitFor({state:'visible'});assert(await page.locator('body').evaluate(el=>el.scrollWidth<=innerWidth));await panel.getByRole('button',{name:'接線の追加を閉じる',exact:true}).tap();await panel.waitFor({state:'hidden'});
 assert.deepEqual(errors,[]);await browser.close();await new Promise(resolve=>server.close(resolve));console.log('graph quick-tangent-browser.test.cjs: ok');
})().catch(async error=>{if(browser)await browser.close();server.close();console.error(error);process.exitCode=1;});
