const assert = require('node:assert/strict'), fs = require('node:fs'), http = require('node:http'), path = require('node:path'), os = require('node:os');
let chromium; try { ({ chromium } = require('playwright')); } catch (_) { ({ chromium } = require(path.join(os.homedir(), '.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'))); }
const root = path.resolve(__dirname, '../../..');
const server = http.createServer((req, res) => { const file = path.resolve(root, '.' + decodeURIComponent(req.url.split('?')[0])); if (!file.startsWith(root + path.sep) || !fs.existsSync(file)) { res.writeHead(404); return res.end(); } res.writeHead(200, { 'Content-Type': file.endsWith('.js') ? 'text/javascript' : 'text/html' }); res.end(fs.readFileSync(file)); });
(async () => {
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve)); const browser = await chromium.launch({ channel: 'chrome', headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 900, height: 650 } }), base = 'http://127.0.0.1:' + server.address().port + '/tools/graph/';
    await page.setContent('<div id="plot" style="width:700px;height:480px"></div><div id="chart" style="width:500px;height:360px"></div>');
    for (const script of ['vendor/plotly.min.js', 'expression.js', 'symbols.js', 'curves.js', 'annotations.js', 'data-curves.js', 'plot.js', 'workspace.js']) await page.addScriptTag({ url: base + script });
    const result = await page.evaluate(async () => {
      const axis = symbol => ({ min: -1, max: 5, label: symbol, symbol, unit: '', scale: 'linear', ticks: { step: null, format: 'auto' } });
      const doc = { name: '行選択', mode: '2d', angle: 'rad', axes: { x: axis('x'), y: axis('y'), z: axis('z') }, parameters: [], grid: true, legend: true, equalScale: false, presentation: {}, annotations: [], series: [{ id: 'data', kind: 'data2d', name: '観測', rows: [[0, 0], [1, 1], [2, 4], [3, 2]], excludedRows: [1], visible: true, interpolation: 'monotone', errorBars: { x: [], y: [] }, style: { color: '#2563eb', width: 2, dash: 'solid', points: true, lines: true, opacity: 1 } }] };
      const selected = [], series = [], blanks = []; const plot = document.querySelector('#plot');
      await GraphPlot.render(plot, doc, { selectedRow: { seriesId: 'data', rowIndex: 1 }, onRowSelect: row => selected.push(row), onSelect: id => series.push(id), onBlankClick: () => blanks.push('blank') });
      const observed = plot.data.find(trace => trace.meta?.dataRows), highlight = plot.data.find(trace => trace.meta?.observationHighlight);
      const point = GraphPlot.screenPoint(plot, [1, 1]); plot.dispatchEvent(new PointerEvent('pointerdown', { bubbles: true, clientX: point[0], clientY: point[1], button: 0, pointerId: 4, pointerType: 'mouse' })); plot.dispatchEvent(new PointerEvent('pointerup', { bubbles: true, clientX: point[0], clientY: point[1], button: 0, pointerId: 4, pointerType: 'mouse' })); plot.emit('plotly_click', { points: [{ x: 1, y: 1, customdata: [2], data: observed }], event: { clientX: point[0], clientY: point[1] } });
      const lineTrace = plot.data.find(trace => trace.mode === 'lines'), lineIndex = lineTrace.x.findIndex(value => value !== null && !Number.isInteger(value)); const line = GraphPlot.screenPoint(plot, [lineTrace.x[lineIndex], lineTrace.y[lineIndex]]); plot.emit('plotly_click', { points: [{ x: lineTrace.x[lineIndex], y: lineTrace.y[lineIndex], data: lineTrace, curveNumber: plot.data.indexOf(lineTrace) }], event: { clientX: line[0], clientY: line[1] } });
      const blank = GraphPlot.screenPoint(plot, [-.5, 4.5]); plot.dispatchEvent(new PointerEvent('pointerdown', { bubbles: true, clientX: blank[0], clientY: blank[1], button: 0, pointerId: 5, pointerType: 'mouse' })); plot.dispatchEvent(new PointerEvent('pointerup', { bubbles: true, clientX: blank[0], clientY: blank[1], button: 0, pointerId: 5, pointerType: 'mouse' }));
      const drag = GraphPlot.screenPoint(plot, [.2, 4.4]); plot.dispatchEvent(new PointerEvent('pointerdown', { bubbles: true, clientX: drag[0], clientY: drag[1], button: 0, pointerId: 6, pointerType: 'mouse' })); document.dispatchEvent(new PointerEvent('pointermove', { bubbles: true, clientX: drag[0] + 20, clientY: drag[1], button: 0, pointerId: 6, pointerType: 'mouse' })); document.dispatchEvent(new PointerEvent('pointerup', { bubbles: true, clientX: drag[0] + 20, clientY: drag[1], button: 0, pointerId: 6, pointerType: 'mouse' })); await new Promise(resolve => setTimeout(resolve, 20));
      const original = Plotly.newPlot, exported = []; Plotly.newPlot = async (...args) => { exported.push(args[1]); return original(...args); }; await GraphPlot.exportImage(plot, { format: 'png', width: 500, height: 400, margin: 32, fontSize: 14, scale: 1, background: 'white' }); Plotly.newPlot = original;
      window.GraphCharts = { build: () => ({ data: [{ type: 'scatter', mode: 'markers', x: [1], y: [1], customdata: [[2]], meta: { dataRows: true, seriesId: 'data' } }], layout: {}, summary: '', warnings: [] }) };
      const chartRows = [], chartBlanks = []; const chart = document.querySelector('#chart'); await GraphWorkspace.renderChart(chart, { id: 'scatter', kind: 'scatter' }, doc, { onRowSelect: row => chartRows.push(row), onBlankClick: () => chartBlanks.push('blank') }); chart.emit('plotly_click', { points: [{ customdata: [2], data: chart.data[0] }] });
      return { symbols: observed.marker.symbol, highlighted: !!highlight, selected, series, blanks, exportedHighlights: exported[0].filter(trace => trace.meta?.observationHighlight).length, chartRows, chartBlanks };
    });
    assert.deepEqual(result.symbols, ['circle', 'circle-open', 'circle', 'circle']); assert.equal(result.highlighted, true); assert.deepEqual(result.selected, [{ seriesId: 'data', rowIndex: 1 }]); assert.deepEqual(result.series, ['data']); assert.equal(result.blanks.length, 0, 'ドラッグ操作は空白クリックを通知しない'); assert.equal(result.exportedHighlights, 0); assert.deepEqual(result.chartRows, [{ seriesId: 'data', rowIndex: 1 }]);
    console.log('row-selection-browser.test.cjs: ok');
  } finally { await browser.close(); await new Promise(resolve => server.close(resolve)); }
})().catch(error => { console.error(error); process.exitCode = 1; });
