/* Sidebar actions, persistent formatting, and reordering through the real UI. */
const assert = require('node:assert/strict');
const fs = require('node:fs'), http = require('node:http'), path = require('node:path'), os = require('node:os');
const C = require('../core.js'), Charts = require('../charts.js');
let chromium;
try { ({ chromium } = require('playwright')); }
catch { ({ chromium } = require(path.join(os.homedir(), '.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'))); }
const root = path.resolve(__dirname, '../../..');
const server = http.createServer((req,res) => {
  const file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));
  if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}
  fs.readFile(file,(error,data)=>{res.writeHead(error?404:200,{'Content-Type':file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.svg')?'image/svg+xml':'text/html'});res.end(error?'not found':data);});
});
function fixture(){
  const doc=C.createDocument();doc.name='一覧と書式';doc.parameters=[{name:'a',value:2,min:0,max:5,step:.1},{name:'b',value:1,min:0,max:5,step:.1}];
  const f=C.createSeries();Object.assign(f,{id:'f',name:'放物線',expression:'a*x^2'});
  const g=C.createSeries();Object.assign(g,{id:'g',name:'直線',expression:'x+1'});
  const d=C.createSeries('data2d');Object.assign(d,{id:'data',name:'実験値',rows:[[0,1],[1,2],[2,4]]});doc.series=[f,g,d];
  const p=C.createAnnotation('point');Object.assign(p,{id:'p',name:'点 P'});
  const q=C.createAnnotation('point');Object.assign(q,{id:'q',name:'点 Q',anchor:{type:'free',x:'2',y:'3'}});
  const segment=C.createAnnotation('segment');Object.assign(segment,{id:'segment',name:'線分 PQ',from:'p',to:'q'});doc.annotations=[p,q,segment];
  doc.charts=[Object.assign(Charts.create('scatter',{seriesId:'data',xColumn:0,yColumn:1}),{id:'chart',name:'実験値の散布図'})];
  doc.comparison.items=['main','chart'];return C.validateDocument(doc);
}
let browser,page;
(async()=>{
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  browser=await chromium.launch({channel:'chrome',headless:true});page=await browser.newPage({viewport:{width:1280,height:900},hasTouch:true});
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(process.env.GRAPH_TEST_URL||`http://127.0.0.1:${server.address().port}/tools/graph/`+'index.html');
  const settle=()=>page.waitForFunction(()=>window.GraphEditor&&!GraphEditor.getState().drawing);
  const doc=()=>page.evaluate(()=>GraphEditor.getDocument());
  const load=async value=>{await page.locator('#file-input').setInputFiles({name:'actions.graph.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(value))});await settle();};
  const row=(type,id)=>page.locator('[data-reorder-type="'+type+'"][data-reorder-id="'+id+'"]');
  const item=(type,id)=>row(type,id).locator('.object-item,.parameter-name');
  const more=(type,id)=>row(type,id).locator('.object-details');
  const menu=page.locator('#object-menu'),bar=page.locator('#selection-toolbar'),dialog=page.locator('#editor-dialog');
  const action=async(type,id,name)=>{await more(type,id).hover();await menu.waitFor({state:'visible'});await menu.getByRole('menuitem',{name,exact:true}).click();await settle();await page.mouse.move(1100,860);};
  const number=async(label,value)=>{const input=bar.getByLabel(label,{exact:true});await input.fill(value);await input.press('Tab');await settle();};
  await settle();for(const id of ['annotations-section','charts-section','parameters-section'])assert(await page.locator('#'+id).isHidden(),id);
  const onlyTable=fixture();onlyTable.annotations=[];onlyTable.charts=[];onlyTable.parameters=[];onlyTable.series=[onlyTable.series[2]];onlyTable.comparison.items=['main'];await load(onlyTable);
  assert(await page.locator('#charts-section').isHidden(),'data alone does not show the analysis heading');
  await load(fixture());for(const id of ['annotations-section','charts-section','parameters-section'])assert(await page.locator('#'+id).isVisible(),id);
  await item('series','f').click();await settle();
  assert.equal(await bar.locator('.quick-color').count(),6,'five presets and one RGB button');
  for(const label of ['線の太さ','線種','不透明度（0〜1）','点を表示','線を表示'])assert(await bar.getByLabel(label,{exact:true}).isVisible(),label);
  assert.equal(await bar.getByRole('button',{name:/非表示|表示する|複製|削除|色・線の詳細|その他の色/}).count(),0);
  await number('不透明度（0〜1）','.45');assert.equal((await doc()).series[0].style.opacity,.45);
  await bar.getByLabel('点を表示',{exact:true}).check();await settle();await bar.getByLabel('線を表示',{exact:true}).uncheck();await settle();assert.equal((await doc()).series[0].style.lines,false);
  await bar.getByLabel('自由な色（RGB）',{exact:true}).fill('#0c2238');
  await settle();assert(!await dialog.isVisible());assert.equal((await doc()).series[0].style.color,'#0c2238');assert.equal((await doc()).series[0].style.opacity,.45);
  assert.equal(await page.evaluate(()=>document.activeElement.dataset.quickControl),'custom-color');
  await page.locator('#stage').focus();await more('series','f').hover();await menu.waitFor({state:'visible'});
  assert.equal(await page.evaluate(()=>document.activeElement.id),'stage','hover does not steal focus');
  assert.deepEqual(await menu.getByRole('menuitem').allTextContents(),['非表示','複製','削除']);
  await menu.getByRole('menuitem',{name:'複製',exact:true}).hover();assert(await menu.isVisible());
  await page.mouse.move(1000,860);await menu.waitFor({state:'hidden'});
  await action('series','f','非表示');assert.equal((await doc()).series[0].visible,false);
  await action('series','f','表示');assert.equal((await doc()).series[0].visible,true);
  await action('series','f','複製');let copy=(await doc()).series[1];assert.equal(copy.expression,'a*x^2');assert.notEqual(copy.id,'f');
  await action('series',copy.id,'削除');assert.equal((await doc()).series.length,3);
  await item('series','f').click();await settle();
  const from=await item('series','f').boundingBox(),to=await item('series','g').boundingBox();
  await page.mouse.move(from.x+50,from.y+from.height/2);await page.mouse.down();await page.mouse.move(to.x+50,to.y+to.height-3,{steps:12});await page.mouse.up();await settle();
  assert.deepEqual((await doc()).series.map(s=>s.id),['g','f','data']);assert.equal((await page.evaluate(()=>GraphEditor.getState())).selected.id,'f');
  await page.locator('#undo').click();await settle();assert.deepEqual((await doc()).series.map(s=>s.id),['f','g','data'],'one Undo restores a drag');
  await page.mouse.move(from.x+50,from.y+from.height/2);await page.mouse.down();await page.mouse.move(to.x+50,to.y+to.height-3,{steps:12});await page.keyboard.press('Escape');await page.mouse.up();await settle();
  assert.deepEqual((await doc()).series.map(s=>s.id),['f','g','data'],'Escape cancels an active drag');
  await item('series','g').click();await settle();assert.equal((await page.evaluate(()=>GraphEditor.getState())).selected.id,'g','a fresh click after cancellation still selects');
  await item('series','f').focus();await page.keyboard.press('Alt+End');await settle();assert.deepEqual((await doc()).series.map(s=>s.id),['g','data','f']);
  await page.locator('#undo').click();await settle();
  await item('annotation','p').click();await settle();
  for(const label of ['名前を表示','文字サイズ（px）','横のずれ（右へ px）','縦のずれ（下へ px）','不透明度（0〜1）'])assert(await bar.getByLabel(label,{exact:true}).isVisible(),label);
  await number('横のずれ（右へ px）','25');await number('文字サイズ（px）','18');assert.equal((await doc()).annotations[0].label.dx,25);
  await action('annotation','segment','複製');copy=(await doc()).annotations.at(-1);assert.equal(copy.from,'p');assert.equal(copy.to,'q');await action('annotation',copy.id,'削除');
  await action('parameter','a','非表示');assert(await row('parameter','a').locator('input[type=range]').isHidden());assert.equal((await doc()).parameters[0].value,2);
  const hidden=await doc();await load(hidden);assert.equal((await doc()).parameters[0].visible,false,'visibility survives save/load');
  await action('parameter','a','複製');const parameter=(await doc()).parameters[1];assert.equal(parameter.name,'a_2');assert.equal(parameter.value,2);await action('parameter','a_2','削除');await action('parameter','a','表示');
  await action('chart','chart','非表示');assert.equal((await doc()).charts[0].visible,false);assert.deepEqual((await doc()).comparison.items,['main','chart']);
  await item('chart','chart').click();await settle();assert.match(await page.locator('#analysis-plot').innerText(),/非表示/);
  assert.equal(await bar.getByRole('button',{name:/複製|削除|非表示/}).count(),0);assert(await bar.getByLabel('自由な色（RGB）',{exact:true}).isVisible());
  await page.locator('#workspace-view').selectOption('comparison');await settle();assert.equal(await page.locator('.comparison-card').count(),1);
  await action('chart','chart','表示');assert.equal(await page.locator('.comparison-card').count(),2);
  await action('chart','chart','複製');copy=(await doc()).charts[1];assert.equal(copy.seriesId,'data');await action('chart',copy.id,'削除');
  await load(fixture());await item('series','f').click();await settle();await page.screenshot({path:'/private/tmp/graph-sidebar-format-desktop.png'});
  await page.mouse.move(1200,880);await page.setViewportSize({width:390,height:850});await page.locator('#list-toggle').tap();
  const cdp=await page.context().newCDPSession(page);
  const touchDrag=async(start,end)=>{await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[start]});for(let i=1;i<=10;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:start.x+(end.x-start.x)*i/10,y:start.y+(end.y-start.y)*i/10}]});await page.waitForTimeout(16);}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await settle();};
  const grip=await row('series','f').locator('[data-reorder-handle]').boundingBox(),target=await row('series','g').boundingBox();
  await touchDrag({x:grip.x+grip.width/2,y:grip.y+grip.height/2},{x:grip.x+grip.width/2,y:target.y+target.height-3});
  assert.deepEqual((await doc()).series.map(s=>s.id),['g','f','data'],'real touch drag reorders using the swatch handle');
  await touchDrag({x:150,y:310},{x:150,y:160});
  assert(await page.locator('#objects').evaluate(el=>el.scrollTop>0),'touching the row text scrolls the list');
  await page.locator('#objects').evaluate(el=>{el.scrollTop=0;});await cdp.detach();
  await more('series','f').tap();await menu.getByRole('menuitem',{name:'非表示',exact:true}).tap();await settle();
  assert.equal((await doc()).series.find(s=>s.id==='f').visible,false);await more('series','f').tap();await page.keyboard.press('Escape');assert(await menu.isHidden());
  await item('series','f').tap();await settle();await page.locator('#view-menu summary').tap();await page.locator('#theme').selectOption('dark');await page.locator('#text-size').selectOption('largest');await page.keyboard.press('Escape');await settle();
  assert(await page.locator('body').evaluate(el=>el.scrollWidth<=innerWidth));assert(await bar.getByLabel('自由な色（RGB）',{exact:true}).isVisible());await page.screenshot({path:'/private/tmp/graph-sidebar-format-mobile.png'});
  assert.deepEqual(errors,[]);console.log('sidebar-actions-browser.test.cjs: ok');
})().catch(async error=>{if(page)await page.screenshot({path:'/private/tmp/graph-sidebar-actions-failure.png'}).catch(()=>{});console.error(error);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));});
