/* Paper.js-backed geometry.  This file never owns a drawing canvas. */
(function (root) {
  'use strict';
  var sharedScope;
  function clear(scope) { if(scope.project&&scope.project.activeLayer)scope.project.activeLayer.removeChildren(); }
  function paper() { if (!root.paper || !root.paper.PaperScope) throw new Error('Paper.js is required before IlapoGeometry'); if (!sharedScope) { sharedScope=new root.paper.PaperScope(); sharedScope.setup(new sharedScope.Size(1,1)); } clear(sharedScope); return sharedScope; }
  function matrix(scope, values) { values=values||[1,0,0,1,0,0]; return new scope.Matrix(values[0],values[1],values[2],values[3],values[4],values[5]); }
  function item(scope, object) { if (!object || object.type!=='path' || typeof object.d!=='string') throw new Error('Geometry requires a path object'); var path=new scope.CompoundPath(object.d); path.matrix=matrix(scope,object.matrix); return path; }
  function bake(path) { path.applyMatrix=true; path.matrix=new path.matrix.constructor(); return path; }
  function asObject(path, source) { bake(path); return {id:'path-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),type:'path',name:(source&&source.name)||'Path',group:null,locked:false,matrix:[1,0,0,1,0,0],style:Object.assign({},source&&source.style),d:path.pathData}; }
  function flattenedPath(object) { var m=object.matrix||[1,0,0,1,0,0];if(m[0]===1&&m[1]===0&&m[2]===0&&m[3]===1)return object;var scope=paper(),path=item(scope,object);try { bake(path);return {id:object.id,type:'path',name:object.name,group:object.group,locked:object.locked,matrix:[1,0,0,1,0,0],style:Object.assign({},object.style),d:path.pathData}; } finally { clear(scope); } }
  function transformedBox(b, m) { var points=[[b.x,b.y],[b.x+b.width,b.y],[b.x,b.y+b.height],[b.x+b.width,b.y+b.height]].map(function(p){return {x:m[0]*p[0]+m[2]*p[1]+m[4],y:m[1]*p[0]+m[3]*p[1]+m[5]};}), xs=points.map(function(p){return p.x;}),ys=points.map(function(p){return p.y;}); return {x:Math.min.apply(null,xs),y:Math.min.apply(null,ys),width:Math.max.apply(null,xs)-Math.min.apply(null,xs),height:Math.max.apply(null,ys)-Math.min.apply(null,ys)}; }
  function legacyTextBounds(object) { var s=Number((object.style||{}).fontSize); if (!Number.isFinite(s) || s <= 0) s=16; var raw={x:Number(object.x)||0,y:(Number(object.y)||0)-s,width:0,height:s*1.2}; if (typeof document !== 'undefined' && document.body) { var svg=document.createElementNS('http://www.w3.org/2000/svg','svg'), text=document.createElementNS('http://www.w3.org/2000/svg','text'), style=object.style||{}; svg.setAttribute('width','1');svg.setAttribute('height','1');svg.style.cssText='position:absolute;left:-10000px;top:-10000px;visibility:hidden;overflow:visible';text.setAttribute('xml:space','preserve');text.setAttribute('x',String(Number(object.x)||0));text.setAttribute('y',String(Number(object.y)||0));text.setAttribute('font-size',String(s));text.setAttribute('font-family',style.fontFamily||'sans-serif');text.setAttribute('font-weight',style.bold?'bold':'normal');text.setAttribute('font-style',style.italic?'italic':'normal');var line=0;(object.runs||[]).forEach(function(run){String(run.text||'').split('\n').forEach(function(part,index){var span=document.createElementNS('http://www.w3.org/2000/svg','tspan');if(index){span.setAttribute('x',text.getAttribute('x'));span.setAttribute('dy',String(s*1.2));line++;}if(run.script==='super'||run.script==='sub'){span.setAttribute('baseline-shift',run.script);span.setAttribute('font-size','70%');}span.textContent=part;text.appendChild(span);});});svg.appendChild(text);document.body.appendChild(svg);try { var b=text.getBBox();raw={x:b.x,y:b.y,width:b.width,height:b.height}; } finally { svg.remove(); } } else { var lines=(object.runs||[]).map(function(r){return r.text||'';}).join('').split('\n');raw.width=Math.max.apply(null,lines.map(function(t){return t.length*s*.6;}));raw.height=Math.max(1,lines.length)*s*1.2; } return transformedBox(raw,object.matrix||[1,0,0,1,0,0]); }
  function textBounds(object) { var textLayout=root.IlapoTextLayout;if(object&&object.layout&&textLayout&&textLayout.layout){var result=textLayout.layout(object),raw=result.visualBounds||result.inkBounds||result.bounds;return transformedBox(raw,object.matrix||[1,0,0,1,0,0]);}return legacyTextBounds(object); }
  function bounds(object) { if(object.type==='connector')return root.IlapoConnectors.bounds(object,false);if(object.type==='image')return transformedBox({x:object.x,y:object.y,width:object.width,height:object.height},object.matrix);if (object.type==='text') return textBounds(object); var scope=paper(), path=item(scope,object); try { var b=path.bounds; return {x:b.x,y:b.y,width:b.width,height:b.height}; } finally { clear(scope); } }
  function visualBounds(object) {
    if(object.type==='connector')return root.IlapoConnectors.bounds(object,true);
    if(object.type==='image')return bounds(object);
    var style=object.style||{},m=object.matrix||[1,0,0,1,0,0],width=style.stroke==='none'?0:Number(style.strokeWidth)||0;
    if(object.type==='text') {
      var box=textBounds(object),join=style.linejoin==='miter'?4:1,dx=width/2*(Math.abs(m[0])+Math.abs(m[2]))*join,dy=width/2*(Math.abs(m[1])+Math.abs(m[3]))*join;
      return {x:box.x-dx,y:box.y-dy,width:box.width+2*dx,height:box.height+2*dy};
    }
    var scope=paper(),path=item(scope,object);
    try {
      path.strokeColor=style.stroke==='none'?null:style.stroke||null;path.strokeWidth=width;path.strokeCap=style.linecap||'butt';path.strokeJoin=style.linejoin||'miter';path.miterLimit=4;
      var b=path.strokeBounds,result={x:b.x,y:b.y,width:b.width,height:b.height},textLayout=root.IlapoTextLayout,label=textLayout&&textLayout.shapeText?textLayout.shapeText(object):null;
      if(label){var labelBox=visualBounds(label),right=Math.max(result.x+result.width,labelBox.x+labelBox.width),bottom=Math.max(result.y+result.height,labelBox.y+labelBox.height);result={x:Math.min(result.x,labelBox.x),y:Math.min(result.y,labelBox.y),width:right-Math.min(result.x,labelBox.x),height:bottom-Math.min(result.y,labelBox.y)};}
      return result;
    } finally { clear(scope); }
  }
  function boolean(a,b,operation) { if(['unite','subtract','intersect'].indexOf(operation)<0)throw new Error('Unsupported boolean operation');var scope=paper(), one=item(scope,a),two=item(scope,b),result=one[operation](two,{insert:false});try{return asObject(result,a);}finally{clear(scope);} }
  function paths(path) { return path.children && path.children.length ? path.children : [path]; }
  function anchors(object) { var scope=paper(), path=item(scope,object);try { bake(path);return paths(path).map(function(child){return child.segments.map(function(s){return {point:{x:s.point.x,y:s.point.y},handleIn:{x:s.handleIn.x,y:s.handleIn.y},handleOut:{x:s.handleOut.x,y:s.handleOut.y}};});}); } finally { clear(scope); } }
  function moveAnchor(object,pathIndex,anchorIndex,dx,dy) { var scope=paper(), path=item(scope,object);try { bake(path);var list=paths(path), target=list[pathIndex];if(!target||!target.segments[anchorIndex])throw new Error('Anchor is out of range');target.segments[anchorIndex].point.x+=Number(dx)||0;target.segments[anchorIndex].point.y+=Number(dy)||0;return asObject(path,object); } finally { clear(scope); } }
  var api={bounds:bounds,visualBounds:visualBounds,flattenedPath:flattenedPath,boolean:boolean,anchors:anchors,moveAnchor:moveAnchor};root.IlapoGeometry=api;if(typeof module==='object'&&module.exports)module.exports=api;
}(typeof globalThis!=='undefined'?globalThis:this));
